-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [core_models_lib_generics]
import Aeneas
import CoreModels
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace core_models_lib_generics

/-- [core_models_lib_generics::size_of_concrete]:
    Source: 'tests/src/core-models-lib-generics.rs', lines 8:0-10:1
    Visibility: public -/
def size_of_concrete : RustM Std.Usize := do
  core.mem.size_of Std.U32

/-- [core_models_lib_generics::size_of_generic]:
    Source: 'tests/src/core-models-lib-generics.rs', lines 12:0-14:1
    Visibility: public -/
def size_of_generic (T : Type) : RustM Std.Usize := do
  core.mem.size_of T

/-- [core_models_lib_generics::align_of_generic]:
    Source: 'tests/src/core-models-lib-generics.rs', lines 16:0-18:1
    Visibility: public -/
def align_of_generic (T : Type) : RustM Std.Usize := do
  core.mem.align_of T

/-- [core_models_lib_generics::vec_push]:
    Source: 'tests/src/core-models-lib-generics.rs', lines 21:0-24:1
    Visibility: public -/
def vec_push (v : alloc.vec.Vec Std.U32) : RustM (alloc.vec.Vec Std.U32) := do
  alloc.vec.Vec.push v 0#u32

/-- [core_models_lib_generics::vec_len]:
    Source: 'tests/src/core-models-lib-generics.rs', lines 26:0-28:1
    Visibility: public -/
def vec_len (v : alloc.vec.Vec Std.U32) : RustM Std.Usize := do
  alloc.vec.Vec.len v

/-- [core_models_lib_generics::vec_into_iter]:
    Source: 'tests/src/core-models-lib-generics.rs', lines 31:0-33:1
    Visibility: public -/
def vec_into_iter
  (v : alloc.vec.Vec Std.U32) :
  RustM (alloc.vec.into_iter.IntoIter Std.U32)
  := do
  alloc.vec.Vec.Insts.CoreIterTraitsCollectIntoIteratorTIntoIter.into_iter v

end core_models_lib_generics
