-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [roundtrip_lib]: function definitions
import Aeneas
import RoundtripLib.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace roundtrip_lib

/-- [roundtrip_lib::START]
    Source: 'src/lib.rs', lines 25:0-25:25
    Visibility: public -/
@[global_simps, irreducible] def START : Std.U32 := 7#u32

/-- [roundtrip_lib::{impl roundtrip_lib::Base for roundtrip_lib::Counter}::base]:
    Source: 'src/lib.rs', lines 40:4-42:5
    Visibility: public -/
def Counter.Insts.Roundtrip_libBase.base
  (self : Counter) : Result Std.U32 := do
  ok self.value

/-- Trait implementation: [roundtrip_lib::{impl roundtrip_lib::Base for roundtrip_lib::Counter}]
    Source: 'src/lib.rs', lines 39:0-43:1 -/
@[reducible]
def Counter.Insts.Roundtrip_libBase : Base Counter := {
  base := Counter.Insts.Roundtrip_libBase.base
}

/-- [roundtrip_lib::{impl roundtrip_lib::Step for roundtrip_lib::Counter}::step]:
    Source: 'src/lib.rs', lines 48:4-50:5
    Visibility: public -/
def Counter.Insts.Roundtrip_libStep.step
  (self : Counter) : Result Std.U32 := do
  ok self.value

/-- [roundtrip_lib::{impl roundtrip_lib::Step for roundtrip_lib::Counter}::STRIDE]
    Source: 'src/lib.rs', lines 46:4-46:26
    Visibility: public -/
@[global_simps, irreducible]
def Counter.Insts.Roundtrip_libStep.STRIDE : Std.U32 := 2#u32

/-- Trait implementation: [roundtrip_lib::{impl roundtrip_lib::Step for roundtrip_lib::Counter}]
    Source: 'src/lib.rs', lines 45:0-51:1 -/
@[reducible]
def Counter.Insts.Roundtrip_libStep : Step Counter := {
  STRIDE := ok Counter.Insts.Roundtrip_libStep.STRIDE
  BaseInst := Counter.Insts.Roundtrip_libBase
  step := Counter.Insts.Roundtrip_libStep.step
}

/-- [roundtrip_lib::add_one]:
    Source: 'src/lib.rs', lines 53:0-55:1
    Visibility: public -/
def add_one (x : Std.U32) : Result Std.U32 := do
  x + 1#u32

/-- [roundtrip_lib::sum_to]: loop body 0:
    Source: 'src/lib.rs', lines 64:4-67:5
    Visibility: public -/
@[rust_loop_body]
def sum_to_loop.body
  (n : Std.U32) (s : Std.U32) (i : Std.U32) :
  Result (ControlFlow (Std.U32 × Std.U32) Std.U32)
  := do
  if i < n
  then let s1 ← s + i
       let i1 ← i + 1#u32
       ok (cont (s1, i1))
  else ok (done s)

/-- [roundtrip_lib::sum_to]: loop 0:
    Source: 'src/lib.rs', lines 64:4-67:5
    Visibility: public -/
@[rust_loop]
def sum_to_loop
  (n : Std.U32) (s : Std.U32) (i : Std.U32) : Result Std.U32 := do
  loop
    (fun (s1, i1) => sum_to_loop.body n s1 i1)
    (s, i)

/-- [roundtrip_lib::sum_to]:
    Source: 'src/lib.rs', lines 61:0-69:1
    Visibility: public -/
@[reducible]
def sum_to (n : Std.U32) : Result Std.U32 := do
  sum_to_loop n 0#u32 0#u32

end roundtrip_lib
