-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [roundtrip_lib]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace roundtrip_lib

/-- [roundtrip_lib::Counter]
    Source: 'src/lib.rs', lines 11:0-13:1
    Visibility: public -/
structure Counter where
  value : Std.U32

/-- [roundtrip_lib::Bound]
    Source: 'src/lib.rs', lines 17:0-20:1
    Visibility: public -/
@[discriminant isize]
inductive Bound where
| Below : Bound
| Above : Bound

/-- Trait declaration: [roundtrip_lib::Base]
    Source: 'src/lib.rs', lines 27:0-29:1
    Visibility: public -/
structure Base (Self : Type) where
  base : Self → Result Std.U32

/-- Trait declaration: [roundtrip_lib::Step]
    Source: 'src/lib.rs', lines 33:0-37:1
    Visibility: public -/
structure Step (Self : Type) where
  STRIDE : Result Std.U32
  BaseInst : Base Self
  step : Self → Result Std.U32

end roundtrip_lib
