// AUTO-GENERATED by gen-diff-tests; do not edit.
// Regenerate with `cargo run --bin gen-diff-tests`.
//
// R₀ side of the auto-generated diff harness: each `<fixture>`
// module brings in the unmodified Rust source from `tests/src/` via
// `#[path]`. The diff harness calls the *original* fns directly —
// no reshape, because the amenable-signature filter rejects any fn
// whose source signature carries `&mut`, `&T`, or generic params.

#![allow(unused_variables, dead_code, non_snake_case, unused_parens, unused_mut, unused_imports, unused_assignments, clippy::all)]

#[path = "../../../../tests/src/aggregates_basic.rs"]
#[allow(unused_variables, dead_code, non_snake_case, unused_parens, unused_mut, unused_imports, unused_assignments, clippy::all)]
pub mod aggregates_basic;
#[path = "../../../../tests/src/assert-cfg.rs"]
#[allow(unused_variables, dead_code, non_snake_case, unused_parens, unused_mut, unused_imports, unused_assignments, clippy::all)]
pub mod assert_cfg;
#[path = "../../../../tests/src/bitwise.rs"]
#[allow(unused_variables, dead_code, non_snake_case, unused_parens, unused_mut, unused_imports, unused_assignments, clippy::all)]
pub mod bitwise;
#[path = "../../../../tests/src/compare_simple.rs"]
#[allow(unused_variables, dead_code, non_snake_case, unused_parens, unused_mut, unused_imports, unused_assignments, clippy::all)]
pub mod compare_simple;
#[path = "../../../../tests/src/demo.rs"]
#[allow(unused_variables, dead_code, non_snake_case, unused_parens, unused_mut, unused_imports, unused_assignments, clippy::all)]
pub mod demo;
#[path = "../../../../tests/src/incr_cert.rs"]
#[allow(unused_variables, dead_code, non_snake_case, unused_parens, unused_mut, unused_imports, unused_assignments, clippy::all)]
pub mod incr_cert;
#[path = "../../../../tests/src/scalars.rs"]
#[allow(unused_variables, dead_code, non_snake_case, unused_parens, unused_mut, unused_imports, unused_assignments, clippy::all)]
pub mod scalars;
