// AUTO-GENERATED by gen-diff-tests; do not edit.
// Regenerate with `cargo run --bin gen-diff-tests`.
//
// Each proptest block was synthesised from a Pure-IR fixture whose
// signature is simple enough to drive `any::<...>()` directly:
// all-scalar / fixed-size-scalar-array / tuple-of-scalars inputs,
// scalar / tuple / array output (optionally wrapped in
// `Result<_, ()>`), no generics, no refs.
//
// The R₂ side (`models::<fixture>`) is the committed pir2rs snapshot
// at `tests/models/<fixture>_pir.rs`; the R₀ side
// (`ref_impl_auto::<fixture>`) imports the source directly from
// `tests/src/<fixture>.rs` (no reshape — the filter rejects any fn
// the IR would have functionalised).
//
// Mismatches are marked `#[ignore]`d inline with one of:
//   * `EMITTER BUG`: the model produces a different value than the
//     source for at least one input — surfaces an emitter limitation.
//   * `DIFF NON-UNIFORM`: the comparison can't be driven by uniform
//     `any::<_>()` (e.g. recursion-depth-bounded inputs).

#![allow(unused_variables, dead_code, non_snake_case, unused_parens, unused_mut, unused_imports, clippy::all)]

use proptest::prelude::*;

#[path = "common/ref_impl_auto.rs"]
mod ref_impl_auto;

#[allow(
    unused_variables,
    unused_parens,
    unused_mut,
    dead_code,
    non_snake_case,
    nonstandard_style,
    unused_assignments,
    unused_imports,
    unreachable_code,
    clippy::all
)]
mod models {
    pub mod aggregates_basic { include!("models/aggregates_basic_pir.rs"); }
    pub mod assert_cfg { include!("models/assert-cfg_pir.rs"); }
    pub mod bitwise { include!("models/bitwise_pir.rs"); }
    pub mod calls { include!("models/calls_pir.rs"); }
    pub mod compare_simple { include!("models/compare_simple_pir.rs"); }
    pub mod demo { include!("models/demo_pir.rs"); }
    pub mod incr_cert { include!("models/incr_cert_pir.rs"); }
    pub mod scalars { include!("models/scalars_pir.rs"); }
}

// =====================================================================
// aggregates_basic — auto-generated (1 candidates, 1 total scanned)
// =====================================================================

proptest! {
/// Auto-generated from `aggregates_basic::mk_tuple` (model `aggregates_basic_mk_tuple_0`)
    #[test]
fn aggregates_basic_mk_tuple_auto(a0 in any::<u32>(), a1 in any::<u32>()) {
        let lhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| ref_impl_auto::aggregates_basic::mk_tuple(a0, a1))) {
Ok(v) => Ok::<_, ()>(v),
Err(_) => Err(()),
};
let rhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| models::aggregates_basic::aggregates_basic_mk_tuple_0(a0, a1))) {
Ok(r) => r.map_err(|_| ()),
Err(_) => Err(()),
};
prop_assert_eq!(lhs, rhs);
}
}

// =====================================================================
// assert-cfg — auto-generated (27 candidates, 32 total scanned)
// =====================================================================

proptest! {
/// Auto-generated from `assert_cfg::assert_arith` (model `assert_cfg_assert_arith_29`)
    #[test]
fn assert_cfg_assert_arith_auto(a0 in any::<u32>(), a1 in any::<u32>()) {
        let lhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| ref_impl_auto::assert_cfg::assert_arith(a0, a1))) {
Ok(v) => Ok::<_, ()>(v),
Err(_) => Err(()),
};
let rhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| models::assert_cfg::assert_cfg_assert_arith_29(a0, a1))) {
Ok(r) => r.map_err(|_| ()),
Err(_) => Err(()),
};
prop_assert_eq!(lhs, rhs);
}
}

proptest! {
/// Auto-generated from `assert_cfg::assert_lt` (model `assert_cfg_assert_lt_23`)
    #[test]
fn assert_cfg_assert_lt_auto(a0 in any::<u32>()) {
        let lhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| ref_impl_auto::assert_cfg::assert_lt(a0))) {
Ok(v) => Ok::<_, ()>(v),
Err(_) => Err(()),
};
let rhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| models::assert_cfg::assert_cfg_assert_lt_23(a0))) {
Ok(r) => r.map_err(|_| ()),
Err(_) => Err(()),
};
prop_assert_eq!(lhs, rhs);
}
}

proptest! {
/// Auto-generated from `assert_cfg::assert_le` (model `assert_cfg_assert_le_24`)
    #[test]
fn assert_cfg_assert_le_auto(a0 in any::<u32>()) {
        let lhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| ref_impl_auto::assert_cfg::assert_le(a0))) {
Ok(v) => Ok::<_, ()>(v),
Err(_) => Err(()),
};
let rhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| models::assert_cfg::assert_cfg_assert_le_24(a0))) {
Ok(r) => r.map_err(|_| ()),
Err(_) => Err(()),
};
prop_assert_eq!(lhs, rhs);
}
}

proptest! {
/// Auto-generated from `assert_cfg::assert_gt` (model `assert_cfg_assert_gt_25`)
    #[test]
fn assert_cfg_assert_gt_auto(a0 in any::<u32>()) {
        let lhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| ref_impl_auto::assert_cfg::assert_gt(a0))) {
Ok(v) => Ok::<_, ()>(v),
Err(_) => Err(()),
};
let rhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| models::assert_cfg::assert_cfg_assert_gt_25(a0))) {
Ok(r) => r.map_err(|_| ()),
Err(_) => Err(()),
};
prop_assert_eq!(lhs, rhs);
}
}

proptest! {
/// Auto-generated from `assert_cfg::assert_ge` (model `assert_cfg_assert_ge_26`)
    #[test]
fn assert_cfg_assert_ge_auto(a0 in any::<u32>()) {
        let lhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| ref_impl_auto::assert_cfg::assert_ge(a0))) {
Ok(v) => Ok::<_, ()>(v),
Err(_) => Err(()),
};
let rhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| models::assert_cfg::assert_cfg_assert_ge_26(a0))) {
Ok(r) => r.map_err(|_| ()),
Err(_) => Err(()),
};
prop_assert_eq!(lhs, rhs);
}
}

proptest! {
/// Auto-generated from `assert_cfg::assert_eq` (model `assert_cfg_assert_eq_27`)
    #[test]
fn assert_cfg_assert_eq_auto(a0 in any::<u32>()) {
        let lhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| ref_impl_auto::assert_cfg::assert_eq(a0))) {
Ok(v) => Ok::<_, ()>(v),
Err(_) => Err(()),
};
let rhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| models::assert_cfg::assert_cfg_assert_eq_27(a0))) {
Ok(r) => r.map_err(|_| ()),
Err(_) => Err(()),
};
prop_assert_eq!(lhs, rhs);
}
}

proptest! {
/// Auto-generated from `assert_cfg::assert_ne` (model `assert_cfg_assert_ne_28`)
    #[test]
fn assert_cfg_assert_ne_auto(a0 in any::<u32>()) {
        let lhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| ref_impl_auto::assert_cfg::assert_ne(a0))) {
Ok(v) => Ok::<_, ()>(v),
Err(_) => Err(()),
};
let rhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| models::assert_cfg::assert_cfg_assert_ne_28(a0))) {
Ok(r) => r.map_err(|_| ()),
Err(_) => Err(()),
};
prop_assert_eq!(lhs, rhs);
}
}

proptest! {
/// Auto-generated from `assert_cfg::assert_or` (model `assert_cfg_assert_or_3`)
    #[test]
fn assert_cfg_assert_or_auto(a0 in any::<bool>(), a1 in any::<bool>()) {
        let lhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| ref_impl_auto::assert_cfg::assert_or(a0, a1))) {
Ok(v) => Ok::<_, ()>(v),
Err(_) => Err(()),
};
let rhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| models::assert_cfg::assert_cfg_assert_or_3(a0, a1))) {
Ok(r) => r.map_err(|_| ()),
Err(_) => Err(()),
};
prop_assert_eq!(lhs, rhs);
}
}

proptest! {
/// Auto-generated from `assert_cfg::assert_not_and` (model `assert_cfg_assert_not_and_6`)
    #[test]
fn assert_cfg_assert_not_and_auto(a0 in any::<bool>(), a1 in any::<bool>()) {
        let lhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| ref_impl_auto::assert_cfg::assert_not_and(a0, a1))) {
Ok(v) => Ok::<_, ()>(v),
Err(_) => Err(()),
};
let rhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| models::assert_cfg::assert_cfg_assert_not_and_6(a0, a1))) {
Ok(r) => r.map_err(|_| ()),
Err(_) => Err(()),
};
prop_assert_eq!(lhs, rhs);
}
}

proptest! {
/// Auto-generated from `assert_cfg::assert_not_b0_or_b1` (model `assert_cfg_assert_not_b0_or_b1_7`)
    #[test]
fn assert_cfg_assert_not_b0_or_b1_auto(a0 in any::<bool>(), a1 in any::<bool>()) {
        let lhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| ref_impl_auto::assert_cfg::assert_not_b0_or_b1(a0, a1))) {
Ok(v) => Ok::<_, ()>(v),
Err(_) => Err(()),
};
let rhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| models::assert_cfg::assert_cfg_assert_not_b0_or_b1_7(a0, a1))) {
Ok(r) => r.map_err(|_| ()),
Err(_) => Err(()),
};
prop_assert_eq!(lhs, rhs);
}
}

proptest! {
/// Auto-generated from `assert_cfg::assert_b0_or_not_b1` (model `assert_cfg_assert_b0_or_not_b1_8`)
    #[test]
fn assert_cfg_assert_b0_or_not_b1_auto(a0 in any::<bool>(), a1 in any::<bool>()) {
        let lhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| ref_impl_auto::assert_cfg::assert_b0_or_not_b1(a0, a1))) {
Ok(v) => Ok::<_, ()>(v),
Err(_) => Err(()),
};
let rhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| models::assert_cfg::assert_cfg_assert_b0_or_not_b1_8(a0, a1))) {
Ok(r) => r.map_err(|_| ()),
Err(_) => Err(()),
};
prop_assert_eq!(lhs, rhs);
}
}

proptest! {
/// Auto-generated from `assert_cfg::assert_not_b0_or_not_b1` (model `assert_cfg_assert_not_b0_or_not_b1_9`)
    #[test]
fn assert_cfg_assert_not_b0_or_not_b1_auto(a0 in any::<bool>(), a1 in any::<bool>()) {
        let lhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| ref_impl_auto::assert_cfg::assert_not_b0_or_not_b1(a0, a1))) {
Ok(v) => Ok::<_, ()>(v),
Err(_) => Err(()),
};
let rhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| models::assert_cfg::assert_cfg_assert_not_b0_or_not_b1_9(a0, a1))) {
Ok(r) => r.map_err(|_| ()),
Err(_) => Err(()),
};
prop_assert_eq!(lhs, rhs);
}
}

/// Auto-generated from `assert_cfg::assert_or_call` (no-arg, model `assert_cfg_assert_or_call_13`)
#[test]
fn assert_cfg_assert_or_call_auto() {
let lhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| ref_impl_auto::assert_cfg::assert_or_call())) {
Ok(v) => Ok::<_, ()>(v),
Err(_) => Err(()),
};
let rhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| models::assert_cfg::assert_cfg_assert_or_call_13())) {
Ok(r) => r.map_err(|_| ()),
Err(_) => Err(()),
};
assert_eq!(lhs, rhs);
}

/// Auto-generated from `assert_cfg::assert_not_and_call` (no-arg, model `assert_cfg_assert_not_and_call_16`)
#[test]
fn assert_cfg_assert_not_and_call_auto() {
let lhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| ref_impl_auto::assert_cfg::assert_not_and_call())) {
Ok(v) => Ok::<_, ()>(v),
Err(_) => Err(()),
};
let rhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| models::assert_cfg::assert_cfg_assert_not_and_call_16())) {
Ok(r) => r.map_err(|_| ()),
Err(_) => Err(()),
};
assert_eq!(lhs, rhs);
}

/// Auto-generated from `assert_cfg::assert_not_b0_or_b1_call` (no-arg, model `assert_cfg_assert_not_b0_or_b1_call_17`)
#[test]
fn assert_cfg_assert_not_b0_or_b1_call_auto() {
let lhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| ref_impl_auto::assert_cfg::assert_not_b0_or_b1_call())) {
Ok(v) => Ok::<_, ()>(v),
Err(_) => Err(()),
};
let rhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| models::assert_cfg::assert_cfg_assert_not_b0_or_b1_call_17())) {
Ok(r) => r.map_err(|_| ()),
Err(_) => Err(()),
};
assert_eq!(lhs, rhs);
}

/// Auto-generated from `assert_cfg::assert_b0_or_not_b1_call` (no-arg, model `assert_cfg_assert_b0_or_not_b1_call_18`)
#[test]
fn assert_cfg_assert_b0_or_not_b1_call_auto() {
let lhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| ref_impl_auto::assert_cfg::assert_b0_or_not_b1_call())) {
Ok(v) => Ok::<_, ()>(v),
Err(_) => Err(()),
};
let rhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| models::assert_cfg::assert_cfg_assert_b0_or_not_b1_call_18())) {
Ok(r) => r.map_err(|_| ()),
Err(_) => Err(()),
};
assert_eq!(lhs, rhs);
}

/// Auto-generated from `assert_cfg::assert_not_b0_or_not_b1_call` (no-arg, model `assert_cfg_assert_not_b0_or_not_b1_call_19`)
#[test]
fn assert_cfg_assert_not_b0_or_not_b1_call_auto() {
let lhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| ref_impl_auto::assert_cfg::assert_not_b0_or_not_b1_call())) {
Ok(v) => Ok::<_, ()>(v),
Err(_) => Err(()),
};
let rhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| models::assert_cfg::assert_cfg_assert_not_b0_or_not_b1_call_19())) {
Ok(r) => r.map_err(|_| ()),
Err(_) => Err(()),
};
assert_eq!(lhs, rhs);
}

proptest! {
/// Auto-generated from `assert_cfg::assert_and` (model `assert_cfg_assert_and_4`)
    #[test]
fn assert_cfg_assert_and_auto(a0 in any::<bool>(), a1 in any::<bool>()) {
        let lhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| ref_impl_auto::assert_cfg::assert_and(a0, a1))) {
Ok(v) => Ok::<_, ()>(v),
Err(_) => Err(()),
};
let rhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| models::assert_cfg::assert_cfg_assert_and_4(a0, a1))) {
Ok(r) => r.map_err(|_| ()),
Err(_) => Err(()),
};
prop_assert_eq!(lhs, rhs);
}
}

proptest! {
/// Auto-generated from `assert_cfg::assert_not_or` (model `assert_cfg_assert_not_or_5`)
    #[test]
fn assert_cfg_assert_not_or_auto(a0 in any::<bool>(), a1 in any::<bool>()) {
        let lhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| ref_impl_auto::assert_cfg::assert_not_or(a0, a1))) {
Ok(v) => Ok::<_, ()>(v),
Err(_) => Err(()),
};
let rhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| models::assert_cfg::assert_cfg_assert_not_or_5(a0, a1))) {
Ok(r) => r.map_err(|_| ()),
Err(_) => Err(()),
};
prop_assert_eq!(lhs, rhs);
}
}

proptest! {
/// Auto-generated from `assert_cfg::assert_not_b0_and_b1` (model `assert_cfg_assert_not_b0_and_b1_10`)
    #[test]
fn assert_cfg_assert_not_b0_and_b1_auto(a0 in any::<bool>(), a1 in any::<bool>()) {
        let lhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| ref_impl_auto::assert_cfg::assert_not_b0_and_b1(a0, a1))) {
Ok(v) => Ok::<_, ()>(v),
Err(_) => Err(()),
};
let rhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| models::assert_cfg::assert_cfg_assert_not_b0_and_b1_10(a0, a1))) {
Ok(r) => r.map_err(|_| ()),
Err(_) => Err(()),
};
prop_assert_eq!(lhs, rhs);
}
}

proptest! {
/// Auto-generated from `assert_cfg::assert_b0_and_not_b1` (model `assert_cfg_assert_b0_and_not_b1_11`)
    #[test]
fn assert_cfg_assert_b0_and_not_b1_auto(a0 in any::<bool>(), a1 in any::<bool>()) {
        let lhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| ref_impl_auto::assert_cfg::assert_b0_and_not_b1(a0, a1))) {
Ok(v) => Ok::<_, ()>(v),
Err(_) => Err(()),
};
let rhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| models::assert_cfg::assert_cfg_assert_b0_and_not_b1_11(a0, a1))) {
Ok(r) => r.map_err(|_| ()),
Err(_) => Err(()),
};
prop_assert_eq!(lhs, rhs);
}
}

proptest! {
/// Auto-generated from `assert_cfg::assert_not_b0_and_not_b1` (model `assert_cfg_assert_not_b0_and_not_b1_12`)
    #[test]
fn assert_cfg_assert_not_b0_and_not_b1_auto(a0 in any::<bool>(), a1 in any::<bool>()) {
        let lhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| ref_impl_auto::assert_cfg::assert_not_b0_and_not_b1(a0, a1))) {
Ok(v) => Ok::<_, ()>(v),
Err(_) => Err(()),
};
let rhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| models::assert_cfg::assert_cfg_assert_not_b0_and_not_b1_12(a0, a1))) {
Ok(r) => r.map_err(|_| ()),
Err(_) => Err(()),
};
prop_assert_eq!(lhs, rhs);
}
}

/// Auto-generated from `assert_cfg::assert_and_call` (no-arg, model `assert_cfg_assert_and_call_14`)
#[test]
fn assert_cfg_assert_and_call_auto() {
let lhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| ref_impl_auto::assert_cfg::assert_and_call())) {
Ok(v) => Ok::<_, ()>(v),
Err(_) => Err(()),
};
let rhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| models::assert_cfg::assert_cfg_assert_and_call_14())) {
Ok(r) => r.map_err(|_| ()),
Err(_) => Err(()),
};
assert_eq!(lhs, rhs);
}

/// Auto-generated from `assert_cfg::assert_not_or_call` (no-arg, model `assert_cfg_assert_not_or_call_15`)
#[test]
fn assert_cfg_assert_not_or_call_auto() {
let lhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| ref_impl_auto::assert_cfg::assert_not_or_call())) {
Ok(v) => Ok::<_, ()>(v),
Err(_) => Err(()),
};
let rhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| models::assert_cfg::assert_cfg_assert_not_or_call_15())) {
Ok(r) => r.map_err(|_| ()),
Err(_) => Err(()),
};
assert_eq!(lhs, rhs);
}

/// Auto-generated from `assert_cfg::assert_not_b0_and_b1_call` (no-arg, model `assert_cfg_assert_not_b0_and_b1_call_20`)
#[test]
fn assert_cfg_assert_not_b0_and_b1_call_auto() {
let lhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| ref_impl_auto::assert_cfg::assert_not_b0_and_b1_call())) {
Ok(v) => Ok::<_, ()>(v),
Err(_) => Err(()),
};
let rhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| models::assert_cfg::assert_cfg_assert_not_b0_and_b1_call_20())) {
Ok(r) => r.map_err(|_| ()),
Err(_) => Err(()),
};
assert_eq!(lhs, rhs);
}

/// Auto-generated from `assert_cfg::assert_b0_and_not_b1_call` (no-arg, model `assert_cfg_assert_b0_and_not_b1_call_21`)
#[test]
fn assert_cfg_assert_b0_and_not_b1_call_auto() {
let lhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| ref_impl_auto::assert_cfg::assert_b0_and_not_b1_call())) {
Ok(v) => Ok::<_, ()>(v),
Err(_) => Err(()),
};
let rhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| models::assert_cfg::assert_cfg_assert_b0_and_not_b1_call_21())) {
Ok(r) => r.map_err(|_| ()),
Err(_) => Err(()),
};
assert_eq!(lhs, rhs);
}

/// Auto-generated from `assert_cfg::assert_not_b0_and_not_b1_call` (no-arg, model `assert_cfg_assert_not_b0_and_not_b1_call_22`)
#[test]
fn assert_cfg_assert_not_b0_and_not_b1_call_auto() {
let lhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| ref_impl_auto::assert_cfg::assert_not_b0_and_not_b1_call())) {
Ok(v) => Ok::<_, ()>(v),
Err(_) => Err(()),
};
let rhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| models::assert_cfg::assert_cfg_assert_not_b0_and_not_b1_call_22())) {
Ok(r) => r.map_err(|_| ()),
Err(_) => Err(()),
};
assert_eq!(lhs, rhs);
}

// =====================================================================
// bitwise — auto-generated (5 candidates, 5 total scanned)
// =====================================================================

proptest! {
/// Auto-generated from `bitwise::shift_u32` (model `bitwise_shift_u32_0`)
    #[test]
fn bitwise_shift_u32_auto(a0 in any::<u32>()) {
        let lhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| ref_impl_auto::bitwise::shift_u32(a0))) {
Ok(v) => Ok::<_, ()>(v),
Err(_) => Err(()),
};
let rhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| models::bitwise::bitwise_shift_u32_0(a0))) {
Ok(r) => r.map_err(|_| ()),
Err(_) => Err(()),
};
prop_assert_eq!(lhs, rhs);
}
}

proptest! {
/// Auto-generated from `bitwise::shift_i32` (model `bitwise_shift_i32_1`)
    #[test]
fn bitwise_shift_i32_auto(a0 in any::<i32>()) {
        let lhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| ref_impl_auto::bitwise::shift_i32(a0))) {
Ok(v) => Ok::<_, ()>(v),
Err(_) => Err(()),
};
let rhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| models::bitwise::bitwise_shift_i32_1(a0))) {
Ok(r) => r.map_err(|_| ()),
Err(_) => Err(()),
};
prop_assert_eq!(lhs, rhs);
}
}

proptest! {
/// Auto-generated from `bitwise::xor_u32` (model `bitwise_xor_u32_2`)
    #[test]
fn bitwise_xor_u32_auto(a0 in any::<u32>(), a1 in any::<u32>()) {
        let lhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| ref_impl_auto::bitwise::xor_u32(a0, a1))) {
Ok(v) => Ok::<_, ()>(v),
Err(_) => Err(()),
};
let rhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| models::bitwise::bitwise_xor_u32_2(a0, a1))) {
Ok(r) => r.map_err(|_| ()),
Err(_) => Err(()),
};
prop_assert_eq!(lhs, rhs);
}
}

proptest! {
/// Auto-generated from `bitwise::or_u32` (model `bitwise_or_u32_3`)
    #[test]
fn bitwise_or_u32_auto(a0 in any::<u32>(), a1 in any::<u32>()) {
        let lhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| ref_impl_auto::bitwise::or_u32(a0, a1))) {
Ok(v) => Ok::<_, ()>(v),
Err(_) => Err(()),
};
let rhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| models::bitwise::bitwise_or_u32_3(a0, a1))) {
Ok(r) => r.map_err(|_| ()),
Err(_) => Err(()),
};
prop_assert_eq!(lhs, rhs);
}
}

proptest! {
/// Auto-generated from `bitwise::and_u32` (model `bitwise_and_u32_4`)
    #[test]
fn bitwise_and_u32_auto(a0 in any::<u32>(), a1 in any::<u32>()) {
        let lhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| ref_impl_auto::bitwise::and_u32(a0, a1))) {
Ok(v) => Ok::<_, ()>(v),
Err(_) => Err(()),
};
let rhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| models::bitwise::bitwise_and_u32_4(a0, a1))) {
Ok(r) => r.map_err(|_| ()),
Err(_) => Err(()),
};
prop_assert_eq!(lhs, rhs);
}
}

// =====================================================================
// calls — auto-generated (1 candidates, 4 total scanned)
// =====================================================================

proptest! {
/// Auto-generated from `calls::pick` (model `calls_pick_4`)
    #[test]
fn calls_pick_auto(a0 in any::<bool>(), a1 in any::<u32>(), a2 in any::<u32>()) {
        let lhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| ref_impl_auto::calls::pick(a0, a1, a2))) {
Ok(v) => Ok::<_, ()>(v),
Err(_) => Err(()),
};
let rhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| models::calls::calls_pick_4(a0, a1, a2))) {
Ok(r) => r.map_err(|_| ()),
Err(_) => Err(()),
};
prop_assert_eq!(lhs, rhs);
}
}

// =====================================================================
// compare_simple — auto-generated (2 candidates, 3 total scanned)
// =====================================================================

proptest! {
/// Auto-generated from `compare_simple::add_u32` (model `compare_simple_add_u32_2`)
    #[test]
fn compare_simple_add_u32_auto(a0 in any::<u32>(), a1 in any::<u32>()) {
        let lhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| ref_impl_auto::compare_simple::add_u32(a0, a1))) {
Ok(v) => Ok::<_, ()>(v),
Err(_) => Err(()),
};
let rhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| models::compare_simple::compare_simple_add_u32_2(a0, a1))) {
Ok(r) => r.map_err(|_| ()),
Err(_) => Err(()),
};
prop_assert_eq!(lhs, rhs);
}
}

proptest! {
/// Auto-generated from `compare_simple::id_u32` (model `compare_simple_id_u32_0`)
    #[test]
fn compare_simple_id_u32_auto(a0 in any::<u32>()) {
        let lhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| ref_impl_auto::compare_simple::id_u32(a0))) {
Ok(v) => Ok::<_, ()>(v),
Err(_) => Err(()),
};
let rhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| models::compare_simple::compare_simple_id_u32_0(a0))) {
Ok(r) => r.map_err(|_| ()),
Err(_) => Err(()),
};
prop_assert_eq!(lhs, rhs);
}
}

// =====================================================================
// demo — auto-generated (3 candidates, 5 total scanned)
// =====================================================================

/// Auto-generated from `demo::use_incr` (no-arg, model `demo_use_incr_4`)
#[test]
fn demo_use_incr_auto() {
let lhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| ref_impl_auto::demo::use_incr())) {
Ok(v) => Ok::<_, ()>(v),
Err(_) => Err(()),
};
let rhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| models::demo::demo_use_incr_4())) {
Ok(r) => r.map_err(|_| ()),
Err(_) => Err(()),
};
assert_eq!(lhs, rhs);
}

proptest! {
/// Auto-generated from `demo::mul2_add1` (model `demo_mul2_add1_1`)
    #[test]
fn demo_mul2_add1_auto(a0 in any::<u32>()) {
        let lhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| ref_impl_auto::demo::mul2_add1(a0))) {
Ok(v) => Ok::<_, ()>(v),
Err(_) => Err(()),
};
let rhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| models::demo::demo_mul2_add1_1(a0))) {
Ok(r) => r.map_err(|_| ()),
Err(_) => Err(()),
};
prop_assert_eq!(lhs, rhs);
}
}

proptest! {
/// Auto-generated from `demo::use_mul2_add1` (model `demo_use_mul2_add1_2`)
    #[test]
fn demo_use_mul2_add1_auto(a0 in any::<u32>(), a1 in any::<u32>()) {
        let lhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| ref_impl_auto::demo::use_mul2_add1(a0, a1))) {
Ok(v) => Ok::<_, ()>(v),
Err(_) => Err(()),
};
let rhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| models::demo::demo_use_mul2_add1_2(a0, a1))) {
Ok(r) => r.map_err(|_| ()),
Err(_) => Err(()),
};
prop_assert_eq!(lhs, rhs);
}
}

// =====================================================================
// incr_cert — auto-generated (1 candidates, 2 total scanned)
// =====================================================================

proptest! {
/// Auto-generated from `incr_cert::incr_local` (model `incr_cert_incr_local_1`)
    #[test]
fn incr_cert_incr_local_auto(a0 in any::<u32>()) {
        let lhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| ref_impl_auto::incr_cert::incr_local(a0))) {
Ok(v) => Ok::<_, ()>(v),
Err(_) => Err(()),
};
let rhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| models::incr_cert::incr_cert_incr_local_1(a0))) {
Ok(r) => r.map_err(|_| ()),
Err(_) => Err(()),
};
prop_assert_eq!(lhs, rhs);
}
}

// =====================================================================
// scalars — auto-generated (2 candidates, 23 total scanned)
// =====================================================================

/// Auto-generated from `scalars::u32_use_bits` (no-arg, model `scalars_u32_use_bits_21`)
#[ignore = "EMITTER BUG: u32::BITS const resolves to 0 in model"]
#[test]
fn scalars_u32_use_bits_auto() {
let lhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| ref_impl_auto::scalars::u32_use_bits())) {
Ok(v) => Ok::<_, ()>(v),
Err(_) => Err(()),
};
let rhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| models::scalars::scalars_u32_use_bits_21())) {
Ok(r) => r.map_err(|_| ()),
Err(_) => Err(()),
};
assert_eq!(lhs, rhs);
}

/// Auto-generated from `scalars::i32_use_bits` (no-arg, model `scalars_i32_use_bits_22`)
#[ignore = "EMITTER BUG: i32::BITS const resolves to 0 in model"]
#[test]
fn scalars_i32_use_bits_auto() {
let lhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| ref_impl_auto::scalars::i32_use_bits())) {
Ok(v) => Ok::<_, ()>(v),
Err(_) => Err(()),
};
let rhs = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| models::scalars::scalars_i32_use_bits_22())) {
Ok(r) => r.map_err(|_| ()),
Err(_) => Err(()),
};
assert_eq!(lhs, rhs);
}

