// AUTO-GENERATED by `meta-harness --generate-tests`. DO NOT EDIT.
// Each `proptest!` block was synthesised from a cert.json fn whose
// signature is simple enough to drive `any::<...>()` directly
// (all-scalar / fixed-size-scalar-array / simple-struct inputs +
// scalar / tuple-of-scalars / array / simple-struct output, no
// generics, no refs).
//
// To regenerate:
//   meta-harness --generate-tests \
//     --sweep tests/llbc \
//     --tests-src-dir tests/src \
//     --tests-out tests/lean-checker/differential/tests/diff_auto.rs

#![allow(unused_variables, dead_code, non_snake_case, unused_parens, unused_mut)]

#[path = "../../../tests/src/aggregates_basic.rs"]
#[allow(unused_variables, dead_code, non_snake_case, unused_parens, unused_mut)]
mod aggregates_basic_src;
#[path = "../../../tests/src/arrays.rs"]
#[allow(unused_variables, dead_code, non_snake_case, unused_parens, unused_mut)]
mod arrays_src;
#[path = "../../../tests/src/arrays_defs.rs"]
#[allow(unused_variables, dead_code, non_snake_case, unused_parens, unused_mut)]
mod arrays_defs_src;
#[path = "../../../tests/src/bitwise.rs"]
#[allow(unused_variables, dead_code, non_snake_case, unused_parens, unused_mut)]
mod bitwise_src;
#[path = "../../../tests/src/calls.rs"]
#[allow(unused_variables, dead_code, non_snake_case, unused_parens, unused_mut)]
mod calls_src;
#[path = "../src/fixtures/chunks_exact.rs"]
#[allow(unused_variables, dead_code, non_snake_case, unused_parens, unused_mut)]
mod chunks_exact_src;
#[path = "../../../tests/src/compare_simple.rs"]
#[allow(unused_variables, dead_code, non_snake_case, unused_parens, unused_mut)]
mod compare_simple_src;
#[path = "../../../tests/src/constants.rs"]
#[allow(unused_variables, dead_code, non_snake_case, unused_parens, unused_mut)]
mod constants_src;
#[path = "../../../tests/src/demo.rs"]
#[allow(unused_variables, dead_code, non_snake_case, unused_parens, unused_mut)]
mod demo_src;
#[path = "../../../tests/src/deref.rs"]
#[allow(unused_variables, dead_code, non_snake_case, unused_parens, unused_mut)]
mod deref_src;
#[path = "../../../tests/src/incr_cert.rs"]
#[allow(unused_variables, dead_code, non_snake_case, unused_parens, unused_mut)]
mod incr_cert_src;
#[path = "../../../tests/src/loops.rs"]
#[allow(unused_variables, dead_code, non_snake_case, unused_parens, unused_mut)]
mod loops_src;
#[path = "../../../tests/src/loops_simple.rs"]
#[allow(unused_variables, dead_code, non_snake_case, unused_parens, unused_mut)]
mod loops_simple_src;
#[path = "../src/fixtures/no_nested_borrows.rs"]
#[allow(unused_variables, dead_code, non_snake_case, unused_parens, unused_mut)]
mod no_nested_borrows_src;
#[path = "../src/fixtures/paper.rs"]
#[allow(unused_variables, dead_code, non_snake_case, unused_parens, unused_mut)]
mod paper_src;
#[path = "../../../tests/src/scalars.rs"]
#[allow(unused_variables, dead_code, non_snake_case, unused_parens, unused_mut)]
mod scalars_src;
#[path = "../src/fixtures/step_by.rs"]
#[allow(unused_variables, dead_code, non_snake_case, unused_parens, unused_mut)]
mod step_by_src;
#[path = "../../../tests/src/traits.rs"]
#[allow(unused_variables, dead_code, non_snake_case, unused_parens, unused_mut)]
mod traits_src;
#[path = "../../../tests/src/traits_basic.rs"]
#[allow(unused_variables, dead_code, non_snake_case, unused_parens, unused_mut)]
mod traits_basic_src;

use aeneas_cert_differential::model;
use proptest::prelude::*;

// ====================================================================
// aggregates_basic — auto-generated
// ====================================================================

proptest! {
    /// Auto-generated from `aggregates_basic::mk_tuple` (signature: (u32, u32) -> (u32, u32))
    #[test]
    fn aggregates_basic_mk_tuple_auto(a0 in any::<u32>(), a1 in any::<u32>()) {
        let lhs = aggregates_basic_src::mk_tuple(a0, a1);
        let rhs = model::aggregates_basic_mk_tuple_model(a0, a1);
        prop_assert_eq!(lhs, rhs);
    }
}

// SKIPPED aggregates_basic::mk_pair: `model::aggregates_basic_mk_pair_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// ====================================================================
// arrays — auto-generated
// ====================================================================

// SKIPPED arrays::index_array_u32: `model::arrays_index_array_u32_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED arrays::take_array: `model::arrays_take_array_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED arrays::const_array: `model::arrays_const_array_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED arrays::const_slice: `model::arrays_const_slice_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED arrays::take_all: `model::arrays_take_all_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED arrays::index_array: `model::arrays_index_array_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED arrays::index_all: `model::arrays_index_all_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED arrays::update_array: `model::arrays_update_array_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED arrays::update_all: `model::arrays_update_all_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED arrays::range_all: `model::arrays_range_all_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED arrays::non_copyable_array: `model::arrays_non_copyable_array_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED arrays::f0: `model::arrays_f0_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED arrays::f1: `model::arrays_f1_model` not in src/model.rs (run scripts/regen-diff-models.sh)

proptest! {
    /// Auto-generated from `arrays::f2` (signature: (u32) -> ())
    #[test]
    fn arrays_f2_auto(a0 in any::<u32>()) {
        let lhs = arrays_src::f2(a0);
        let rhs = model::arrays_f2_model(a0);
        prop_assert_eq!(lhs, rhs);
    }
}

// SKIPPED arrays::f3: `model::arrays_f3_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED arrays::ite: `model::arrays_ite_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// ====================================================================
// arrays_defs — auto-generated
// ====================================================================

// SKIPPED arrays_defs::index_empty_array: `model::arrays_defs_index_empty_array_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// ====================================================================
// bitwise — auto-generated
// ====================================================================

proptest! {
    /// Auto-generated from `bitwise::shift_u32` (signature: (u32) -> u32)
    #[test]
    fn bitwise_shift_u32_auto(a0 in any::<u32>()) {
        let lhs = bitwise_src::shift_u32(a0);
        let rhs = model::bitwise_shift_u32_model(a0);
        prop_assert_eq!(lhs, rhs);
    }
}

proptest! {
    /// Auto-generated from `bitwise::shift_i32` (signature: (i32) -> i32)
    #[test]
    fn bitwise_shift_i32_auto(a0 in any::<i32>()) {
        let lhs = bitwise_src::shift_i32(a0);
        let rhs = model::bitwise_shift_i32_model(a0);
        prop_assert_eq!(lhs, rhs);
    }
}

proptest! {
    /// Auto-generated from `bitwise::xor_u32` (signature: (u32, u32) -> u32)
    #[test]
    fn bitwise_xor_u32_auto(a0 in any::<u32>(), a1 in any::<u32>()) {
        let lhs = bitwise_src::xor_u32(a0, a1);
        let rhs = model::bitwise_xor_u32_model(a0, a1);
        prop_assert_eq!(lhs, rhs);
    }
}

proptest! {
    /// Auto-generated from `bitwise::or_u32` (signature: (u32, u32) -> u32)
    #[test]
    fn bitwise_or_u32_auto(a0 in any::<u32>(), a1 in any::<u32>()) {
        let lhs = bitwise_src::or_u32(a0, a1);
        let rhs = model::bitwise_or_u32_model(a0, a1);
        prop_assert_eq!(lhs, rhs);
    }
}

proptest! {
    /// Auto-generated from `bitwise::and_u32` (signature: (u32, u32) -> u32)
    #[test]
    fn bitwise_and_u32_auto(a0 in any::<u32>(), a1 in any::<u32>()) {
        let lhs = bitwise_src::and_u32(a0, a1);
        let rhs = model::bitwise_and_u32_model(a0, a1);
        prop_assert_eq!(lhs, rhs);
    }
}

// ====================================================================
// calls — auto-generated
// ====================================================================

proptest! {
    /// Auto-generated from `calls::pick` (signature: (bool, u32, u32) -> u32)
    #[test]
    fn calls_pick_auto(a0 in any::<bool>(), a1 in any::<u32>(), a2 in any::<u32>()) {
        let lhs = calls_src::pick(a0, a1, a2);
        let rhs = model::calls_pick_model(a0, a1, a2);
        prop_assert_eq!(lhs, rhs);
    }
}

// ====================================================================
// chunks_exact — auto-generated
// ====================================================================

// SKIPPED chunks_exact::test_chunks_exact_exact_fit: `model::chunks_exact_test_chunks_exact_exact_fit_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED chunks_exact::test_chunks_exact_with_remainder: `model::chunks_exact_test_chunks_exact_with_remainder_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED chunks_exact::test_chunks_exact_remainder_2: `model::chunks_exact_test_chunks_exact_remainder_2_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED chunks_exact::test_chunks_exact_size_1: `model::chunks_exact_test_chunks_exact_size_1_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED chunks_exact::test_chunks_exact_empty: `model::chunks_exact_test_chunks_exact_empty_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED chunks_exact::test_chunks_exact_chunk_larger_than_slice: `model::chunks_exact_test_chunks_exact_chunk_larger_than_slice_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED chunks_exact::test_chunks_exact_chunk_equals_slice: `model::chunks_exact_test_chunks_exact_chunk_equals_slice_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED chunks_exact::test_chunks_exact_2_odd: `model::chunks_exact_test_chunks_exact_2_odd_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED chunks_exact::test_chunks_exact_2_single_element: `model::chunks_exact_test_chunks_exact_2_single_element_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// ====================================================================
// compare_simple — auto-generated
// ====================================================================

proptest! {
    /// Auto-generated from `compare_simple::id_u32` (signature: (u32) -> u32)
    #[test]
    fn compare_simple_id_u32_auto(a0 in any::<u32>()) {
        let lhs = compare_simple_src::id_u32(a0);
        let rhs = model::compare_simple_id_u32_model(a0);
        prop_assert_eq!(lhs, rhs);
    }
}

proptest! {
    /// Auto-generated from `compare_simple::add_u32` (signature: (u32, u32) -> u32)
    #[test]
    fn compare_simple_add_u32_auto(a0 in any::<u32>(), a1 in any::<u32>()) {
        let lhs = compare_simple_src::add_u32(a0, a1);
        let rhs = model::compare_simple_add_u32_model(a0, a1);
        prop_assert_eq!(lhs, rhs);
    }
}

// ====================================================================
// constants — auto-generated
// ====================================================================

proptest! {
    /// Auto-generated from `constants::incr` (signature: (u32) -> u32)
    #[test]
    fn constants_incr_auto(a0 in any::<u32>()) {
        let lhs = constants_src::incr(a0);
        let rhs = model::constants_incr_model(a0);
        prop_assert_eq!(lhs, rhs);
    }
}

proptest! {
    /// Auto-generated from `constants::mk_pair0` (signature: (u32, u32) -> (u32, u32))
    #[test]
    fn constants_mk_pair0_auto(a0 in any::<u32>(), a1 in any::<u32>()) {
        let lhs = constants_src::mk_pair0(a0, a1);
        let rhs = model::constants_mk_pair0_model(a0, a1);
        prop_assert_eq!(lhs, rhs);
    }
}

// SKIPPED constants::unwrap_y: `model::constants_unwrap_y_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED constants::get_z1: `model::constants_get_z1_model` not in src/model.rs (run scripts/regen-diff-models.sh)

proptest! {
    /// Auto-generated from `constants::add` (signature: (i32, i32) -> i32)
    #[test]
    fn constants_add_auto(a0 in any::<i32>(), a1 in any::<i32>()) {
        let lhs = constants_src::add(a0, a1);
        let rhs = model::constants_add_model(a0, a1);
        prop_assert_eq!(lhs, rhs);
    }
}

// SKIPPED constants::get_z2: `model::constants_get_z2_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// ====================================================================
// demo — auto-generated
// ====================================================================

proptest! {
    /// Auto-generated from `demo::mul2_add1` (signature: (u32) -> u32)
    #[test]
    fn demo_mul2_add1_auto(a0 in any::<u32>()) {
        let lhs = demo_src::mul2_add1(a0);
        let rhs = model::demo_mul2_add1_model(a0);
        prop_assert_eq!(lhs, rhs);
    }
}

// SKIPPED demo::use_mul2_add1: `model::demo_use_mul2_add1_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED demo::use_incr: `model::demo_use_incr_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED demo::i32_id: `model::demo_i32_id_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// ====================================================================
// deref — auto-generated
// ====================================================================

// SKIPPED deref::test_deref_box: `model::deref_test_deref_box_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// ====================================================================
// incr_cert — auto-generated
// ====================================================================

proptest! {
    /// Auto-generated from `incr_cert::incr_local` (signature: (u32) -> u32)
    #[test]
    fn incr_cert_incr_local_auto(a0 in any::<u32>()) {
        let lhs = incr_cert_src::incr_local(a0);
        let rhs = model::incr_cert_incr_local_model(a0);
        prop_assert_eq!(lhs, rhs);
    }
}

// ====================================================================
// loops — auto-generated
// ====================================================================

// SKIPPED loops::iter: `model::loops_iter_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED loops::sum: `model::loops_sum_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED loops::sum_with_mut_borrows: `model::loops_sum_with_mut_borrows_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED loops::sum_with_shared_borrows: `model::loops_sum_with_shared_borrows_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// ====================================================================
// loops_simple — auto-generated
// ====================================================================

// SKIPPED loops_simple::count_to: `model::loops_simple_count_to_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// ====================================================================
// no_nested_borrows — auto-generated
// ====================================================================

proptest! {
    /// Auto-generated from `no_nested_borrows::cast_u32_to_i32` (signature: (u32) -> i32)
    #[test]
    fn no_nested_borrows_cast_u32_to_i32_auto(a0 in any::<u32>()) {
        let lhs = no_nested_borrows_src::cast_u32_to_i32(a0);
        let rhs = model::no_nested_borrows_cast_u32_to_i32_model(a0);
        prop_assert_eq!(lhs, rhs);
    }
}

proptest! {
    /// Auto-generated from `no_nested_borrows::cast_bool_to_i32` (signature: (bool) -> i32)
    #[test]
    fn no_nested_borrows_cast_bool_to_i32_auto(a0 in any::<bool>()) {
        let lhs = no_nested_borrows_src::cast_bool_to_i32(a0);
        let rhs = model::no_nested_borrows_cast_bool_to_i32_model(a0);
        prop_assert_eq!(lhs, rhs);
    }
}

proptest! {
    /// Auto-generated from `no_nested_borrows::cast_bool_to_bool` (signature: (bool) -> bool)
    #[test]
    fn no_nested_borrows_cast_bool_to_bool_auto(a0 in any::<bool>()) {
        let lhs = no_nested_borrows_src::cast_bool_to_bool(a0);
        let rhs = model::no_nested_borrows_cast_bool_to_bool_model(a0);
        prop_assert_eq!(lhs, rhs);
    }
}

/// Auto-generated from `no_nested_borrows::test2` (signature: () -> ())
#[test]
fn no_nested_borrows_test2_auto() {
    let lhs = no_nested_borrows_src::test2();
    let rhs = model::no_nested_borrows_test2_model();
    assert_eq!(lhs, rhs);
}

proptest! {
    /// Auto-generated from `no_nested_borrows::get_max` (signature: (u32, u32) -> u32)
    #[test]
    fn no_nested_borrows_get_max_auto(a0 in any::<u32>(), a1 in any::<u32>()) {
        let lhs = no_nested_borrows_src::get_max(a0, a1);
        let rhs = model::no_nested_borrows_get_max_model(a0, a1);
        prop_assert_eq!(lhs, rhs);
    }
}

// SKIPPED no_nested_borrows::test3: `model::no_nested_borrows_test3_model` not in src/model.rs (run scripts/regen-diff-models.sh)

/// Auto-generated from `no_nested_borrows::test_neg1` (signature: () -> ())
#[test]
fn no_nested_borrows_test_neg1_auto() {
    let lhs = no_nested_borrows_src::test_neg1();
    let rhs = model::no_nested_borrows_test_neg1_model();
    assert_eq!(lhs, rhs);
}

/// Auto-generated from `no_nested_borrows::refs_test1` (signature: () -> ())
#[test]
fn no_nested_borrows_refs_test1_auto() {
    let lhs = no_nested_borrows_src::refs_test1();
    let rhs = model::no_nested_borrows_refs_test1_model();
    assert_eq!(lhs, rhs);
}

/// Auto-generated from `no_nested_borrows::refs_test2` (signature: () -> ())
#[test]
fn no_nested_borrows_refs_test2_auto() {
    let lhs = no_nested_borrows_src::refs_test2();
    let rhs = model::no_nested_borrows_refs_test2_model();
    assert_eq!(lhs, rhs);
}

// SKIPPED no_nested_borrows::test_list1: `model::no_nested_borrows_test_list1_model` not in src/model.rs (run scripts/regen-diff-models.sh)

proptest! {
    /// Auto-generated from `no_nested_borrows::copy_int` (signature: (i32) -> i32)
    #[test]
    fn no_nested_borrows_copy_int_auto(a0 in any::<i32>()) {
        let lhs = no_nested_borrows_src::copy_int(a0);
        let rhs = model::no_nested_borrows_copy_int_model(a0);
        prop_assert_eq!(lhs, rhs);
    }
}

// SKIPPED no_nested_borrows::test_unreachable: `test_unreachable` not defined in the resolved source file

// SKIPPED no_nested_borrows::test_panic: `test_panic` not defined in the resolved source file

// SKIPPED no_nested_borrows::test_panic_msg: `test_panic_msg` not defined in the resolved source file

// SKIPPED no_nested_borrows::test_copy_int: `model::no_nested_borrows_test_copy_int_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED no_nested_borrows::test_is_cons: `model::no_nested_borrows_test_is_cons_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED no_nested_borrows::test_split_list: `model::no_nested_borrows_test_split_list_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED no_nested_borrows::choose_test: `model::no_nested_borrows_choose_test_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED no_nested_borrows::test_list_functions: `model::no_nested_borrows_test_list_functions_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED no_nested_borrows::test_constants: `model::no_nested_borrows_test_constants_model` not in src/model.rs (run scripts/regen-diff-models.sh)

/// Auto-generated from `no_nested_borrows::test_weird_borrows1` (signature: () -> ())
#[test]
fn no_nested_borrows_test_weird_borrows1_auto() {
    let lhs = no_nested_borrows_src::test_weird_borrows1();
    let rhs = model::no_nested_borrows_test_weird_borrows1_model();
    assert_eq!(lhs, rhs);
}

proptest! {
    /// Auto-generated from `no_nested_borrows::test_shared_borrow_bool1` (signature: (bool) -> u32)
    #[test]
    fn no_nested_borrows_test_shared_borrow_bool1_auto(a0 in any::<bool>()) {
        let lhs = no_nested_borrows_src::test_shared_borrow_bool1(a0);
        let rhs = model::no_nested_borrows_test_shared_borrow_bool1_model(a0);
        prop_assert_eq!(lhs, rhs);
    }
}

/// Auto-generated from `no_nested_borrows::test_shared_borrow_bool2` (signature: () -> u32)
#[test]
fn no_nested_borrows_test_shared_borrow_bool2_auto() {
    let lhs = no_nested_borrows_src::test_shared_borrow_bool2();
    let rhs = model::no_nested_borrows_test_shared_borrow_bool2_model();
    assert_eq!(lhs, rhs);
}

/// Auto-generated from `no_nested_borrows::test_shared_borrow_enum2` (signature: () -> u32)
#[test]
fn no_nested_borrows_test_shared_borrow_enum2_auto() {
    let lhs = no_nested_borrows_src::test_shared_borrow_enum2();
    let rhs = model::no_nested_borrows_test_shared_borrow_enum2_model();
    assert_eq!(lhs, rhs);
}

// SKIPPED no_nested_borrows::call_incr: `model::no_nested_borrows_call_incr_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED no_nested_borrows::not_bool: `model::no_nested_borrows_not_bool_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED no_nested_borrows::not_u32: `model::no_nested_borrows_not_u32_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED no_nested_borrows::not_i32: `model::no_nested_borrows_not_i32_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// ====================================================================
// paper — auto-generated
// ====================================================================

// SKIPPED paper::test_incr: `model::paper_test_incr_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED paper::test_choose: `model::paper_test_choose_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED paper::test_nth: `model::paper_test_nth_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED paper::call_choose: `model::paper_call_choose_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// ====================================================================
// scalars — auto-generated
// ====================================================================

/// Auto-generated from `scalars::u32_use_bits` (signature: () -> u32)
#[test]
fn scalars_u32_use_bits_auto() {
    let lhs = scalars_src::u32_use_bits();
    let rhs = model::scalars_u32_use_bits_model();
    assert_eq!(lhs, rhs);
}

/// Auto-generated from `scalars::i32_use_bits` (signature: () -> u32)
#[test]
fn scalars_i32_use_bits_auto() {
    let lhs = scalars_src::i32_use_bits();
    let rhs = model::scalars_i32_use_bits_model();
    assert_eq!(lhs, rhs);
}

// ====================================================================
// step_by — auto-generated
// ====================================================================

// SKIPPED step_by::test_step_by_1: `model::step_by_test_step_by_1_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED step_by::test_step_by_2: `model::step_by_test_step_by_2_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED step_by::test_step_by_3: `model::step_by_test_step_by_3_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED step_by::test_step_by_larger_than_len: `model::step_by_test_step_by_larger_than_len_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED step_by::test_step_by_empty: `model::step_by_test_step_by_empty_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED step_by::test_step_by_single: `model::step_by_test_step_by_single_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED step_by::test_step_by_single_step_2: `model::step_by_test_step_by_single_step_2_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED step_by::test_step_by_eq_len: `model::step_by_test_step_by_eq_len_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED step_by::test_step_by_len_minus_1: `model::step_by_test_step_by_len_minus_1_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED step_by::test_step_by_two_elements: `model::step_by_test_step_by_two_elements_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED step_by::test_step_by_4_on_longer: `model::step_by_test_step_by_4_on_longer_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// ====================================================================
// traits — auto-generated
// ====================================================================

// SKIPPED traits::test_bool_trait_bool: `model::traits_test_bool_trait_bool_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED traits::h0: `model::traits_h0_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// ====================================================================
// traits_basic — auto-generated
// ====================================================================

// SKIPPED traits_basic::use_numeric: `model::traits_basic_use_numeric_model` not in src/model.rs (run scripts/regen-diff-models.sh)

