-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [external_names]
import Aeneas
import ExternalNamesModel
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace external_names

/-- [external_names::use_is_mult]:
    Source: 'tests/src/external-names.rs', lines 11:0-13:1 -/
def use_is_mult (x : Std.U32) : Result Bool := do
  ExternalNamesModel.isMult x 3#u32

end external_names
