-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [huge_discriminant]
import Aeneas
open Aeneas Aeneas.Std RustM ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace huge_discriminant

/-- [huge_discriminant::HugeDiscriminant]
    Source: 'tests/src/huge_discriminant.rs', lines 5:0-8:1
    Visibility: public -/
@[discriminant u128 [0,340282366920938463463374607431768211455]]
inductive HugeDiscriminant where
| Small : HugeDiscriminant
| Huge : HugeDiscriminant

end huge_discriminant
