-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [opaque_trait_impl]
import Aeneas
open Aeneas Aeneas.Std RustM ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace opaque_trait_impl

/-- Trait declaration: [opaque_trait_impl::Tr]
    Source: 'tests/src/opaque_trait_impl.rs', lines 6:0-8:1
    Visibility: public -/
structure Tr (Self : Type) where
  m : Self → RustM Std.U32

/-- [opaque_trait_impl::S]
    Source: 'tests/src/opaque_trait_impl.rs', lines 10:0-10:13
    Visibility: public -/
@[reducible]
def S := Unit

/-- Trait implementation: [opaque_trait_impl::{impl opaque_trait_impl::Tr for opaque_trait_impl::S}]
    Source: 'tests/src/opaque_trait_impl.rs', lines 12:0-16:1 -/
axiom S.Insts.Opaque_trait_implTr : Tr S

end opaque_trait_impl
