-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [type_erasure]
import Aeneas
open Aeneas Aeneas.Std RustM ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace type_erasure

/-- [type_erasure::Handler]
    Source: 'tests/src/type_erasure.rs', lines 5:0-8:1
    Visibility: public -/
structure Handler where
  cb : Erased
  n : Std.U32

/-- [type_erasure::get_n]:
    Source: 'tests/src/type_erasure.rs', lines 10:0-12:1
    Visibility: public -/
def get_n (h : Handler) : RustM Std.U32 := do
  ok h.n

end type_erasure
