// AUTO-GENERATED by `meta-harness --generate-tests`. DO NOT EDIT.
// Each `proptest!` block was synthesised from a cert.json fn whose
// signature is simple enough to drive `any::<...>()` directly
// (all-scalar inputs + scalar / tuple-of-scalars output, no
// generics, no refs).
//
// To regenerate:
//   meta-harness --generate-tests \
//     --sweep tests/llbc \
//     --tests-src-dir tests/src \
//     --tests-out tests/lean-checker/differential/tests/diff_auto.rs

#![allow(unused_variables, dead_code, non_snake_case, unused_parens, unused_mut)]

#[path = "../../../src/aggregates_basic.rs"]
#[allow(unused_variables, dead_code, non_snake_case, unused_parens, unused_mut)]
mod aggregates_basic_src;
#[path = "../../../src/arrays.rs"]
#[allow(unused_variables, dead_code, non_snake_case, unused_parens, unused_mut)]
mod arrays_src;
#[path = "../../../src/arrays_defs.rs"]
#[allow(unused_variables, dead_code, non_snake_case, unused_parens, unused_mut)]
mod arrays_defs_src;
#[path = "../../../src/bitwise.rs"]
#[allow(unused_variables, dead_code, non_snake_case, unused_parens, unused_mut)]
mod bitwise_src;
#[path = "../../../src/calls.rs"]
#[allow(unused_variables, dead_code, non_snake_case, unused_parens, unused_mut)]
mod calls_src;
#[path = "../../../src/compare_simple.rs"]
#[allow(unused_variables, dead_code, non_snake_case, unused_parens, unused_mut)]
mod compare_simple_src;
#[path = "../../../src/constants.rs"]
#[allow(unused_variables, dead_code, non_snake_case, unused_parens, unused_mut)]
mod constants_src;
#[path = "../../../src/demo.rs"]
#[allow(unused_variables, dead_code, non_snake_case, unused_parens, unused_mut)]
mod demo_src;
#[path = "../../../src/deref.rs"]
#[allow(unused_variables, dead_code, non_snake_case, unused_parens, unused_mut)]
mod deref_src;
#[path = "../../../src/incr_cert.rs"]
#[allow(unused_variables, dead_code, non_snake_case, unused_parens, unused_mut)]
mod incr_cert_src;
#[path = "../../../src/loops.rs"]
#[allow(unused_variables, dead_code, non_snake_case, unused_parens, unused_mut)]
mod loops_src;
#[path = "../../../src/loops_simple.rs"]
#[allow(unused_variables, dead_code, non_snake_case, unused_parens, unused_mut)]
mod loops_simple_src;
#[path = "../../../src/scalars.rs"]
#[allow(unused_variables, dead_code, non_snake_case, unused_parens, unused_mut)]
mod scalars_src;
#[path = "../../../src/traits.rs"]
#[allow(unused_variables, dead_code, non_snake_case, unused_parens, unused_mut)]
mod traits_src;

use aeneas_cert_differential::model;
use proptest::prelude::*;

// ====================================================================
// aggregates_basic — auto-generated
// ====================================================================

// SKIPPED aggregates_basic::mk_tuple: `model::aggregates_basic_mk_tuple_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// ====================================================================
// arrays — auto-generated
// ====================================================================

// SKIPPED arrays::const_slice: `model::arrays_const_slice_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED arrays::take_all: `model::arrays_take_all_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED arrays::index_all: `model::arrays_index_all_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED arrays::update_all: `model::arrays_update_all_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED arrays::range_all: `model::arrays_range_all_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED arrays::non_copyable_array: `model::arrays_non_copyable_array_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED arrays::f0: `model::arrays_f0_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED arrays::f1: `model::arrays_f1_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED arrays::f2: `model::arrays_f2_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED arrays::f3: `model::arrays_f3_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED arrays::ite: `model::arrays_ite_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED arrays::SZ: `model::arrays_SZ_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// ====================================================================
// arrays_defs — auto-generated
// ====================================================================

// SKIPPED arrays_defs::index_empty_array: `model::arrays_defs_index_empty_array_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// ====================================================================
// bitwise — auto-generated
// ====================================================================

proptest! {
    /// Auto-generated from `bitwise::shift_u32` (signature: (u32) -> u32)
    #[test]
    fn bitwise_shift_u32_auto(a0 in any::<u32>()) {
        let lhs = bitwise_src::shift_u32(a0);
        let rhs = model::bitwise_shift_u32_model(a0);
        prop_assert_eq!(lhs, rhs);
    }
}

proptest! {
    /// Auto-generated from `bitwise::shift_i32` (signature: (i32) -> i32)
    #[test]
    fn bitwise_shift_i32_auto(a0 in any::<i32>()) {
        let lhs = bitwise_src::shift_i32(a0);
        let rhs = model::bitwise_shift_i32_model(a0);
        prop_assert_eq!(lhs, rhs);
    }
}

proptest! {
    /// Auto-generated from `bitwise::xor_u32` (signature: (u32, u32) -> u32)
    #[test]
    fn bitwise_xor_u32_auto(a0 in any::<u32>(), a1 in any::<u32>()) {
        let lhs = bitwise_src::xor_u32(a0, a1);
        let rhs = model::bitwise_xor_u32_model(a0, a1);
        prop_assert_eq!(lhs, rhs);
    }
}

proptest! {
    /// Auto-generated from `bitwise::or_u32` (signature: (u32, u32) -> u32)
    #[test]
    fn bitwise_or_u32_auto(a0 in any::<u32>(), a1 in any::<u32>()) {
        let lhs = bitwise_src::or_u32(a0, a1);
        let rhs = model::bitwise_or_u32_model(a0, a1);
        prop_assert_eq!(lhs, rhs);
    }
}

proptest! {
    /// Auto-generated from `bitwise::and_u32` (signature: (u32, u32) -> u32)
    #[test]
    fn bitwise_and_u32_auto(a0 in any::<u32>(), a1 in any::<u32>()) {
        let lhs = bitwise_src::and_u32(a0, a1);
        let rhs = model::bitwise_and_u32_model(a0, a1);
        prop_assert_eq!(lhs, rhs);
    }
}

// ====================================================================
// calls — auto-generated
// ====================================================================

proptest! {
    /// Auto-generated from `calls::pick` (signature: (bool, u32, u32) -> u32)
    #[test]
    fn calls_pick_auto(a0 in any::<bool>(), a1 in any::<u32>(), a2 in any::<u32>()) {
        let lhs = calls_src::pick(a0, a1, a2);
        let rhs = model::calls_pick_model(a0, a1, a2);
        prop_assert_eq!(lhs, rhs);
    }
}

// ====================================================================
// compare_simple — auto-generated
// ====================================================================

proptest! {
    /// Auto-generated from `compare_simple::id_u32` (signature: (u32) -> u32)
    #[test]
    fn compare_simple_id_u32_auto(a0 in any::<u32>()) {
        let lhs = compare_simple_src::id_u32(a0);
        let rhs = model::compare_simple_id_u32_model(a0);
        prop_assert_eq!(lhs, rhs);
    }
}

proptest! {
    /// Auto-generated from `compare_simple::add_u32` (signature: (u32, u32) -> u32)
    #[test]
    fn compare_simple_add_u32_auto(a0 in any::<u32>(), a1 in any::<u32>()) {
        let lhs = compare_simple_src::add_u32(a0, a1);
        let rhs = model::compare_simple_add_u32_model(a0, a1);
        prop_assert_eq!(lhs, rhs);
    }
}

// ====================================================================
// constants — auto-generated
// ====================================================================

proptest! {
    /// Auto-generated from `constants::incr` (signature: (u32) -> u32)
    #[test]
    fn constants_incr_auto(a0 in any::<u32>()) {
        let lhs = constants_src::incr(a0);
        let rhs = model::constants_incr_model(a0);
        prop_assert_eq!(lhs, rhs);
    }
}

proptest! {
    /// Auto-generated from `constants::mk_pair0` (signature: (u32, u32) -> (u32, u32))
    #[test]
    fn constants_mk_pair0_auto(a0 in any::<u32>(), a1 in any::<u32>()) {
        let lhs = constants_src::mk_pair0(a0, a1);
        let rhs = model::constants_mk_pair0_model(a0, a1);
        prop_assert_eq!(lhs, rhs);
    }
}

// SKIPPED constants::unwrap_y: `model::constants_unwrap_y_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED constants::get_z1: `model::constants_get_z1_model` not in src/model.rs (run scripts/regen-diff-models.sh)

proptest! {
    /// Auto-generated from `constants::add` (signature: (i32, i32) -> i32)
    #[test]
    fn constants_add_auto(a0 in any::<i32>(), a1 in any::<i32>()) {
        let lhs = constants_src::add(a0, a1);
        let rhs = model::constants_add_model(a0, a1);
        prop_assert_eq!(lhs, rhs);
    }
}

// SKIPPED constants::get_z2: `model::constants_get_z2_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED constants::X0: `model::constants_X0_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED constants::X1: `model::constants_X1_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED constants::X2: `model::constants_X2_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED constants::X3: `model::constants_X3_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED constants::P0: `model::constants_P0_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED constants::P2: `model::constants_P2_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED constants::YVAL: `model::constants_YVAL_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED constants::Q1: `model::constants_Q1_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED constants::Q2: `model::constants_Q2_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED constants::Q3: `model::constants_Q3_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED constants::S1: `model::constants_S1_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED constants::S2: `model::constants_S2_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// ====================================================================
// demo — auto-generated
// ====================================================================

proptest! {
    /// Auto-generated from `demo::mul2_add1` (signature: (u32) -> u32)
    #[test]
    fn demo_mul2_add1_auto(a0 in any::<u32>()) {
        let lhs = demo_src::mul2_add1(a0);
        let rhs = model::demo_mul2_add1_model(a0);
        prop_assert_eq!(lhs, rhs);
    }
}

// SKIPPED demo::use_mul2_add1: `model::demo_use_mul2_add1_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED demo::use_incr: `model::demo_use_incr_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED demo::i32_id: `model::demo_i32_id_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// ====================================================================
// deref — auto-generated
// ====================================================================

// SKIPPED deref::test_deref_box: `model::deref_test_deref_box_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// ====================================================================
// incr_cert — auto-generated
// ====================================================================

// SKIPPED incr_cert::incr_local: `model::incr_cert_incr_local_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// ====================================================================
// loops — auto-generated
// ====================================================================

// SKIPPED loops::iter: `model::loops_iter_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED loops::sum: `model::loops_sum_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED loops::sum_with_mut_borrows: `model::loops_sum_with_mut_borrows_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED loops::sum_with_shared_borrows: `model::loops_sum_with_shared_borrows_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// ====================================================================
// loops_simple — auto-generated
// ====================================================================

// SKIPPED loops_simple::count_to: `model::loops_simple_count_to_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// ====================================================================
// scalars — auto-generated
// ====================================================================

// SKIPPED scalars::u32_use_bits: `model::scalars_u32_use_bits_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED scalars::i32_use_bits: `model::scalars_i32_use_bits_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// ====================================================================
// traits — auto-generated
// ====================================================================

// SKIPPED traits::test_bool_trait_bool: `model::traits_test_bool_trait_bool_model` not in src/model.rs (run scripts/regen-diff-models.sh)

// SKIPPED traits::h0: `model::traits_h0_model` not in src/model.rs (run scripts/regen-diff-models.sh)

