//! Phase-2 semantic-differential oracle (O4): integration glue.
//!
//! Wires the *validated* `fuzz/semdiff/` pipeline (see `RECIPE.md`) into the
//! harness. For a crate of closed deterministic `test_*` functions it:
//!   1. runs the crate natively for ground truth
//!      (`native_run.sh`, `-C overflow-checks=on`, panics via `catch_unwind`),
//!   2. translates it with the (fork) aeneas to Lean, using the target config's
//!      charon + aeneas commands **on the raw source** (NOT the pack path — the
//!      test names must survive so the two sides stay in lock-step),
//!   3. evaluates + compares in Lean (`check.sh` → `#eval` classifier → verdicts),
//!   4. parses the per-test verdicts.
//!
//! A `MISMATCH` (native and Lean disagree OK-vs-FAIL) is a candidate
//! miscompilation — a HIGH-VALUE finding. Each mismatch gets a self-contained
//! repro dir under `fuzz/findings/` and is flagged loudly.
//!
//! This oracle is FORK-ONLY and slow (a fixed ~2 s of Aeneas import loading per
//! crate + one-time lake warm-up); it is gated behind the `semdiff` subcommand,
//! never run in the default campaign. It calls the `fuzz/semdiff/*.sh` scripts
//! as-is and reuses the prebuilt `lean-driver/.lake`.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::time::Duration;

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};

use crate::config::{substitute, TargetConfig};
use crate::pipeline::run_cmd;

/// Options controlling one semdiff run.
pub struct SemdiffOpts {
    /// The `fuzz/semdiff/` directory holding native_run.sh / check.sh.
    pub semdiff_dir: PathBuf,
    /// Scratch directory for this run (native.json, llbc, lean-out, verdicts).
    pub work_dir: PathBuf,
    /// Where MISMATCH repro dirs are written (`fuzz/findings/`).
    pub findings_dir: PathBuf,
    /// `--strict`: also flag error-kind disagreements (`MISMATCH_KIND`).
    pub strict: bool,
    /// Overall wall-clock cap (seconds) for each external stage.
    pub stage_timeout_secs: u64,
}

impl SemdiffOpts {
    /// The prebuilt lake driver project (default: `<semdiff_dir>/lean-driver`).
    pub fn driver_dir(&self) -> PathBuf {
        self.semdiff_dir.join("lean-driver")
    }
}

/// One row of the `check.py` verdict report.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VerdictRow {
    pub name: String,
    #[serde(default)]
    pub native: Option<serde_json::Value>,
    #[serde(default)]
    pub lean: Option<serde_json::Value>,
    pub verdict: String,
}

impl VerdictRow {
    /// Human summary of the native side.
    pub fn native_str(&self) -> String {
        self.native
            .as_ref()
            .map(|v| v.to_string())
            .unwrap_or_else(|| "<none>".into())
    }
    /// Human summary of the Lean side.
    pub fn lean_str(&self) -> String {
        match &self.lean {
            Some(serde_json::Value::String(s)) => s.clone(),
            Some(v) => v.to_string(),
            None => "<none>".into(),
        }
    }
    /// A MISMATCH is the bug signal (native/Lean disagree OK-vs-FAIL). In strict
    /// mode a MISMATCH_KIND (both fail, different variant) also counts.
    pub fn is_mismatch(&self, strict: bool) -> bool {
        self.verdict == "MISMATCH" || (strict && self.verdict == "MISMATCH_KIND")
    }
}

/// The aggregate result of one semdiff run.
pub struct SemdiffReport {
    pub counts: BTreeMap<String, usize>,
    pub rows: Vec<VerdictRow>,
    pub mismatches: Vec<VerdictRow>,
    pub timings_ms: BTreeMap<String, u128>,
    /// Repro dirs emitted for mismatches (parallel to `mismatches`).
    pub repro_dirs: Vec<PathBuf>,
    /// True if every external stage ran (native/charon/aeneas/check) OK enough to
    /// produce a verdict report. When false, `note` explains what stalled.
    pub complete: bool,
    pub note: String,
}

impl SemdiffReport {
    pub fn count(&self, key: &str) -> usize {
        self.counts.get(key).copied().unwrap_or(0)
    }
    /// A one-line summary of the verdict tally.
    pub fn summary(&self) -> String {
        self.counts
            .iter()
            .map(|(k, v)| format!("{k}={v}"))
            .collect::<Vec<_>>()
            .join(" ")
    }
}

/// Parse a `check.py` verdict JSON array into rows.
pub fn parse_verdicts(json: &str) -> Result<Vec<VerdictRow>> {
    let rows: Vec<VerdictRow> =
        serde_json::from_str(json).context("parsing semdiff verdict JSON")?;
    Ok(rows)
}

/// Tally verdict labels.
pub fn tally(rows: &[VerdictRow]) -> BTreeMap<String, usize> {
    let mut m = BTreeMap::new();
    for r in rows {
        *m.entry(r.verdict.clone()).or_insert(0) += 1;
    }
    m
}

/// Run the full semantic differential on one closed test crate.
///
/// `src` must contain niladic `pub fn test_*()` functions (generated by
/// [`crate::gen::gen_closed_crate`] or hand-written). `cfg` supplies the
/// (fork) charon + aeneas commands and env.
pub fn run_crate(src: &Path, cfg: &TargetConfig, opts: &SemdiffOpts) -> Result<SemdiffReport> {
    // Absolutize every directory: child processes run with `current_dir` set to
    // the work dir, so any relative script/output path would resolve against
    // *that* and break.
    std::fs::create_dir_all(&opts.work_dir)
        .with_context(|| format!("create semdiff work dir {}", opts.work_dir.display()))?;
    std::fs::create_dir_all(&opts.findings_dir)
        .with_context(|| format!("create findings dir {}", opts.findings_dir.display()))?;
    let work_dir = std::fs::canonicalize(&opts.work_dir)?;
    let findings_dir = std::fs::canonicalize(&opts.findings_dir)?;
    let semdiff_dir = std::fs::canonicalize(&opts.semdiff_dir)
        .with_context(|| format!("canonicalize semdiff dir {}", opts.semdiff_dir.display()))?;
    let driver = semdiff_dir.join("lean-driver");
    let src_abs = std::fs::canonicalize(src)
        .with_context(|| format!("canonicalize {}", src.display()))?;
    let source_text = std::fs::read_to_string(&src_abs)?;

    let mut timings = BTreeMap::new();
    let mut note = String::new();
    let timeout = Duration::from_secs(opts.stage_timeout_secs);

    // --- 1. native ground truth (overflow-checks ON is mandatory) ---
    let native_json = work_dir.join("native.json");
    let native_sh = semdiff_dir.join("native_run.sh");
    anyhow::ensure!(
        native_sh.exists(),
        "native_run.sh not found at {}",
        native_sh.display()
    );
    let native_argv = vec![
        "bash".to_string(),
        native_sh.to_string_lossy().into_owned(),
        src_abs.to_string_lossy().into_owned(),
        native_json.to_string_lossy().into_owned(),
    ];
    let native_out = run_cmd(&native_argv, &cfg.extra_env, &work_dir, timeout, "native")?;
    timings.insert("native_ms".to_string(), native_out.duration_ms);
    if native_out.timed_out {
        return Ok(incomplete(
            timings,
            "native_run.sh timed out (non-terminating test?)".into(),
        ));
    }
    if native_out.exit_code != Some(0) || !native_json.exists() {
        return Ok(incomplete(
            timings,
            format!(
                "native_run.sh failed (exit {:?}): {}",
                native_out.exit_code, native_out.stderr_tail
            ),
        ));
    }

    // --- 2. translate: charon (raw source) then aeneas (names preserved) ---
    let llbc = work_dir.join("crate.llbc");
    let charon_argv = substitute(
        &cfg.charon_cmd,
        &[
            ("input", &src_abs.to_string_lossy()),
            ("output", &llbc.to_string_lossy()),
        ],
    );
    let charon_out = run_cmd(&charon_argv, &cfg.extra_env, &work_dir, timeout, "charon")?;
    timings.insert("charon_ms".to_string(), charon_out.duration_ms);
    if charon_out.exit_code != Some(0) || !llbc.exists() {
        return Ok(incomplete(
            timings,
            format!(
                "charon failed (exit {:?}): {}",
                charon_out.exit_code, charon_out.stderr_tail
            ),
        ));
    }

    let dest = work_dir.join("lean-out");
    let _ = std::fs::remove_dir_all(&dest);
    // Drop `-abort-on-error` for the semdiff translation: we WANT partial
    // emission. A single test that crashes aeneas (e.g. an N1 assert
    // double-eval) would otherwise abort the whole batch and yield no Lean at
    // all; without it, aeneas skips the offending function and still emits a
    // namespaced Crate.lean for the rest (the crasher becomes MISSING_LEAN,
    // harmless). Crash *findings* are the open pipeline's job, not the oracle's.
    let translate_flags: Vec<String> = cfg
        .translate_flags
        .iter()
        .filter(|f| f.as_str() != "-abort-on-error")
        .cloned()
        .collect();
    let flags = substitute(
        &translate_flags,
        &[
            ("llbc", &llbc.to_string_lossy()),
            ("dest", &dest.to_string_lossy()),
        ],
    );
    let mut aeneas_argv = cfg.aeneas_cmd.clone();
    aeneas_argv.extend(flags);
    let aeneas_out = run_cmd(&aeneas_argv, &cfg.extra_env, &work_dir, timeout, "aeneas")?;
    timings.insert("aeneas_ms".to_string(), aeneas_out.duration_ms);
    // aeneas may exit nonzero on a translation gate; if it still produced a
    // namespaced .lean we proceed (check.sh evaluates whatever it can).
    let have_lean = dest.exists()
        && std::fs::read_dir(&dest)
            .map(|rd| {
                rd.flatten().any(|e| {
                    e.path().extension().map(|x| x == "lean").unwrap_or(false)
                        && std::fs::read_to_string(e.path())
                            .map(|t| t.contains("namespace "))
                            .unwrap_or(false)
                })
            })
            .unwrap_or(false);
    if !have_lean {
        return Ok(incomplete(
            timings,
            format!(
                "aeneas produced no namespaced .lean (exit {:?}): {}",
                aeneas_out.exit_code, aeneas_out.stderr_tail
            ),
        ));
    }

    // --- 3. Lean eval + compare (check.sh: gen_driver -> lake env lean -> check.py) ---
    let verdict_json = work_dir.join("verdicts.json");
    let check_sh = semdiff_dir.join("check.sh");
    anyhow::ensure!(
        check_sh.exists(),
        "check.sh not found at {}",
        check_sh.display()
    );
    if !driver.join(".lake").exists() {
        note.push_str(&format!(
            "warning: prebuilt lake driver .lake missing at {} (check.sh may need a warm-up); ",
            driver.display()
        ));
    }
    let mut check_argv = vec![
        "bash".to_string(),
        check_sh.to_string_lossy().into_owned(),
        "--dest".to_string(),
        dest.to_string_lossy().into_owned(),
        "--native".to_string(),
        native_json.to_string_lossy().into_owned(),
        "--out".to_string(),
        verdict_json.to_string_lossy().into_owned(),
        "--driver".to_string(),
        driver.to_string_lossy().into_owned(),
    ];
    if opts.strict {
        check_argv.push("--strict".to_string());
    }
    // Lean can hang on a divergent #eval; give check.sh generous headroom above
    // its own internal SEMDIFF_LEAN_TIMEOUT (default 120s).
    let check_timeout = Duration::from_secs(opts.stage_timeout_secs.max(300));
    let check_out = run_cmd(&check_argv, &cfg.extra_env, &work_dir, check_timeout, "check")?;
    timings.insert("lean_ms".to_string(), check_out.duration_ms);
    if check_out.timed_out {
        return Ok(incomplete(
            timings,
            "check.sh (lean eval) timed out; a divergent #eval may be poisoning the batch".into(),
        ));
    }
    if !verdict_json.exists() {
        return Ok(incomplete(
            timings,
            format!(
                "check.sh produced no verdict file (exit {:?}): {}",
                check_out.exit_code, check_out.stderr_tail
            ),
        ));
    }

    // --- 4. parse verdicts + emit repro dirs for mismatches ---
    let vtext = std::fs::read_to_string(&verdict_json)?;
    let rows = parse_verdicts(&vtext)?;
    let counts = tally(&rows);
    let mismatches: Vec<VerdictRow> =
        rows.iter().filter(|r| r.is_mismatch(opts.strict)).cloned().collect();

    let mut repro_dirs = Vec::new();
    for m in &mismatches {
        match emit_mismatch_repro(
            &findings_dir,
            m,
            &source_text,
            &cfg.name,
            &vtext,
        ) {
            Ok(dir) => repro_dirs.push(dir),
            Err(e) => note.push_str(&format!("repro emit failed for {}: {e}; ", m.name)),
        }
    }

    Ok(SemdiffReport {
        counts,
        rows,
        mismatches,
        timings_ms: timings,
        repro_dirs,
        complete: true,
        note,
    })
}

fn incomplete(timings: BTreeMap<String, u128>, note: String) -> SemdiffReport {
    SemdiffReport {
        counts: BTreeMap::new(),
        rows: Vec::new(),
        mismatches: Vec::new(),
        timings_ms: timings,
        repro_dirs: Vec::new(),
        complete: false,
        note,
    }
}

/// Extract the source of a single niladic `pub fn NAME()` (brace-matched). Safe
/// for generated code, which contains no braces inside string/char literals.
pub fn extract_fn_source(src: &str, name: &str) -> Option<String> {
    let needle = format!("pub fn {name}(");
    let start = src.find(&needle)?;
    let brace_rel = src[start..].find('{')?;
    let brace = start + brace_rel;
    let mut depth = 0i32;
    for (i, c) in src[brace..].char_indices() {
        match c {
            '{' => depth += 1,
            '}' => {
                depth -= 1;
                if depth == 0 {
                    return Some(src[start..brace + i + 1].to_string());
                }
            }
            _ => {}
        }
    }
    None
}

/// Emit a self-contained repro dir for a semdiff mismatch under `findings_dir`.
/// Contains: the full crate (`repro.rs`), the isolated test fn (`test.rs`),
/// the native + Lean results, and `notes.md` with reproduction instructions.
pub fn emit_mismatch_repro(
    findings_dir: &Path,
    row: &VerdictRow,
    crate_source: &str,
    target_name: &str,
    full_verdict_json: &str,
) -> Result<PathBuf> {
    let slug = uniquify(findings_dir, &format!("semdiff-{}-{}", row.verdict.to_ascii_lowercase(), sanitize(&row.name)));
    let dir = findings_dir.join(&slug);
    std::fs::create_dir_all(&dir)?;

    std::fs::write(dir.join("repro.rs"), crate_source)?;
    if let Some(fn_src) = extract_fn_source(crate_source, &row.name) {
        std::fs::write(dir.join("test.rs"), fn_src)?;
    }
    let native_pretty = row
        .native
        .as_ref()
        .and_then(|v| serde_json::to_string_pretty(v).ok())
        .unwrap_or_else(|| "null".into());
    std::fs::write(dir.join("native.json"), native_pretty)?;
    std::fs::write(dir.join("lean.txt"), row.lean_str())?;
    std::fs::write(dir.join("verdicts.json"), full_verdict_json)?;

    let notes = format!(
        "# SEMDIFF {verdict}: `{name}` (target `{target}`)\n\n\
         **Candidate miscompilation** — native Rust execution and Lean evaluation of the\n\
         Aeneas translation disagree.\n\n\
         - test: `{name}`\n\
         - verdict: `{verdict}`\n\
         - native (rustc `-C overflow-checks=on`, catch_unwind): `{native}`\n\
         - lean (`#eval` of the Aeneas translation): `{lean}`\n\n\
         ## Reproduce\n\n\
         ```sh\n\
         # from the repo root (fork aeneas + charon v0.1.196 on PATH via env)\n\
         fuzz/semdiff/oracle.sh <this-dir>/repro.rs --strict\n\
         ```\n\n\
         Verify by hand before claiming a bug: re-run native and Lean, inspect the emitted\n\
         `<dest>/*.lean` for the `{name}` def, and confirm the divergence is real (not a\n\
         range-`for`/noncomputable artifact — those are `LEAN_INCONCLUSIVE`, or an\n\
         overflow-checks mismatch — `native_run.sh` sets `-C overflow-checks=on`).\n",
        verdict = row.verdict,
        name = row.name,
        target = target_name,
        native = row.native_str(),
        lean = row.lean_str(),
    );
    std::fs::write(dir.join("notes.md"), notes)?;
    Ok(dir)
}

fn sanitize(s: &str) -> String {
    s.chars()
        .map(|c| if c.is_alphanumeric() { c } else { '-' })
        .collect()
}

/// Return a slug that does not yet exist under `root` (appending `-2`, `-3`, …).
fn uniquify(root: &Path, base: &str) -> String {
    if !root.join(base).exists() {
        return base.to_string();
    }
    for n in 2..1000 {
        let cand = format!("{base}-{n}");
        if !root.join(&cand).exists() {
            return cand;
        }
    }
    base.to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    const CANNED: &str = r#"[
      {"name":"test_0","native":{"name":"test_0","status":"OK","kind":"ok","msg":""},"lean":"OK","verdict":"MATCH"},
      {"name":"test_1","native":{"name":"test_1","status":"PANIC","kind":"integerOverflow","msg":"attempt to add with overflow"},"lean":"FAIL:integerOverflow","verdict":"MATCH"},
      {"name":"test_2","native":{"name":"test_2","status":"OK","kind":"ok","msg":""},"lean":"FAIL:assertionFailure","verdict":"MISMATCH"},
      {"name":"test_3","native":{"name":"test_3","status":"OK","kind":"ok","msg":""},"lean":null,"verdict":"LEAN_INCONCLUSIVE"},
      {"name":"test_4","native":{"name":"test_4","status":"PANIC","kind":"panic","msg":"x"},"lean":"FAIL:integerOverflow","verdict":"MATCH"}
    ]"#;

    #[test]
    fn parse_and_tally_canned() {
        let rows = parse_verdicts(CANNED).unwrap();
        assert_eq!(rows.len(), 5);
        let t = tally(&rows);
        assert_eq!(t.get("MATCH"), Some(&3));
        assert_eq!(t.get("MISMATCH"), Some(&1));
        assert_eq!(t.get("LEAN_INCONCLUSIVE"), Some(&1));
        let mism: Vec<_> = rows.iter().filter(|r| r.is_mismatch(false)).collect();
        assert_eq!(mism.len(), 1);
        assert_eq!(mism[0].name, "test_2");
        assert_eq!(mism[0].native_str().contains("OK"), true);
        assert_eq!(mism[0].lean_str(), "FAIL:assertionFailure");
    }

    #[test]
    fn extract_fn_brace_matched() {
        let src = "\
#![allow(dead_code)]
struct S { a: u32 }
pub fn test_7() {
    let x = { 1 + 2 };
    assert!(x == 3);
}
pub fn test_8() { assert!(true); }
";
        let f = extract_fn_source(src, "test_7").unwrap();
        assert!(f.starts_with("pub fn test_7()"));
        assert!(f.trim_end().ends_with('}'));
        assert!(f.contains("assert!(x == 3)"));
        assert!(!f.contains("test_8"));
    }

    #[test]
    fn emit_repro_writes_files() {
        let tmp = std::env::temp_dir().join(format!("semdiff-repro-test-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&tmp);
        std::fs::create_dir_all(&tmp).unwrap();
        let rows = parse_verdicts(CANNED).unwrap();
        let m = rows.iter().find(|r| r.verdict == "MISMATCH").unwrap();
        let crate_src = "#![allow(dead_code)]\npub fn test_2() {\n    let x = 1u32;\n    assert!(x == 2);\n}\n";
        let dir = emit_mismatch_repro(&tmp, m, crate_src, "fork", CANNED).unwrap();
        assert!(dir.join("repro.rs").exists());
        assert!(dir.join("test.rs").exists());
        assert!(dir.join("native.json").exists());
        assert!(dir.join("lean.txt").exists());
        assert!(dir.join("notes.md").exists());
        let test_rs = std::fs::read_to_string(dir.join("test.rs")).unwrap();
        assert!(test_rs.contains("pub fn test_2()"));
        let _ = std::fs::remove_dir_all(&tmp);
    }
}
