-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS-LEAN-CHECKER
-- Crate: incr_cert
import Aeneas.Std
open Aeneas (Std)

def incr_cert.incr (x1 : Std.U32) (x2 : Std.U32) : Std.Result Std.U32 :=
  .ok x1

def incr_cert.incr_local (x1 : Std.U32) (x2 : Std.U32) (x3 : Std.U32) (x4 : Std.U32) : Std.Result Std.U32 :=
  .ok x1
