#!/usr/bin/env python3
"""gen_driver.py -- turn an Aeneas-generated Lean file into a semdiff driver.

The Aeneas backend emits, for a crate `foo`, a file like:

    import Aeneas
    open Aeneas Aeneas.Std Result ControlFlow Error
    ...
    namespace foo
    def test_pass : Result Unit := do ...
    #assert (test_pass == ok ())            -- only for #[verify::test] unit fns
    def test_value : Result Std.U32 := do ...
    end foo

We reuse that file verbatim (it already `import Aeneas` and opens the right
namespaces), but:
  * strip the `#assert (...)` lines -- they throw *hard elaboration errors*
    on any failing test, which is exactly what the oracle wants to observe
    quietly rather than abort on; and
  * append a classifier + one `#eval IO.println` per niladic closed `Result`
    definition, printing a machine-parseable `SEMDIFF|<name>|<status>` line.

`<status>` is one of:  OK | FAIL:<errorVariant> | DIV
matching Aeneas.Std.Error: assertionFailure, integerOverflow, divisionByZero,
arrayOutOfBounds, maximumSizeExceeded, panic, undef.

Usage:
    gen_driver.py AENEAS_LEAN_FILE [--prefix test] > Driver.lean

Only niladic definitions (`def NAME : Result ...`, i.e. no parameter list
before the colon) whose name starts with --prefix (default "test") are run,
to stay in lock-step with the native side which runs `pub fn NAME()`.
"""
import argparse
import re
import sys

DEF_RE = re.compile(r'^def\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*Result\b')

CLASSIFIER = '''
/- ===== semdiff oracle appendix (generated) ===== -/
private def semdiffClassify {α : Type} (r : Result α) : String :=
  match r with
  | .ok _ => "OK"
  | .fail .assertionFailure    => "FAIL:assertionFailure"
  | .fail .integerOverflow     => "FAIL:integerOverflow"
  | .fail .divisionByZero      => "FAIL:divisionByZero"
  | .fail .arrayOutOfBounds    => "FAIL:arrayOutOfBounds"
  | .fail .maximumSizeExceeded => "FAIL:maximumSizeExceeded"
  | .fail .panic               => "FAIL:panic"
  | .fail .undef               => "FAIL:undef"
  | .div => "DIV"
'''


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("lean_file")
    ap.add_argument("--prefix", default="test",
                    help="only run defs whose name starts with this (default: test; "
                         "empty string = all niladic Result defs)")
    args = ap.parse_args()

    src = open(args.lean_file).read()
    lines = src.splitlines()

    namespace = None
    tests = []
    kept = []
    for line in lines:
        m = re.match(r'^namespace\s+([A-Za-z_][A-Za-z0-9_.]*)', line)
        if m and namespace is None:
            namespace = m.group(1)
        # Drop Aeneas's own #assert lines: they abort on mismatch.
        if line.startswith("#assert"):
            continue
        kept.append(line)
        dm = DEF_RE.match(line)
        if dm:
            name = dm.group(1)
            if args.prefix == "" or name.startswith(args.prefix):
                tests.append(name)

    out = []
    out.append("-- GENERATED BY semdiff gen_driver.py -- do not edit by hand")
    out.extend(kept)
    out.append(CLASSIFIER)
    if namespace:
        out.append(f"open {namespace}")
    for name in tests:
        # Escaped braces: the s! interpolation needs literal {name}.
        out.append(
            f'#eval IO.println s!"SEMDIFF|{name}|{{semdiffClassify {name}}}"')

    sys.stdout.write("\n".join(out) + "\n")
    # Report the discovered tests on stderr for the driver script.
    sys.stderr.write("tests: " + " ".join(tests) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
