#![allow(unused_variables, dead_code)]

//! Differential harness for the aeneas-lean-checker vertical slice.
//!
//! The original Rust functions live in `tests/src/incr_cert.rs`. We
//! re-export the subset that the M8 cert covers, alongside the
//! generated model in `model.rs`.
//!
//! The M7/M8 translator emits a placeholder body — `incr_model(x, ..)
//! = x` — so the *reference* function we compare against is the
//! identity (`incr_ref`), not the original `incr` (which adds 1). M9+
//! will land the binop translation; at that point this file changes
//! to compare against `*x_after = *x_before + 1`.

pub fn incr_ref(x: u32) -> u32 {
    // M10.0: the cert now carries the `*x += 1` binop, so the model
    // emits `x + 1`. The reference shifts in lock-step. We use
    // `wrapping_add` because the standard `+` panics on overflow in
    // debug mode and the proptest harness includes `u32::MAX`.
    x.wrapping_add(1)
}

// Generated by aeneas-lean-checker before the test runs (see
// build.rs). For local development you can regenerate manually:
//   ./scripts/regenerate-model.sh
include!("model.rs");
