#![allow(unused_variables, dead_code, non_snake_case, unused_parens, unused_mut, clippy::all)]

//! Differential harness for the aeneas-lean-checker vertical slice.
//!
//! Layout:
//!   - `ref_impl` / `model` — flat fixtures without crate-local ADTs
//!     (single hand-curated `model.rs` with `<crate>_<fn>_model`
//!     names; regen via `scripts/regen-diff-models.sh`).
//!   - `aggregates_basic` / `reborrows` — per-fixture modules for
//!     ADT fixtures (each carries its own `struct Pair` decl, so
//!     they cannot share the flat namespace).
//!
//! Proptests in `tests/diff.rs` compare R₀ (the original Rust source,
//! copied verbatim from `tests/src/*.rs`) against R₁ (the
//! `aeneas-check --rust-model` output) on randomised inputs.

/// Reference implementations (R₀) copied verbatim from
/// `tests/src/*.rs`. `&mut` signatures are reshaped to forward
/// scalars to match the cert convention.
pub mod ref_impl {
    // ---- incr_cert.rs ----

    /// `pub fn incr(x: &mut u32) { *x += 1; }` reshaped to
    /// `u32 → u32`. Release-mode `+` wraps silently.
    pub fn incr_cert_incr(x: u32) -> u32 {
        x.wrapping_add(1)
    }

    // ---- constants.rs ----

    pub const fn constants_incr(n: u32) -> u32 {
        n.wrapping_add(1)
    }

    pub const fn constants_mk_pair0(x: u32, y: u32) -> (u32, u32) {
        (x, y)
    }

    pub const fn constants_add(a: i32, b: i32) -> i32 {
        a.wrapping_add(b)
    }

    // ---- bitwise.rs ----

    pub fn bitwise_xor_u32(a: u32, b: u32) -> u32 {
        a ^ b
    }

    pub fn bitwise_or_u32(a: u32, b: u32) -> u32 {
        a | b
    }

    pub fn bitwise_and_u32(a: u32, b: u32) -> u32 {
        a & b
    }

    pub fn bitwise_shift_u32(a: u32) -> u32 {
        let i: usize = 16;
        let mut t = a >> i;
        t <<= i;
        t
    }

    pub fn bitwise_shift_i32(a: i32) -> i32 {
        let i: isize = 16;
        let mut t = a >> i;
        t <<= i;
        t
    }

    // ---- compare_simple.rs ----

    pub fn compare_simple_id_u32(x: u32) -> u32 {
        x
    }

    pub fn compare_simple_add_u32(a: u32, b: u32) -> u32 {
        a.wrapping_add(b)
    }

    // ---- calls.rs ----

    /// `pub fn incr_inner(y: &mut u32)` reshaped to `u32 → u32` per
    /// the cert convention (forward collapses `&mut` borrow).
    pub fn calls_incr_inner(y: u32) -> u32 {
        y.wrapping_add(1)
    }

    /// `pub fn pick(b: bool, x: u32, y: u32) -> u32`.
    pub fn calls_pick(b: bool, x: u32, y: u32) -> u32 {
        let mut r = 0u32;
        if b {
            r = x;
        } else {
            r = y;
        }
        r.wrapping_add(1)
    }

    // ---- scalars.rs ----

    pub fn scalars_u32_use_wrapping_add(x: u32, y: u32) -> u32 {
        x.wrapping_add(y)
    }
    pub fn scalars_i32_use_wrapping_add(x: i32, y: i32) -> i32 {
        x.wrapping_add(y)
    }
    pub fn scalars_u32_use_wrapping_sub(x: u32, y: u32) -> u32 {
        x.wrapping_sub(y)
    }
    pub fn scalars_i32_use_wrapping_sub(x: i32, y: i32) -> i32 {
        x.wrapping_sub(y)
    }
    pub fn scalars_u32_use_shift_right(x: u32) -> u32 {
        x >> 2
    }
    pub fn scalars_i32_use_shift_right(x: i32) -> i32 {
        x >> 2
    }
    pub fn scalars_u32_use_shift_left(x: u32) -> u32 {
        x << 2
    }
    pub fn scalars_i32_use_shift_left(x: i32) -> i32 {
        x << 2
    }
    pub fn scalars_add_and(a: u32, b: u32) -> u32 {
        // Release-mode `+` wraps, matching the model's release-mode `+`.
        (b & a).wrapping_add(b & a)
    }
    pub fn scalars_u32_use_rotate_right(x: u32) -> u32 {
        x.rotate_right(2)
    }
    pub fn scalars_i32_use_rotate_right(x: i32) -> i32 {
        x.rotate_right(2)
    }
    pub fn scalars_u32_use_rotate_left(x: u32) -> u32 {
        x.rotate_left(2)
    }
    pub fn scalars_i32_use_rotate_left(x: i32) -> i32 {
        x.rotate_left(2)
    }

    // ---- demo.rs ----

    pub fn demo_mul2_add1(x: u32) -> u32 {
        // Source uses `+`, release wraps; matches the model's
        // `(x + x) + 1` body.
        x.wrapping_add(x).wrapping_add(1)
    }
    pub fn demo_incr(x: u32) -> u32 {
        x.wrapping_add(1)
    }
}

/// Generated by `aeneas-check --rust-model` per fixture, then
/// reconciled into a single hand-curated file. Regenerate via
/// `./scripts/regen-diff-models.sh`.
pub mod model {
    include!("model.rs");
}

// ----------------------------------------------------------------------
// Phase 1C: ADT fixtures — per-fixture modules with their own struct
// decls. Each crate's `Pair` etc. is module-local to avoid name
// collisions with other fixtures' homonyms.
// ----------------------------------------------------------------------

pub mod aggregates_basic {
    #![allow(unused_variables, dead_code, unused_parens, unused_mut, non_snake_case)]

    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
    pub struct Pair {
        pub x: u32,
        pub y: u32,
    }

    pub fn mk_pair_ref(x: u32, y: u32) -> Pair {
        Pair { x, y }
    }

    pub fn mk_tuple_ref(x: u32, y: u32) -> (u32, u32) {
        (x, y)
    }

    include!("aggregates_basic_model.rs");
}

pub mod reborrows {
    #![allow(unused_variables, dead_code, unused_parens, unused_mut, non_snake_case)]

    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
    pub struct Pair {
        pub fst: u32,
        pub snd: u32,
    }

    pub fn set_fst_ref(p: Pair, v: u32) -> Pair {
        let mut p = p;
        p.fst = v;
        p
    }

    // Phase 1C: copy of `set_fst_model` emitted by aeneas-check from
    // tests/llbc/reborrows.cert.json. The sibling `set_idx_model` in
    // the same generated file emits `Array.update(x1, x2, x3)` (a
    // separate emitter gap), so we hand-copy just this one fn here
    // instead of `include!`ing the whole file.
    pub fn set_fst_model(x1: Pair, x2: u32) -> Pair {
        Pair { fst: x2, ..x1 }
    }
}

// Session 4 — Phase 4b sweep (Item 4b): enum fixtures unblocked by the
// `PExpr.toRust` rewrite that turns Lean-style `Type.Ctor` paths into
// Rust's `Type::Ctor`. `enums_basic::flip` exercises a nullary-only
// enum match-arm round trip; `enums_payload::{value, wrap, zero}` adds
// a payload-bearing variant.

pub mod enums_basic {
    #![allow(unused_variables, dead_code, unused_parens, unused_mut, non_snake_case)]

    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
    pub enum Sign {
        Pos,
        Neg,
        Zero,
    }

    pub fn flip_ref(s: Sign) -> Sign {
        match s {
            Sign::Pos => Sign::Neg,
            Sign::Neg => Sign::Pos,
            Sign::Zero => Sign::Zero,
        }
    }

    // Verbatim from /tmp/enums_basic-rmodel.rs (post-Session-4
    // `::`-path fix). The cert walker correctly converts the bodies
    // after Session 4's `PExpr.toRust` rewrite.
    pub fn flip_model(x1: Sign) -> Sign {
        match x1 { Sign::Pos => Sign::Neg, Sign::Neg => Sign::Pos, Sign::Zero => Sign::Zero, }
    }
}

// Session 4 — Phase 4b sweep (Item 4a): demo fixture's intra-crate
// call cases. Wrapping the model fns in `pub mod demo { ... }` lets
// the `demo::mul2_add1` and `demo::incr` references resolve.
//
// `mod_add` is included here because the cert emits it with a `>>
// 2i32` shift amount that the flat-namespace `model::mod_add_model`
// would also handle, but living next to the call-site fns keeps the
// per-fixture grouping consistent.
pub mod demo {
    #![allow(unused_variables, dead_code, unused_parens, unused_mut, non_snake_case)]

    // Source-Rust copies (R₀ side).
    pub fn mul2_add1_ref(x: u32) -> u32 {
        x.wrapping_add(x).wrapping_add(1)
    }
    pub fn use_mul2_add1_ref(x: u32, y: u32) -> u32 {
        mul2_add1_ref(x).wrapping_add(y)
    }
    pub fn mod_add_ref(x: u32, y: u32) -> u32 {
        // Source: `if x < 3329 && y < 3329 { /* unused */ }` followed
        // by Aeneas-style modular-add via wrapping_sub + shift mask.
        // We replicate the cert's chosen lowering exactly.
        let t2 = x.wrapping_add(y);
        let t3 = t2.wrapping_sub(3329);
        let t4 = t3.wrapping_shr(16);
        let t5 = 3329u32 & t4;
        t3.wrapping_add(t5)
    }

    // Model fns. Verbatim from /tmp/demo-rmodel.rs, except the
    // `pub fn mul2_add1` is renamed to bare `mul2_add1` so the
    // intra-module `demo::mul2_add1(...)` call resolves.
    pub fn mul2_add1(x1: u32) -> u32 {
        let t0 = x1.wrapping_add(x1);
        t0.wrapping_add(1u32)
    }
    pub fn use_mul2_add1_model(x1: u32, x2: u32) -> u32 {
        // Cert emit references `demo::mul2_add1`. Inside `pub mod
        // demo { ... }`, Rust would interpret `demo::` as a nested
        // module lookup. `self::mul2_add1` reaches the sibling fn.
        let x1_post = self::mul2_add1(x1);
        x1_post.wrapping_add(x2)
    }
    pub fn mod_add_model(x1: u32, x2: u32) -> u32 {
        // The cert emits `(x1 + x2)` (release-mode wraps), then
        // `u32::wrapping_sub(t2, 3329u32)`, then `(t3 >> 16i32)`
        // (u32 >> i32 — Rust accepts this via the `Shr<i32> for u32`
        // impl), then `(3329u32 & t4)`, then `u32::wrapping_add(t3,
        // t5)`. We render the body with release-mode `+` for the
        // first step to match the emit exactly.
        let t2 = x1.wrapping_add(x2);
        let t3 = u32::wrapping_sub(t2, 3329u32);
        let t4 = (t3 >> 16i32);
        let t5 = (3329u32 & t4);
        u32::wrapping_add(t3, t5)
    }
}

pub mod enums_payload {
    #![allow(unused_variables, dead_code, unused_parens, unused_mut, non_snake_case)]

    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
    pub enum NumOrZero {
        Num(u32),
        Zero,
    }

    pub fn value_ref(x: NumOrZero) -> u32 {
        match x {
            NumOrZero::Num(n) => n,
            NumOrZero::Zero => 0,
        }
    }
    pub fn wrap_ref(x: u32) -> NumOrZero {
        NumOrZero::Num(x)
    }
    pub fn zero_ref() -> NumOrZero {
        NumOrZero::Zero
    }

    // Verbatim from /tmp/enums_payload-rmodel.rs.
    pub fn value_model(x1: NumOrZero) -> u32 {
        match x1 { NumOrZero::Num(x2) => x2, NumOrZero::Zero => 0u32, }
    }
    pub fn wrap_model(x1: u32) -> NumOrZero {
        NumOrZero::Num(x1)
    }
    pub fn zero_model() -> NumOrZero {
        NumOrZero::Zero
    }
}

// ----------------------------------------------------------------------
// Back-compat re-exports so the existing single-fixture proptest in
// tests/diff.rs still compiles unchanged.

pub use model::incr_model;
pub use ref_impl::incr_cert_incr as incr_ref;
