#![allow(unused_variables, dead_code, non_snake_case, unused_parens, unused_mut, clippy::all)]

//! Differential harness for the aeneas-lean-checker vertical slice.
//!
//! Layout:
//!   - `ref_impl` / `model` — flat fixtures without crate-local ADTs
//!     (single hand-curated `model.rs` with `<crate>_<fn>_model`
//!     names; regen via `scripts/regen-diff-models.sh`).
//!   - `aggregates_basic` / `reborrows` — per-fixture modules for
//!     ADT fixtures (each carries its own `struct Pair` decl, so
//!     they cannot share the flat namespace).
//!
//! Proptests in `tests/diff.rs` compare R₀ (the original Rust source,
//! copied verbatim from `tests/src/*.rs`) against R₁ (the
//! `aeneas-check --rust-model` output) on randomised inputs.

/// Reference implementations (R₀) copied verbatim from
/// `tests/src/*.rs`. `&mut` signatures are reshaped to forward
/// scalars to match the cert convention.
pub mod ref_impl {
    // ---- incr_cert.rs ----

    /// `pub fn incr(x: &mut u32) { *x += 1; }` reshaped to
    /// `u32 → u32`. Release-mode `+` wraps silently.
    pub fn incr_cert_incr(x: u32) -> u32 {
        x.wrapping_add(1)
    }

    // ---- constants.rs ----

    pub const fn constants_incr(n: u32) -> u32 {
        n.wrapping_add(1)
    }

    pub const fn constants_mk_pair0(x: u32, y: u32) -> (u32, u32) {
        (x, y)
    }

    pub const fn constants_add(a: i32, b: i32) -> i32 {
        a.wrapping_add(b)
    }

    // ---- bitwise.rs ----

    pub fn bitwise_xor_u32(a: u32, b: u32) -> u32 {
        a ^ b
    }

    pub fn bitwise_or_u32(a: u32, b: u32) -> u32 {
        a | b
    }

    pub fn bitwise_and_u32(a: u32, b: u32) -> u32 {
        a & b
    }

    pub fn bitwise_shift_u32(a: u32) -> u32 {
        let i: usize = 16;
        let mut t = a >> i;
        t <<= i;
        t
    }

    pub fn bitwise_shift_i32(a: i32) -> i32 {
        let i: isize = 16;
        let mut t = a >> i;
        t <<= i;
        t
    }

    // ---- compare_simple.rs ----

    pub fn compare_simple_id_u32(x: u32) -> u32 {
        x
    }

    pub fn compare_simple_add_u32(a: u32, b: u32) -> u32 {
        a.wrapping_add(b)
    }

    // ---- calls.rs ----

    /// `pub fn incr_inner(y: &mut u32)` reshaped to `u32 → u32` per
    /// the cert convention (forward collapses `&mut` borrow).
    pub fn calls_incr_inner(y: u32) -> u32 {
        y.wrapping_add(1)
    }

    /// `pub fn pick(b: bool, x: u32, y: u32) -> u32`.
    pub fn calls_pick(b: bool, x: u32, y: u32) -> u32 {
        let mut r = 0u32;
        if b {
            r = x;
        } else {
            r = y;
        }
        r.wrapping_add(1)
    }
}

/// Generated by `aeneas-check --rust-model` per fixture, then
/// reconciled into a single hand-curated file. Regenerate via
/// `./scripts/regen-diff-models.sh`.
pub mod model {
    include!("model.rs");
}

// ----------------------------------------------------------------------
// Phase 1C: ADT fixtures — per-fixture modules with their own struct
// decls. Each crate's `Pair` etc. is module-local to avoid name
// collisions with other fixtures' homonyms.
// ----------------------------------------------------------------------

pub mod aggregates_basic {
    #![allow(unused_variables, dead_code, unused_parens, unused_mut, non_snake_case)]

    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
    pub struct Pair {
        pub x: u32,
        pub y: u32,
    }

    pub fn mk_pair_ref(x: u32, y: u32) -> Pair {
        Pair { x, y }
    }

    pub fn mk_tuple_ref(x: u32, y: u32) -> (u32, u32) {
        (x, y)
    }

    include!("aggregates_basic_model.rs");
}

pub mod reborrows {
    #![allow(unused_variables, dead_code, unused_parens, unused_mut, non_snake_case)]

    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
    pub struct Pair {
        pub fst: u32,
        pub snd: u32,
    }

    pub fn set_fst_ref(p: Pair, v: u32) -> Pair {
        let mut p = p;
        p.fst = v;
        p
    }

    // Phase 1C: copy of `set_fst_model` emitted by aeneas-check from
    // tests/llbc/reborrows.cert.json. The sibling `set_idx_model` in
    // the same generated file emits `Array.update(x1, x2, x3)` (a
    // separate emitter gap), so we hand-copy just this one fn here
    // instead of `include!`ing the whole file.
    pub fn set_fst_model(x1: Pair, x2: u32) -> Pair {
        Pair { fst: x2, ..x1 }
    }
}

// ----------------------------------------------------------------------
// Back-compat re-exports so the existing single-fixture proptest in
// tests/diff.rs still compiles unchanged.

pub use model::incr_model;
pub use ref_impl::incr_cert_incr as incr_ref;
