// HAND-CURATED MODEL FILE for the differential harness.
//
// Each block below is the verbatim `aeneas-check --rust-model` output
// for the named cert, renamed with a `<crate>_<fn>_model` suffix so
// multiple fixtures coexist in a single Rust module. Regenerate with
//
//   aeneas-lean-checker/.lake/build/bin/aeneas-check \
//     tests/llbc/<fixture>.cert.json --rust-model /tmp/<fixture>_m.rs
//
// and reconcile any rename diffs.

// ---- incr_cert.cert.json ----
//   ✓ incr        — `(x1 + 1u32)`
//   ✓ incr_local  — `(x1 + 1u32)`

pub fn incr_model(x1: u32) -> u32 {
    (x1 + 1u32)
}

pub fn incr_local_model(x1: u32) -> u32 {
    (x1 + 1u32)
}

// ---- constants.cert.json ----
//   ✓ incr        — `(x1 + 1u32)`         (same shape as incr_cert::incr)
//   ✓ mk_pair0    — `(x1, x2)`
//   ✓ add         — `(x1 + x2)`           (release-mode wraps for i32)

pub fn constants_incr_model(x1: u32) -> u32 {
    (x1 + 1u32)
}

pub fn constants_mk_pair0_model(x1: u32, x2: u32) -> (u32, u32) {
    (x1, x2)
}

pub fn constants_add_model(x1: i32, x2: i32) -> i32 {
    (x1 + x2)
}

// ---- bitwise.cert.json ----
//   ✓ shift_u32   — `(x1 >> 16usize) << 16usize`
//   ✓ shift_i32   — `(x1 >> 16isize) << 16isize`
//   ✓ xor_u32     — `(x1 ^ x2)`
//   ✓ or_u32      — `(x1 | x2)`
//   ✓ and_u32     — `(x1 & x2)`

pub fn bitwise_shift_u32_model(x1: u32) -> u32 {
    let t0 = (x1 >> 16usize);
    (t0 << 16usize)
}

pub fn bitwise_shift_i32_model(x1: i32) -> i32 {
    let t0 = (x1 >> 16isize);
    (t0 << 16isize)
}

pub fn bitwise_xor_u32_model(x1: u32, x2: u32) -> u32 {
    (x1 ^ x2)
}

pub fn bitwise_or_u32_model(x1: u32, x2: u32) -> u32 {
    (x1 | x2)
}

pub fn bitwise_and_u32_model(x1: u32, x2: u32) -> u32 {
    (x1 & x2)
}

// ---- compare_simple.cert.json ----
//   ✓ id_u32      — identity
//   ✓ add_u32     — `u32::wrapping_add(x1, x2)`   (post-3d086b79 brace fix)

pub fn compare_simple_id_u32_model(x1: u32) -> u32 {
    x1
}

pub fn compare_simple_add_u32_model(x1: u32, x2: u32) -> u32 {
    u32::wrapping_add(x1, x2)
}

// ---- calls.cert.json ----
//   ✓ incr_inner  — `(x1 + 1u32)`              (forward collapses &mut)
//   ✓ pick        — `let t0 = if x1 { x2 } else { x3 }; u32::wrapping_add(t0, 1u32)`

pub fn calls_incr_inner_model(x1: u32) -> u32 {
    (x1 + 1u32)
}

pub fn calls_pick_model(x1: bool, x2: u32, x3: u32) -> u32 {
    let t0 = if x1 { x2 } else { x3 };
    u32::wrapping_add(t0, 1u32)
}

// ---- scalars.cert.json (Phase 4b — new fixture) ----
//   The cert emits ~22 fns; we wire only those whose body is a clean
//   self-contained arithmetic / bitwise / shift / rotate. The rest
//   (casts that the emitter renders as identity, `Default::default`
//   that gets emitted as `u32::default` without parens, the match-
//   shaped fns that fold to constants) are skipped per the prompt's
//   "well-emitted bodies only" rule. Bodies copied verbatim from
//   /tmp/sweep-rust-models/scalars.rs (post Phase 4a-2 brace fix).

pub fn scalars_u32_use_wrapping_add_model(x1: u32, x2: u32) -> u32 {
    u32::wrapping_add(x1, x2)
}

pub fn scalars_i32_use_wrapping_add_model(x1: i32, x2: i32) -> i32 {
    i32::wrapping_add(x1, x2)
}

pub fn scalars_u32_use_wrapping_sub_model(x1: u32, x2: u32) -> u32 {
    u32::wrapping_sub(x1, x2)
}

pub fn scalars_i32_use_wrapping_sub_model(x1: i32, x2: i32) -> i32 {
    i32::wrapping_sub(x1, x2)
}

pub fn scalars_u32_use_shift_right_model(x1: u32) -> u32 {
    (x1 >> 2i32)
}

pub fn scalars_i32_use_shift_right_model(x1: i32) -> i32 {
    (x1 >> 2i32)
}

pub fn scalars_u32_use_shift_left_model(x1: u32) -> u32 {
    (x1 << 2i32)
}

pub fn scalars_i32_use_shift_left_model(x1: i32) -> i32 {
    (x1 << 2i32)
}

pub fn scalars_add_and_model(x1: u32, x2: u32) -> u32 {
    let t0 = (x2 & x1);
    let t1 = (x2 & x1);
    (t0 + t1)
}

pub fn scalars_u32_use_rotate_right_model(x1: u32) -> u32 {
    u32::rotate_right(x1, 2u32)
}

pub fn scalars_i32_use_rotate_right_model(x1: i32) -> i32 {
    i32::rotate_right(x1, 2u32)
}

pub fn scalars_u32_use_rotate_left_model(x1: u32) -> u32 {
    u32::rotate_left(x1, 2u32)
}

pub fn scalars_i32_use_rotate_left_model(x1: i32) -> i32 {
    i32::rotate_left(x1, 2u32)
}

// ---- demo.cert.json (Phase 4b — new fixture) ----
//   `mul2_add1` and `incr` are self-contained (no intra-crate calls).
//   `use_mul2_add1` and `use_incr` reference `demo::*` in the emit —
//   would need module wrapping; skipped. Closure-based `choose` /
//   `list_nth` skipped (M12.2a placeholder).

pub fn demo_mul2_add1_model(x1: u32) -> u32 {
    let t0 = (x1 + x1);
    (t0 + 1u32)
}

pub fn demo_incr_model(x1: u32) -> u32 {
    (x1 + 1u32)
}
// AUTO-GENERATED by meta-harness model regen. DO NOT EDIT.
// Scalar-only sig + scalar-only body filter.

// ---- adt ----
pub fn adt_f_model() -> () {
    ()
}

// ---- aggregates_basic ----
pub fn aggregates_basic_mk_tuple_model(x: u32, y: u32) -> (u32, u32) {
    (x, y)
}

// ---- arrays ----
pub fn arrays_incr_model(x: u32) -> u32 {
    (x + 1u32)
}

// ---- arrays ----
pub fn arrays_f2_model(x1: u32) -> () {
    ()
}

// ---- closures ----
pub fn closures_u8_id_model(x: u8) -> u8 {
    x
}

// ---- compare_simple ----
pub fn compare_simple_incr_val_model(x: u32) -> u32 {
    (x + 1u32)
}

// ---- constants ----
pub fn constants_X0_model() -> u32 {
    0u32
}

// ---- constants ----
pub fn constants_X1_model() -> u32 {
    u32::MAX
}

// ---- constants ----
pub fn constants_X2_model() -> u32 {
    3u32
}

// ---- constants ----
pub fn constants_P2_model() -> (u32, u32) {
    (0u32, 1u32)
}

// ---- constants ----
pub fn constants_Q1_model() -> i32 {
    5i32
}

// ---- constants ----
pub fn constants_S1_model() -> u32 {
    6u32
}

// ---- constants ----
pub fn constants_Z1_model() -> i32 {
    3i32
}

// ---- constants ----
pub fn constants_LEN_model() -> usize {
    0usize
}

// ---- dyn ----
pub fn dyn_bool_to_trait_model(b: bool) -> bool {
    b
}

// ---- from_to ----
pub fn from_to_from_model(x: u32) -> u32 {
    x
}

// ---- hashmap ----
pub fn hashmap_hash_key_model(k: usize) -> usize {
    k
}

// ---- incr_cert ----
pub fn incr_cert_incr_model(x: u32) -> u32 {
    (x + 1u32)
}

// ---- incr_cert ----
pub fn incr_cert_incr_local_model(y: u32) -> u32 {
    (y + 1u32)
}

// ---- joins ----
pub fn joins_opt_add_1_model(b: bool, x: u32) -> u32 {
    let t0 = if b { 1u32 } else { 0u32 };
    (x + t0)
}

// ---- joins ----
pub fn joins_opt_add_2_model(b: bool, x: u32) -> u32 {
    let t0 = if b { 1u32 } else { 0u32 };
    let t1 = if b { 1u32 } else { 0u32 };
    let t2 = (x + t0);
    (t2 + t1)
}

// ---- joins ----
pub fn joins_opt_add_1_or_panic_model(b: bool, x: u32) -> u32 {
    (x + 1u32)
}

// ---- joins ----
pub fn joins_opt_add_switch_1_model(a: u32, x: u32) -> u32 {
    (x + 1u32)
}

// ---- loops ----
pub fn loops_bar_model(_a: bool) -> bool {
    _a
}

// ---- loops ----
pub fn loops_reborrow_model(x: u64) -> u64 {
    x
}

// ---- no_nested_borrows ----
pub fn no_nested_borrows_cast_u32_to_i32_model(x: u32) -> i32 {
    (x as i32)
}

// ---- no_nested_borrows ----
pub fn no_nested_borrows_cast_bool_to_i32_model(x: bool) -> i32 {
    (x as i32)
}

// ---- no_nested_borrows ----
pub fn no_nested_borrows_cast_bool_to_bool_model(x: bool) -> bool {
    x
}

// ---- no_nested_borrows ----
pub fn no_nested_borrows_test2_model() -> () {
    let t0 = (23u32 + 44u32);
    ()
}

// ---- no_nested_borrows ----
pub fn no_nested_borrows_get_max_model(x: u32, y: u32) -> u32 {
    let t0 = (x >= y);
    if t0 { x } else { y }
}

// ---- no_nested_borrows ----
pub fn no_nested_borrows_test_neg1_model() -> () {
    let t0 = (3i32 == -3i32);
    ()
}

// ---- no_nested_borrows ----
pub fn no_nested_borrows_refs_test1_model() -> () {
    let t0 = (0i32 == 1i32);
    ()
}

// ---- no_nested_borrows ----
pub fn no_nested_borrows_refs_test2_model() -> () {
    let t0 = (0i32 == 2i32);
    let t1 = (0i32 == 0i32);
    let t2 = (1i32 == 2i32);
    let t3 = (1i32 == 2i32);
    ()
}

// ---- no_nested_borrows ----
pub fn no_nested_borrows_copy_int_model(x: i32) -> i32 {
    x
}

// ---- no_nested_borrows ----
pub fn no_nested_borrows_test_unreachable_model(b: bool) -> () {
    ()
}

// ---- no_nested_borrows ----
pub fn no_nested_borrows_test_panic_model(b: bool) -> () {
    ()
}

// ---- no_nested_borrows ----
pub fn no_nested_borrows_test_panic_msg_model(b: bool) -> () {
    ()
}

// ---- no_nested_borrows ----
pub fn no_nested_borrows_panic_mut_borrow_model(x1: u32) -> u32 {
    x1
}

// ---- no_nested_borrows ----
pub fn no_nested_borrows_test_weird_borrows1_model() -> () {
    ()
}

// ---- no_nested_borrows ----
pub fn no_nested_borrows_test_shared_borrow_bool1_model(b: bool) -> u32 {
    if b { 0u32 } else { 1u32 }
}

// ---- no_nested_borrows ----
pub fn no_nested_borrows_test_shared_borrow_bool2_model() -> u32 {
    0u32
}

// ---- no_nested_borrows ----
pub fn no_nested_borrows_test_shared_borrow_enum2_model() -> u32 {
    0u32
}

// ---- no_nested_borrows ----
pub fn no_nested_borrows_incr_model(x: u32) -> u32 {
    (x + 1u32)
}

// ---- paper ----
pub fn paper_ref_incr_model(x: i32) -> i32 {
    (x + 1i32)
}

// ---- reborrows ----
pub fn reborrows_reborrow_chain_model(x: u32) -> u32 {
    7u32
}

// ---- scalars ----
pub fn scalars_match_usize_model(x: usize) -> bool {
    false
}

// ---- scalars ----
pub fn scalars_match_isize_model(x: isize) -> isize {
    (x + 1isize)
}

// ---- scalars ----
pub fn scalars_u32_as_u16_model(x: u32) -> u16 {
    (x as u16)
}

// ---- scalars ----
pub fn scalars_u16_as_u32_model(x: u16) -> u32 {
    (x as u32)
}

// ---- scalars ----
pub fn scalars_u32_as_i16_model(x: u32) -> i16 {
    (x as i16)
}

// ---- scalars ----
pub fn scalars_i16_as_u32_model(x: i16) -> u32 {
    (x as u32)
}

// ---- scalars ----
pub fn scalars_u32_use_bits_model() -> u32 {
    u32::BITS
}

// ---- scalars ----
pub fn scalars_i32_use_bits_model() -> u32 {
    i32::BITS
}

// ---- static ----
pub fn static_use_static_model() -> () {
    ()
}

// ---- switch_test ----
pub fn switch_test_match_u32_model(x: u32) -> u32 {
    2u32
}

// ---- traits ----
pub fn traits_use_with_const_ty1_model() -> usize {
    0usize
}

// ---- traits ----
pub fn traits_test_where2_model(_x: u32) -> () {
    ()
}

// ---- traits ----
pub fn traits_order1_model() -> () {
    ()
}

// ---- traits ----
pub fn traits_convert_model(x: u32) -> u32 {
    x
}

// ---- traits ----
pub fn traits_LEN2_model() -> usize {
    32usize
}

// ---- traits ----
pub fn traits_LEN1_model() -> usize {
    12usize
}

// ---- traits ----
pub fn traits_LEN_model() -> usize {
    0usize
}

