-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [hax_tests]: function definitions
import Aeneas
import CoreModels
import HaxTests.Extraction.Types
import HaxTests.Extraction.FunsExternal
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace hax_tests

/-- [hax_tests::basic::only_requires]:
    Source: 'src/lib.rs', lines 9:4-11:5 -/
def basic.only_requires (x : Std.U32) : RustM Std.U32 := do
  x + 1#u32

/-- [hax_tests::basic::only_ensures]:
    Source: 'src/lib.rs', lines 14:4-16:5 -/
def basic.only_ensures (x : Std.U32) : RustM Std.U32 := do
  ok x

/-- [hax_tests::basic::both]:
    Source: 'src/lib.rs', lines 20:4-22:5 -/
def basic.both (x : Std.U32) : RustM Std.U32 := do
  x + 1#u32

/-- [hax_tests::basic::returns_unit]:
    Source: 'src/lib.rs', lines 27:4-27:30 -/
def basic.returns_unit (x : Std.U32) : RustM Unit := do
  ok ()

/-- [hax_tests::basic::no_args]:
    Source: 'src/lib.rs', lines 31:4-34:5 -/
def basic.no_args : RustM Unit := do
  ok ()

/-- [hax_tests::basic::block_in_requires]:
    Source: 'src/lib.rs', lines 38:4-40:5 -/
def basic.block_in_requires (x : Std.U32) : RustM Std.U32 := do
  ok x

/-- [hax_tests::basic::returns_pair]:
    Source: 'src/lib.rs', lines 44:4-46:5 -/
def basic.returns_pair (x : Std.U32) : RustM (Std.U32 × Std.U32) := do
  ok (x, x)

/-- [hax_tests::extra_args::generic]:
    Source: 'src/lib.rs', lines 56:4-58:5 -/
def extra_args.generic (N : Std.U32) (x : Std.U32) : RustM Std.U32 := do
  N - x

/-- [hax_tests::extra_args::{impl hax_tests::extra_args::Val for u32}::value]:
    Source: 'src/lib.rs', lines 66:8-68:9 -/
def U32.Insts.Hax_testsExtra_argsVal.value
  (self : Std.U32) : RustM Std.U32 := do
  ok self

/-- Trait implementation: [hax_tests::extra_args::{impl hax_tests::extra_args::Val for u32}]
    Source: 'src/lib.rs', lines 65:4-69:5 -/
@[reducible]
def U32.Insts.Hax_testsExtra_argsVal : extra_args.Val Std.U32 := {
  value := U32.Insts.Hax_testsExtra_argsVal.value
}

/-- [hax_tests::extra_args::traits]:
    Source: 'src/lib.rs', lines 73:4-75:5 -/
def extra_args.traits
  {T : Type} (ValInst : extra_args.Val T) (t : T) (x : Std.U32) :
  RustM Std.U32
  := do
  let i ← ValInst.value t
  i + x

/-- [hax_tests::future::incr]:
    Source: 'src/lib.rs', lines 84:4-86:5 -/
def future.incr (x : Std.U32) : RustM Std.U32 := do
  x + 1#u32

/-- [hax_tests::future::incr_i]:
    Source: 'src/lib.rs', lines 92:4-94:5 -/
def future.incr_i
  (x : Slice Std.U32) (i : Std.Usize) : RustM (Slice Std.U32) := do
  let i1 ← Slice.index_usize x i
  let i2 ← i1 + 1#u32
  Slice.update x i i2

/-- [hax_tests::future::swap_and_add]:
    Source: 'src/lib.rs', lines 100:4-106:5 -/
def future.swap_and_add
  (x : Std.U32) (y : Std.U32) : RustM (Std.U32 × Std.U32 × Std.U32) := do
  let i ← x + y
  ok (i, y, x)

/-- [hax_tests::const_generic_ty::{hax_tests::const_generic_ty::MyStruct<N>}::build]:
    Source: 'src/lib.rs', lines 127:8-129:9
    Visibility: public -/
def const_generic_ty.MyStruct.build
  (N : Std.Usize) (k : Std.Usize) : RustM (const_generic_ty.MyStruct N) := do
  ok { cap := k }

/-- [hax_tests::const_generic_ty::{hax_tests::const_generic_ty::MyStruct<N>}::get]:
    Source: 'src/lib.rs', lines 133:8-135:9
    Visibility: public -/
def const_generic_ty.MyStruct.get
  {N : Std.Usize} (self : const_generic_ty.MyStruct N) : RustM Std.Usize := do
  ok self.cap

/-- [hax_tests::implicit_generics::nothing]:
    Source: 'src/lib.rs', lines 151:4-153:5 -/
def implicit_generics.nothing
  (T : Type) (k : Std.Usize) : RustM (core.option.Option T) := do
  ok core.option.Option.None

/-- [hax_tests::implicit_generics::of_fst]:
    Source: 'src/lib.rs', lines 157:4-159:5 -/
def implicit_generics.of_fst
  {T : Type} (N : Std.Usize) (t : T) : RustM (implicit_generics.Pair T N) := do
  ok { fst := t }

/-- [hax_tests::implicit_generics::empty]:
    Source: 'src/lib.rs', lines 163:4-165:5 -/
def implicit_generics.empty
  (T : Type) (N : Std.Usize) (k : Std.Usize) :
  RustM (core.option.Option (implicit_generics.Pair T N))
  := do
  ok core.option.Option.None

/-- [hax_tests::implicit_generics::from_default]:
    Source: 'src/lib.rs', lines 170:4-172:5 -/
def implicit_generics.from_default
  {T : Type} (N : Std.Usize) (coredefaultDefaultInst : core.default.Default T)
  (k : Std.Usize) :
  RustM (implicit_generics.Pair T N)
  := do
  let t ← coredefaultDefaultInst.default
  ok { fst := t }

/-- [hax_tests::unit_args::{impl hax_tests::unit_args::Size for ()}::len]:
    Source: 'src/lib.rs', lines 189:8-191:9 -/
def Tuple.Insts.Hax_testsUnit_argsSize.len (_ : Unit) : RustM Std.Usize := do
  ok 0#usize

/-- Trait implementation: [hax_tests::unit_args::{impl hax_tests::unit_args::Size for ()}]
    Source: 'src/lib.rs', lines 187:4-192:5 -/
@[reducible]
def Tuple.Insts.Hax_testsUnit_argsSize : unit_args.Size Unit := {
  len := Tuple.Insts.Hax_testsUnit_argsSize.len
}

/-- [hax_tests::unit_args::named]:
    Source: 'src/lib.rs', lines 195:4-197:5 -/
def unit_args.named (_ : Unit) : RustM Std.Usize := do
  ok 0#usize

/-- [hax_tests::unit_args::before_other]:
    Source: 'src/lib.rs', lines 202:4-204:5 -/
def unit_args.before_other (_ : Unit) (y : Std.U32) : RustM Std.U32 := do
  ok y

/-- [hax_tests::supertraits::B::provided]:
    Source: 'src/lib.rs', lines 221:8-223:9
    Visibility: public -/
@[trait_default]
def supertraits.B.provided.default
  {Self : Type} (BInst : supertraits.B Self) (self : Self) :
  RustM Std.Usize
  := do
  BInst.AInst.a self

/-- [hax_tests::supertraits::C::provided_c]:
    Source: 'src/lib.rs', lines 232:8-234:9
    Visibility: public -/
@[trait_default]
def supertraits.C.provided_c.default
  {Self : Type} (CInst : supertraits.C Self) (self : Self) :
  RustM Std.Usize
  := do
  CInst.BInst.AInst.a self

/-- [hax_tests::supertraits::H::provided_h]:
    Source: 'src/lib.rs', lines 245:8-247:9
    Visibility: public -/
@[trait_default]
def supertraits.H.provided_h.default
  {Self : Type} {T : Type} (HInst : supertraits.H Self T) (self : Self) :
  RustM T
  := do
  HInst.GInst.g self

/-- [hax_tests::reserved_names::foo]:
    Source: 'src/lib.rs', lines 258:4-260:5
    Visibility: public -/
def reserved_names.foo (x : Std.U32) : RustM Std.U32 := do
  x + 1#u32

/-- [hax_tests::reserved_names::foo::precondition]:
    Source: 'src/lib.rs', lines 264:8-266:9
    Visibility: public -/
def reserved_names.foo.precondition (x : Std.U32) : RustM Bool := do
  ok (x < 100#u32)

/-- [hax_tests::reserved_names::foo::spec::lemma]:
    Source: 'src/lib.rs', lines 269:12-269:29
    Visibility: public -/
def reserved_names.foo.spec.lemma : RustM Unit := do
  ok ()

/-- [hax_tests::reserved_names::proof]:
    Source: 'src/lib.rs', lines 274:4-274:21
    Visibility: public -/
def reserved_names.proof : RustM Unit := do
  ok ()

/-- [hax_tests::reserved_names::bar::pre]:
    Source: 'src/lib.rs', lines 277:8-277:23
    Visibility: public -/
def reserved_names.bar.pre : RustM Unit := do
  ok ()

end hax_tests
