-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [hax_tests]: proof obligations
import Aeneas
import CoreModels
import HaxTests.Extraction.Types
import HaxTests.Extraction.Funs
import HaxTests.Extraction.Specs
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace hax_tests

theorem basic.only_requires.spec.proof (x : Std.U32) :
  basic.only_requires.spec x
  := by sorry

theorem basic.only_ensures.spec.proof (x : Std.U32) : basic.only_ensures.spec x
  := by sorry

theorem basic.both.spec.proof (x : Std.U32) : basic.both.spec x := by sorry

theorem basic.returns_unit.spec.proof (x : Std.U32) : basic.returns_unit.spec x
  := by sorry

theorem basic.no_args.spec.proof : basic.no_args.spec := by sorry

theorem basic.block_in_requires.spec.proof (x : Std.U32) :
  basic.block_in_requires.spec x
  := by sorry

theorem basic.returns_pair.spec.proof (x : Std.U32) : basic.returns_pair.spec x
  := by sorry

theorem extra_args.generic.spec.proof (N : Std.U32) (x : Std.U32) :
  extra_args.generic.spec N x
  := by sorry

theorem extra_args.traits.spec.proof {T : Type} (ValInst : extra_args.Val T)
  (t : T) (x : Std.U32) : extra_args.traits.spec ValInst t x
  := by sorry

theorem future.incr.spec.proof (x : Std.U32) : future.incr.spec x := by sorry

theorem future.incr_i.spec.proof (x : Slice Std.U32) (i : Std.Usize) :
  future.incr_i.spec x i
  := by sorry

theorem future.swap_and_add.spec.proof (x : Std.U32) (y : Std.U32) :
  future.swap_and_add.spec x y
  := by sorry

theorem implicit_generics.nothing.spec.proof (T : Type) (k : Std.Usize) :
  implicit_generics.nothing.spec T k
  := by sorry

theorem implicit_generics.of_fst.spec.proof {T : Type} (N : Std.Usize) 
  (t : T) : implicit_generics.of_fst.spec N t
  := by sorry

theorem implicit_generics.empty.spec.proof (T : Type) (N : Std.Usize)
  (k : Std.Usize) : implicit_generics.empty.spec T N k
  := by sorry

theorem unit_args.named.spec.proof (_ : Unit) : unit_args.named.spec ()
  := by sorry

theorem unit_args.before_other.spec.proof (_ : Unit) (y : Std.U32) :
  unit_args.before_other.spec () y
  := by sorry

theorem reserved_names.foo.spec.proof (x : Std.U32) : reserved_names.foo.spec x
  := by sorry

theorem const_generic_ty.MyStruct.build.spec.proof (N : Std.Usize)
  (k : Std.Usize) : const_generic_ty.MyStruct.build.spec N k
  := by sorry

theorem const_generic_ty.MyStruct.get.spec.proof {N : Std.Usize}
  (self : const_generic_ty.MyStruct N) :
  const_generic_ty.MyStruct.get.spec self
  := by sorry

theorem Tuple.Insts.Hax_testsUnit_argsSize.len.spec.proof (_ : Unit) :
  Tuple.Insts.Hax_testsUnit_argsSize.len.spec ()
  := by sorry

theorem
  supertraits.B.provided.default.spec.proof {Self : Type} (BInst :
                                           supertraits.B Self) (self : Self) :
  supertraits.B.provided.default.spec BInst self
  := by sorry

theorem
  supertraits.C.provided_c.default.spec.proof {Self : Type} (CInst :
                                             supertraits.C Self) (self : Self)
  : supertraits.C.provided_c.default.spec CInst self
  := by sorry

end hax_tests
