-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [hax_tests]: proof obligations
import Aeneas
import CoreModels
import HaxTests.Extraction.Types
import HaxTests.Extraction.Funs
import HaxTests.Extraction.Specs
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace hax_tests

theorem standalone.contracts.only_requires.spec.proof (x : Std.U32) :
  standalone.contracts.only_requires.spec x
  := by sorry

theorem standalone.contracts.only_ensures.spec.proof (x : Std.U32) :
  standalone.contracts.only_ensures.spec x
  := by sorry

theorem standalone.contracts.both.spec.proof (x : Std.U32) :
  standalone.contracts.both.spec x
  := by sorry

theorem standalone.contracts.returns_unit.spec.proof (x : Std.U32) :
  standalone.contracts.returns_unit.spec x
  := by sorry

theorem standalone.contracts.no_args.spec.proof :
  standalone.contracts.no_args.spec
  := by sorry

theorem standalone.contracts.block_in_requires.spec.proof (x : Std.U32) :
  standalone.contracts.block_in_requires.spec x
  := by sorry

theorem standalone.contracts.returns_pair.spec.proof (x : Std.U32) :
  standalone.contracts.returns_pair.spec x
  := by sorry

theorem standalone.contracts.returns_option.spec.proof (x : Std.U32) :
  standalone.contracts.returns_option.spec x
  := by sorry

theorem standalone.contracts.returns_result.spec.proof (x : Std.U32) :
  standalone.contracts.returns_result.spec x
  := by sorry

theorem standalone.contracts.may_panic.spec.proof (x : Std.U32) (y : Std.U32) :
  standalone.contracts.may_panic.spec x y
  := by sorry

theorem standalone.contracts.explicit_panic.spec.proof (x : Std.U32) :
  standalone.contracts.explicit_panic.spec x
  := by sorry

theorem standalone.arguments.named.spec.proof (_ : Unit) :
  standalone.arguments.named.spec ()
  := by sorry

theorem standalone.arguments.before_other.spec.proof (_ : Unit) (y : Std.U32) :
  standalone.arguments.before_other.spec () y
  := by sorry

theorem standalone.mutable_borrows.incr.spec.proof (x : Std.U32) :
  standalone.mutable_borrows.incr.spec x
  := by sorry

theorem standalone.mutable_borrows.incr_i.spec.proof (x : Slice Std.U32)
  (i : Std.Usize) : standalone.mutable_borrows.incr_i.spec x i
  := by sorry

theorem standalone.mutable_borrows.swap_and_add.spec.proof (x : Std.U32)
  (y : Std.U32) : standalone.mutable_borrows.swap_and_add.spec x y
  := by sorry

theorem standalone.mutable_borrows.read_shared.spec.proof (x : Std.U32) :
  standalone.mutable_borrows.read_shared.spec x
  := by sorry

theorem standalone.mutable_borrows.add_assign.spec.proof (x : Std.U32)
  (y : Std.U32) : standalone.mutable_borrows.add_assign.spec x y
  := by sorry

theorem standalone.generics.generic.spec.proof (N : Std.U32) (x : Std.U32) :
  standalone.generics.generic.spec N x
  := by sorry

theorem
  standalone.generics.trait_clause.spec.proof {T : Type} (ValInst :
                                             standalone.generics.Val T) 
  (t : T) (x : Std.U32) : standalone.generics.trait_clause.spec ValInst t x
  := by sorry

theorem
  standalone.generics.where_clause.spec.proof {T : Type} (ValInst :
                                             standalone.generics.Val T) 
  (t : T) : standalone.generics.where_clause.spec ValInst t
  := by sorry

theorem standalone.generics.nothing.spec.proof (T : Type) (k : Std.Usize) :
  standalone.generics.nothing.spec T k
  := by sorry

theorem standalone.generics.of_fst.spec.proof {T : Type} (N : Std.Usize)
  (t : T) : standalone.generics.of_fst.spec N t
  := by sorry

theorem standalone.generics.empty.spec.proof (T : Type) (N : Std.Usize)
  (k : Std.Usize) : standalone.generics.empty.spec T N k
  := by sorry

theorem standalone.naming.foo.spec.proof (x : Std.U32) :
  standalone.naming.foo.spec x
  := by sorry

theorem Tuple.Insts.Hax_testsStandaloneArgumentsSize.len.spec.proof (_ : Unit)
  : Tuple.Insts.Hax_testsStandaloneArgumentsSize.len.spec ()
  := by sorry

theorem standalone.generics.MyStruct.build.spec.proof (N : Std.Usize)
  (k : Std.Usize) : standalone.generics.MyStruct.build.spec N k
  := by sorry

theorem standalone.generics.MyStruct.get.spec.proof {N : Std.Usize}
  (self : standalone.generics.MyStruct N) :
  standalone.generics.MyStruct.get.spec self
  := by sorry

theorem
  standalone.traits.B.provided.default.spec.proof {Self : Type} (BInst :
                                                 standalone.traits.B Self)
  (self : Self) : standalone.traits.B.provided.default.spec BInst self
  := by sorry

theorem
  standalone.traits.C.provided_c.default.spec.proof {Self : Type} (CInst :
                                                   standalone.traits.C Self)
  (self : Self) : standalone.traits.C.provided_c.default.spec CInst self
  := by sorry

end hax_tests
