-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [hax_tests]: specs (statements of correctness)
import Aeneas
import CoreModels
import Hax
import HaxTests.Extraction.Types
import HaxTests.Extraction.Funs
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace hax_tests


/-- [hax_tests::standalone::contracts::only_requires::pre]:
    Source: 'src/standalone/contracts.rs', lines 3:0-3:20 -/
@[reducible]
def standalone.contracts.only_requires.pre (x : Std.U32) : RustM Bool := do
  ok (x < 100#u32)

def standalone.contracts.only_requires.spec (x : Std.U32) : Prop :=
  (standalone.contracts.only_requires.pre x).holds →
  ⦃ ⌜ True ⌝ ⦄
  standalone.contracts.only_requires x
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [hax_tests::standalone::contracts::only_ensures::post]:
    Source: 'src/standalone/contracts.rs', lines 8:0-8:32 -/
@[reducible]
def standalone.contracts.only_ensures.post
  (x : Std.U32) (result : Std.U32) : RustM Bool := do
  ok (result = x)

def standalone.contracts.only_ensures.spec (x : Std.U32) : Prop :=
  ⦃ ⌜ True ⌝ ⦄
  standalone.contracts.only_ensures x
  ⦃ ⇓ res => ⌜ (standalone.contracts.only_ensures.post x res).holds ⌝
  ⦄


/-- [hax_tests::standalone::contracts::both::pre]:
    Source: 'src/standalone/contracts.rs', lines 13:0-13:19 -/
@[reducible]
def standalone.contracts.both.pre (x : Std.U32) : RustM Bool := do
  ok (x < 10#u32)

/-- [hax_tests::standalone::contracts::both::post]:
    Source: 'src/standalone/contracts.rs', lines 14:0-14:31 -/
@[reducible]
def standalone.contracts.both.post
  (x : Std.U32) (result : Std.U32) : RustM Bool := do
  ok (result > x)

def standalone.contracts.both.spec (x : Std.U32) : Prop :=
  (standalone.contracts.both.pre x).holds →
  ⦃ ⌜ True ⌝ ⦄
  standalone.contracts.both x
  ⦃ ⇓ res => ⌜ (standalone.contracts.both.post x res).holds ⌝ ⦄


/-- [hax_tests::standalone::contracts::returns_unit::pre]:
    Source: 'src/standalone/contracts.rs', lines 20:0-20:19 -/
@[reducible]
def standalone.contracts.returns_unit.pre (x : Std.U32) : RustM Bool := do
  ok (x < 10#u32)

/-- [hax_tests::standalone::contracts::returns_unit::post]:
    Source: 'src/standalone/contracts.rs', lines 21:0-21:20 -/
@[reducible]
def standalone.contracts.returns_unit.post
  (x : Std.U32) (_ : Unit) : RustM Bool := do
  ok true

def standalone.contracts.returns_unit.spec (x : Std.U32) : Prop :=
  (standalone.contracts.returns_unit.pre x).holds →
  ⦃ ⌜ True ⌝ ⦄
  standalone.contracts.returns_unit x
  ⦃ ⇓ res => ⌜ (standalone.contracts.returns_unit.post x res).holds ⌝
  ⦄


/-- [hax_tests::standalone::contracts::no_args::post]:
    Source: 'src/standalone/contracts.rs', lines 25:0-25:20 -/
@[reducible]
def standalone.contracts.no_args.post (_ : Unit) : RustM Bool := do
  ok true

def standalone.contracts.no_args.spec : Prop :=
  ⦃ ⌜ True ⌝ ⦄
  standalone.contracts.no_args
  ⦃ ⇓ res => ⌜ (standalone.contracts.no_args.post res).holds ⌝ ⦄


/-- [hax_tests::standalone::contracts::block_in_requires::pre]:
    Source: 'src/standalone/contracts.rs', lines 32:0-32:42 -/
@[reducible]
def standalone.contracts.block_in_requires.pre (x : Std.U32) : RustM Bool := do
  ok (x > 10#u32)

def standalone.contracts.block_in_requires.spec (x : Std.U32) : Prop :=
  (standalone.contracts.block_in_requires.pre x).holds →
  ⦃ ⌜ True ⌝ ⦄
  standalone.contracts.block_in_requires x
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [hax_tests::standalone::contracts::returns_pair::post]:
    Source: 'src/standalone/contracts.rs', lines 38:0-38:37 -/
@[reducible]
def standalone.contracts.returns_pair.post
  (x : Std.U32) (p : (Std.U32 × Std.U32)) : RustM Bool := do
  let (a, b) := p
  if a = x
  then ok (b = x)
  else ok false

def standalone.contracts.returns_pair.spec (x : Std.U32) : Prop :=
  ⦃ ⌜ True ⌝ ⦄
  standalone.contracts.returns_pair x
  ⦃ ⇓ res => ⌜ (standalone.contracts.returns_pair.post x res).holds ⌝
  ⦄


/-- [hax_tests::standalone::contracts::returns_option::post]:
    Source: 'src/standalone/contracts.rs', lines 44:0-44:70 -/
@[reducible]
def standalone.contracts.returns_option.post
  (x : Std.U32) (result : core.option.Option Std.U32) : RustM Bool := do
  match result with
  | core.option.Option.None => ok false
  | core.option.Option.Some v => ok (v = x)

def standalone.contracts.returns_option.spec (x : Std.U32) : Prop :=
  ⦃ ⌜ True ⌝ ⦄
  standalone.contracts.returns_option x
  ⦃ ⇓ res => ⌜ (standalone.contracts.returns_option.post x res).holds ⌝
  ⦄


/-- [hax_tests::standalone::contracts::returns_result::pre]:
    Source: 'src/standalone/contracts.rs', lines 50:0-50:20 -/
@[reducible]
def standalone.contracts.returns_result.pre (x : Std.U32) : RustM Bool := do
  ok (x < 100#u32)

/-- [hax_tests::standalone::contracts::returns_result::post]:
    Source: 'src/standalone/contracts.rs', lines 51:0-51:74 -/
@[reducible]
def standalone.contracts.returns_result.post
  (x : Std.U32) (result : core.result.Result Std.U32 Unit) : RustM Bool := do
  match result with
  | core.result.Result.Ok v => let i ← x + 1#u32
                               ok (v = i)
  | core.result.Result.Err _ => ok false

def standalone.contracts.returns_result.spec (x : Std.U32) : Prop :=
  (standalone.contracts.returns_result.pre x).holds →
  ⦃ ⌜ True ⌝ ⦄
  standalone.contracts.returns_result x
  ⦃ ⇓ res => ⌜ (standalone.contracts.returns_result.post x res).holds ⌝
  ⦄


/-- [hax_tests::standalone::contracts::may_panic::pre]:
    Source: 'src/standalone/contracts.rs', lines 57:0-57:19 -/
@[reducible]
def standalone.contracts.may_panic.pre
  (x : Std.U32) (y : Std.U32) : RustM Bool := do
  ok (y != 0#u32)

/-- [hax_tests::standalone::contracts::may_panic::post]:
    Source: 'src/standalone/contracts.rs', lines 58:0-58:32 -/
@[reducible]
def standalone.contracts.may_panic.post
  (x : Std.U32) (y : Std.U32) (result : Std.U32) : RustM Bool := do
  ok (result <= x)

def standalone.contracts.may_panic.spec (x : Std.U32) (y : Std.U32) : Prop :=
  (standalone.contracts.may_panic.pre x y).holds →
  ⦃ ⌜ True ⌝ ⦄
  standalone.contracts.may_panic x y
  ⦃ ⇓ res => ⌜ (standalone.contracts.may_panic.post x y res).holds ⌝
  ⦄


/-- [hax_tests::standalone::contracts::explicit_panic::pre]:
    Source: 'src/standalone/contracts.rs', lines 64:0-64:19 -/
@[reducible]
def standalone.contracts.explicit_panic.pre (x : Std.U32) : RustM Bool := do
  ok (x < 10#u32)

/-- [hax_tests::standalone::contracts::explicit_panic::post]:
    Source: 'src/standalone/contracts.rs', lines 65:0-65:32 -/
@[reducible]
def standalone.contracts.explicit_panic.post
  (x : Std.U32) (result : Std.U32) : RustM Bool := do
  ok (result = x)

def standalone.contracts.explicit_panic.spec (x : Std.U32) : Prop :=
  (standalone.contracts.explicit_panic.pre x).holds →
  ⦃ ⌜ True ⌝ ⦄
  standalone.contracts.explicit_panic x
  ⦃ ⇓ res => ⌜ (standalone.contracts.explicit_panic.post x res).holds ⌝
  ⦄


/-- [hax_tests::standalone::arguments::named::post]:
    Source: 'src/standalone/arguments.rs', lines 18:0-18:32 -/
@[reducible]
def standalone.arguments.named.post
  (_ : Unit) (result : Std.Usize) : RustM Bool := do
  ok (result = 0#usize)

def standalone.arguments.named.spec (_ : Unit) : Prop :=
  ⦃ ⌜ True ⌝ ⦄
  standalone.arguments.named ()
  ⦃ ⇓ res => ⌜ (standalone.arguments.named.post () res).holds ⌝ ⦄


/-- [hax_tests::standalone::arguments::before_other::pre]:
    Source: 'src/standalone/arguments.rs', lines 24:0-24:20 -/
@[reducible]
def standalone.arguments.before_other.pre
  (_ : Unit) (y : Std.U32) : RustM Bool := do
  ok (y < 100#u32)

/-- [hax_tests::standalone::arguments::before_other::post]:
    Source: 'src/standalone/arguments.rs', lines 25:0-25:32 -/
@[reducible]
def standalone.arguments.before_other.post
  (_ : Unit) (y : Std.U32) (result : Std.U32) : RustM Bool := do
  ok (result = y)

def standalone.arguments.before_other.spec (_ : Unit) (y : Std.U32) : Prop :=
  (standalone.arguments.before_other.pre () y).holds →
  ⦃ ⌜ True ⌝ ⦄
  standalone.arguments.before_other () y
  ⦃ ⇓ res =>
  ⌜ (standalone.arguments.before_other.post () y res).holds ⌝ ⦄


/-- [hax_tests::standalone::mutable_borrows::incr::pre]:
    Source: 'src/standalone/mutable_borrows.rs', lines 3:0-3:22 -/
@[reducible]
def standalone.mutable_borrows.incr.pre (x : Std.U32) : RustM Bool := do
  ok (x < 1000#u32)

/-- [hax_tests::standalone::mutable_borrows::incr::post]:
    Source: 'src/standalone/mutable_borrows.rs', lines 4:0-4:37 -/
@[reducible]
def standalone.mutable_borrows.incr.post
  (x : Std.U32) (x_future : Std.U32) : RustM Bool := do
  let i ← x + 1#u32
  ok (x_future = i)

def standalone.mutable_borrows.incr.spec (x : Std.U32) : Prop :=
  (standalone.mutable_borrows.incr.pre x).holds →
  ⦃ ⌜ True ⌝ ⦄
  standalone.mutable_borrows.incr x
  ⦃ ⇓ res => ⌜ (standalone.mutable_borrows.incr.post x res).holds ⌝ ⦄


/-- [hax_tests::standalone::mutable_borrows::incr_i::pre]:
    Source: 'src/standalone/mutable_borrows.rs', lines 9:0-9:43 -/
@[reducible]
def standalone.mutable_borrows.incr_i.pre
  (x : Slice Std.U32) (i : Std.Usize) : RustM Bool := do
  let i1 ← core.slice.Slice.len x
  if i < i1
  then let i2 ← Slice.index_usize x i
       ok (i2 < core.num.U32.MAX)
  else ok false

/-- [hax_tests::standalone::mutable_borrows::incr_i::post]:
    Source: 'src/standalone/mutable_borrows.rs', lines 10:0-12:27 -/
@[reducible]
def standalone.mutable_borrows.incr_i.post
  (x : Slice Std.U32) (i : Std.Usize) (x_future : Slice Std.U32) :
  RustM Bool
  := do
  let i1 ← Slice.index_usize x_future i
  let i2 ← Slice.index_usize x i
  let i3 ← i2 + 1#u32
  ok (i1 = i3)

def standalone.mutable_borrows.incr_i.spec (x : Slice Std.U32) (i : Std.Usize)
  : Prop :=
  (standalone.mutable_borrows.incr_i.pre x i).holds →
  ⦃ ⌜ True ⌝ ⦄
  standalone.mutable_borrows.incr_i x i
  ⦃ ⇓ res => ⌜ (standalone.mutable_borrows.incr_i.post x i res).holds ⌝
  ⦄


/-- [hax_tests::standalone::mutable_borrows::swap_and_add::pre]:
    Source: 'src/standalone/mutable_borrows.rs', lines 17:0-17:35 -/
@[reducible]
def standalone.mutable_borrows.swap_and_add.pre
  (x : Std.U32) (y : Std.U32) : RustM Bool := do
  if x < 1000#u32
  then ok (y < 1000#u32)
  else ok false

/-- [hax_tests::standalone::mutable_borrows::swap_and_add::post]:
    Source: 'src/standalone/mutable_borrows.rs', lines 20:0-20:71 -/
@[reducible]
def standalone.mutable_borrows.swap_and_add.post
  (x : Std.U32) (y : Std.U32) (t : (Std.U32 × Std.U32 × Std.U32)) :
  RustM Bool
  := do
  let (r, x_future, y_future) := t
  if y_future = x
  then if x_future = y
       then let i ← x + y
            ok (r = i)
       else ok false
  else ok false

def standalone.mutable_borrows.swap_and_add.spec (x : Std.U32) (y : Std.U32)
  : Prop :=
  (standalone.mutable_borrows.swap_and_add.pre x y).holds →
  ⦃ ⌜ True ⌝ ⦄
  standalone.mutable_borrows.swap_and_add x y
  ⦃ ⇓ res =>
  ⌜ (standalone.mutable_borrows.swap_and_add.post x y res).holds ⌝ ⦄


/-- [hax_tests::standalone::mutable_borrows::read_shared::post]:
    Source: 'src/standalone/mutable_borrows.rs', lines 30:0-30:33 -/
@[reducible]
def standalone.mutable_borrows.read_shared.post
  (x : Std.U32) (result : Std.U32) : RustM Bool := do
  ok (result = x)

def standalone.mutable_borrows.read_shared.spec (x : Std.U32) : Prop :=
  ⦃ ⌜ True ⌝ ⦄
  standalone.mutable_borrows.read_shared x
  ⦃ ⇓ res =>
  ⌜ (standalone.mutable_borrows.read_shared.post x res).holds ⌝ ⦄


/-- [hax_tests::standalone::mutable_borrows::add_assign::pre]:
    Source: 'src/standalone/mutable_borrows.rs', lines 36:0-36:35 -/
@[reducible]
def standalone.mutable_borrows.add_assign.pre
  (x : Std.U32) (y : Std.U32) : RustM Bool := do
  if x < 1000#u32
  then ok (y < 1000#u32)
  else ok false

/-- [hax_tests::standalone::mutable_borrows::add_assign::post]:
    Source: 'src/standalone/mutable_borrows.rs', lines 37:0-37:37 -/
@[reducible]
def standalone.mutable_borrows.add_assign.post
  (x : Std.U32) (y : Std.U32) (x_future : Std.U32) : RustM Bool := do
  let i ← x + y
  ok (x_future = i)

def standalone.mutable_borrows.add_assign.spec (x : Std.U32) (y : Std.U32)
  : Prop :=
  (standalone.mutable_borrows.add_assign.pre x y).holds →
  ⦃ ⌜ True ⌝ ⦄
  standalone.mutable_borrows.add_assign x y
  ⦃ ⇓ res =>
  ⌜ (standalone.mutable_borrows.add_assign.post x y res).holds ⌝ ⦄


/-- [hax_tests::standalone::generics::generic::pre]:
    Source: 'src/standalone/generics.rs', lines 9:0-9:27 -/
@[reducible]
def standalone.generics.generic.pre
  (N : Std.U32) (x : Std.U32) : RustM Bool := do
  if 0#u32 < x
  then ok (x < N)
  else ok false

/-- [hax_tests::standalone::generics::generic::post]:
    Source: 'src/standalone/generics.rs', lines 10:0-10:31 -/
@[reducible]
def standalone.generics.generic.post
  (N : Std.U32) (x : Std.U32) (result : Std.U32) : RustM Bool := do
  ok (result < N)

def standalone.generics.generic.spec (N : Std.U32) (x : Std.U32) : Prop :=
  (standalone.generics.generic.pre N x).holds →
  ⦃ ⌜ True ⌝ ⦄
  standalone.generics.generic N x
  ⦃ ⇓ res => ⌜ (standalone.generics.generic.post N x res).holds ⌝ ⦄


/-- [hax_tests::standalone::generics::trait_clause::pre]:
    Source: 'src/standalone/generics.rs', lines 26:0-26:41 -/
@[reducible]
def standalone.generics.trait_clause.pre
  {T : Type} (ValInst : standalone.generics.Val T) (t : T) (x : Std.U32) :
  RustM Bool
  := do
  let i ← ValInst.value t
  if i < 1000#u32
  then ok (x < 1000#u32)
  else ok false

/-- [hax_tests::standalone::generics::trait_clause::post]:
    Source: 'src/standalone/generics.rs', lines 27:0-27:34 -/
@[reducible]
def standalone.generics.trait_clause.post
  {T : Type} (ValInst : standalone.generics.Val T) (t : T) (x : Std.U32)
  (result : Std.U32) :
  RustM Bool
  := do
  ok (result < 2000#u32)

def
  standalone.generics.trait_clause.spec {T : Type} (ValInst :
                                       standalone.generics.Val T) (t : T)
  (x : Std.U32) : Prop :=
  (standalone.generics.trait_clause.pre ValInst t x).holds →
  ⦃ ⌜ True ⌝ ⦄
  standalone.generics.trait_clause ValInst t x
  ⦃ ⇓ res =>
  ⌜ (standalone.generics.trait_clause.post ValInst t x res).holds ⌝ ⦄


/-- [hax_tests::standalone::generics::where_clause::pre]:
    Source: 'src/standalone/generics.rs', lines 33:0-33:29 -/
@[reducible]
def standalone.generics.where_clause.pre
  {T : Type} (ValInst : standalone.generics.Val T) (t : T) : RustM Bool := do
  let i ← ValInst.value t
  ok (i < 1000#u32)

/-- [hax_tests::standalone::generics::where_clause::post]:
    Source: 'src/standalone/generics.rs', lines 34:0-34:34 -/
@[reducible]
def standalone.generics.where_clause.post
  {T : Type} (ValInst : standalone.generics.Val T) (t : T) (result : Std.U32) :
  RustM Bool
  := do
  ok (result < 1000#u32)

def
  standalone.generics.where_clause.spec {T : Type} (ValInst :
                                       standalone.generics.Val T) (t : T)
  : Prop :=
  (standalone.generics.where_clause.pre ValInst t).holds →
  ⦃ ⌜ True ⌝ ⦄
  standalone.generics.where_clause ValInst t
  ⦃ ⇓ res =>
  ⌜ (standalone.generics.where_clause.post ValInst t res).holds ⌝ ⦄


/-- [hax_tests::standalone::generics::nothing::post]:
    Source: 'src/standalone/generics.rs', lines 70:0-70:20 -/
@[reducible]
def standalone.generics.nothing.post
  {T : Type} (k : Std.Usize) (o : core.option.Option T) : RustM Bool := do
  ok true

def standalone.generics.nothing.spec (T : Type) (k : Std.Usize) : Prop :=
  ⦃ ⌜ True ⌝ ⦄
  standalone.generics.nothing T k
  ⦃ ⇓ res => ⌜ (standalone.generics.nothing.post k res).holds ⌝ ⦄


/-- [hax_tests::standalone::generics::of_fst::post]:
    Source: 'src/standalone/generics.rs', lines 76:0-76:20 -/
@[reducible]
def standalone.generics.of_fst.post
  {T : Type} {N : Std.Usize} (t : T) (p : standalone.generics.Pair T N) :
  RustM Bool
  := do
  ok true

def standalone.generics.of_fst.spec {T : Type} (N : Std.Usize) (t : T)
  : Prop :=
  ⦃ ⌜ True ⌝ ⦄
  standalone.generics.of_fst N t
  ⦃ ⇓ res => ⌜ (standalone.generics.of_fst.post t res).holds ⌝ ⦄


/-- [hax_tests::standalone::generics::empty::post]:
    Source: 'src/standalone/generics.rs', lines 82:0-82:20 -/
@[reducible]
def standalone.generics.empty.post
  {T : Type} {N : Std.Usize} (k : Std.Usize)
  (o : core.option.Option (standalone.generics.Pair T N)) :
  RustM Bool
  := do
  ok true

def standalone.generics.empty.spec (T : Type) (N : Std.Usize) (k : Std.Usize)
  : Prop :=
  ⦃ ⌜ True ⌝ ⦄
  standalone.generics.empty T N k
  ⦃ ⇓ res => ⌜ (standalone.generics.empty.post k res).holds ⌝ ⦄


/-- [hax_tests::standalone::naming::foo::pre]:
    Source: 'src/standalone/naming.rs', lines 5:0-5:20 -/
@[reducible]
def standalone.naming.foo.pre (x : Std.U32) : RustM Bool := do
  ok (x < 100#u32)

/-- [hax_tests::standalone::naming::foo::post]:
    Source: 'src/standalone/naming.rs', lines 6:0-6:36 -/
@[reducible]
def standalone.naming.foo.post
  (x : Std.U32) (result : Std.U32) : RustM Bool := do
  let i ← x + 1#u32
  ok (result = i)

def standalone.naming.foo.spec (x : Std.U32) : Prop :=
  (standalone.naming.foo.pre x).holds →
  ⦃ ⌜ True ⌝ ⦄
  standalone.naming.foo x
  ⦃ ⇓ res => ⌜ (standalone.naming.foo.post x res).holds ⌝ ⦄


/-- [hax_tests::standalone::arguments::{impl hax_tests::standalone::arguments::Size for ()}::len::post]:
    Source: 'src/standalone/arguments.rs', lines 12:4-12:24 -/
@[reducible]
def Tuple.Insts.Hax_testsStandaloneArgumentsSize.len.post
  (_ : Unit) (i : Std.Usize) : RustM Bool := do
  ok true

def Tuple.Insts.Hax_testsStandaloneArgumentsSize.len.spec (_ : Unit) : Prop :=
  ⦃ ⌜ True ⌝ ⦄
  Tuple.Insts.Hax_testsStandaloneArgumentsSize.len ()
  ⦃ ⇓ res =>
  ⌜ (Tuple.Insts.Hax_testsStandaloneArgumentsSize.len.post () res).holds ⌝
  ⦄


/-- [hax_tests::standalone::generics::{hax_tests::standalone::generics::MyStruct<N>}::build::pre]:
    Source: 'src/standalone/generics.rs', lines 50:4-50:24 -/
@[reducible]
def standalone.generics.MyStruct.build.pre
  (N : Std.Usize) (k : Std.Usize) : RustM Bool := do
  ok (k < 100#usize)

/-- [hax_tests::standalone::generics::{hax_tests::standalone::generics::MyStruct<N>}::build::post]:
    Source: 'src/standalone/generics.rs', lines 51:4-51:24 -/
@[reducible]
def standalone.generics.MyStruct.build.post
  {N : Std.Usize} (k : Std.Usize) (ms : standalone.generics.MyStruct N) :
  RustM Bool
  := do
  ok true

def standalone.generics.MyStruct.build.spec (N : Std.Usize) (k : Std.Usize)
  : Prop :=
  (standalone.generics.MyStruct.build.pre N k).holds →
  ⦃ ⌜ True ⌝ ⦄
  standalone.generics.MyStruct.build N k
  ⦃ ⇓ res => ⌜ (standalone.generics.MyStruct.build.post k res).holds ⌝
  ⦄


/-- [hax_tests::standalone::generics::{hax_tests::standalone::generics::MyStruct<N>}::get::post]:
    Source: 'src/standalone/generics.rs', lines 57:4-57:24 -/
@[reducible]
def standalone.generics.MyStruct.get.post
  {N : Std.Usize} (self_ : standalone.generics.MyStruct N) (i : Std.Usize) :
  RustM Bool
  := do
  ok true

def standalone.generics.MyStruct.get.spec {N : Std.Usize}
  (self : standalone.generics.MyStruct N) : Prop :=
  ⦃ ⌜ True ⌝ ⦄
  standalone.generics.MyStruct.get self
  ⦃ ⇓ res => ⌜ (standalone.generics.MyStruct.get.post self res).holds ⌝
  ⦄


/-- [hax_tests::standalone::traits::B::provided::pre]:
    Source: 'src/standalone/traits.rs', lines 7:0-7:22 -/
@[reducible]
def standalone.traits.B.provided.pre
  {Self_ : Type} (AInst : standalone.traits.A Self_) (BInst :
  standalone.traits.B Self_) (self_ : Self_) :
  RustM Bool
  := do
  let i ← AInst.a self_
  ok (i < 100#usize)

/-- [hax_tests::standalone::traits::B::provided::post]:
    Source: 'src/standalone/traits.rs', lines 7:0-7:22 -/
@[reducible]
def standalone.traits.B.provided.post
  {Self_ : Type} (AInst : standalone.traits.A Self_) (BInst :
  standalone.traits.B Self_) (self_ : Self_) (res : Std.Usize) :
  RustM Bool
  := do
  let i ← AInst.a self_
  ok (res = i)

def
  standalone.traits.B.provided.default.spec {Self : Type} (BInst :
                                           standalone.traits.B Self)
  (self : Self) : Prop :=
  (standalone.traits.B.provided.pre BInst.AInst BInst self).holds →
  ⦃ ⌜ True ⌝ ⦄
  standalone.traits.B.provided.default BInst self
  ⦃ ⇓ res =>
  ⌜ (standalone.traits.B.provided.post BInst.AInst BInst self res).holds ⌝
  ⦄


/-- [hax_tests::standalone::traits::C::provided_c::pre]:
    Source: 'src/standalone/traits.rs', lines 20:0-20:22 -/
@[reducible]
def standalone.traits.C.provided_c.pre
  {Self_ : Type} (BInst : standalone.traits.B Self_) (CInst :
  standalone.traits.C Self_) (self_ : Self_) :
  RustM Bool
  := do
  let i ← BInst.AInst.a self_
  ok (i < 100#usize)

/-- [hax_tests::standalone::traits::C::provided_c::post]:
    Source: 'src/standalone/traits.rs', lines 20:0-20:22 -/
@[reducible]
def standalone.traits.C.provided_c.post
  {Self_ : Type} (BInst : standalone.traits.B Self_) (CInst :
  standalone.traits.C Self_) (self_ : Self_) (res : Std.Usize) :
  RustM Bool
  := do
  let i ← BInst.AInst.a self_
  ok (res = i)

def
  standalone.traits.C.provided_c.default.spec {Self : Type} (CInst :
                                             standalone.traits.C Self)
  (self : Self) : Prop :=
  (standalone.traits.C.provided_c.pre CInst.BInst CInst self).holds →
  ⦃ ⌜ True ⌝ ⦄
  standalone.traits.C.provided_c.default CInst self
  ⦃ ⇓ res =>
  ⌜ (standalone.traits.C.provided_c.post CInst.BInst CInst self res).holds
  ⌝ ⦄

end hax_tests
