-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [hax_tests]: specs (statements of correctness)
import Aeneas
import CoreModels
import Hax
import HaxTests.Extraction.Types
import HaxTests.Extraction.Funs
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace hax_tests


/-- [hax_tests::basic::only_requires::pre]:
    Source: 'src/lib.rs', lines 8:4-8:24 -/
@[reducible]
def basic.only_requires.pre (x : Std.U32) : RustM Bool := do
  ok (x < 100#u32)

def basic.only_requires.spec (x : Std.U32) : Prop :=
  (basic.only_requires.pre x).holds →
  ⦃ ⌜ True ⌝ ⦄
  basic.only_requires x
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [hax_tests::basic::only_ensures::post]:
    Source: 'src/lib.rs', lines 13:4-13:36 -/
@[reducible]
def basic.only_ensures.post (x : Std.U32) (result : Std.U32) : RustM Bool := do
  ok (result = x)

def basic.only_ensures.spec (x : Std.U32) : Prop :=
  ⦃ ⌜ True ⌝ ⦄
  basic.only_ensures x
  ⦃ ⇓ res => ⌜ (basic.only_ensures.post x res).holds ⌝ ⦄


/-- [hax_tests::basic::both::pre]:
    Source: 'src/lib.rs', lines 18:4-18:23 -/
@[reducible]
def basic.both.pre (x : Std.U32) : RustM Bool := do
  ok (x < 10#u32)

/-- [hax_tests::basic::both::post]:
    Source: 'src/lib.rs', lines 19:4-19:35 -/
@[reducible]
def basic.both.post (x : Std.U32) (result : Std.U32) : RustM Bool := do
  ok (result > x)

def basic.both.spec (x : Std.U32) : Prop :=
  (basic.both.pre x).holds →
  ⦃ ⌜ True ⌝ ⦄
  basic.both x
  ⦃ ⇓ res => ⌜ (basic.both.post x res).holds ⌝ ⦄


/-- [hax_tests::basic::returns_unit::pre]:
    Source: 'src/lib.rs', lines 25:4-25:23 -/
@[reducible]
def basic.returns_unit.pre (x : Std.U32) : RustM Bool := do
  ok (x < 10#u32)

/-- [hax_tests::basic::returns_unit::post]:
    Source: 'src/lib.rs', lines 26:4-26:24 -/
@[reducible]
def basic.returns_unit.post (x : Std.U32) (_ : Unit) : RustM Bool := do
  ok true

def basic.returns_unit.spec (x : Std.U32) : Prop :=
  (basic.returns_unit.pre x).holds →
  ⦃ ⌜ True ⌝ ⦄
  basic.returns_unit x
  ⦃ ⇓ res => ⌜ (basic.returns_unit.post x res).holds ⌝ ⦄


/-- [hax_tests::basic::no_args::post]:
    Source: 'src/lib.rs', lines 30:4-30:24 -/
@[reducible] def basic.no_args.post (_ : Unit) : RustM Bool := do
               ok true

def basic.no_args.spec : Prop :=
  ⦃ ⌜ True ⌝ ⦄
  basic.no_args
  ⦃ ⇓ res => ⌜ (basic.no_args.post res).holds ⌝ ⦄


/-- [hax_tests::basic::block_in_requires::pre]:
    Source: 'src/lib.rs', lines 37:4-37:46 -/
@[reducible]
def basic.block_in_requires.pre (x : Std.U32) : RustM Bool := do
  ok (x > 10#u32)

def basic.block_in_requires.spec (x : Std.U32) : Prop :=
  (basic.block_in_requires.pre x).holds →
  ⦃ ⌜ True ⌝ ⦄
  basic.block_in_requires x
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [hax_tests::basic::returns_pair::post]:
    Source: 'src/lib.rs', lines 43:4-43:41 -/
@[reducible]
def basic.returns_pair.post
  (x : Std.U32) (p : (Std.U32 × Std.U32)) : RustM Bool := do
  let (a, b) := p
  if a = x
  then ok (b = x)
  else ok false

def basic.returns_pair.spec (x : Std.U32) : Prop :=
  ⦃ ⌜ True ⌝ ⦄
  basic.returns_pair x
  ⦃ ⇓ res => ⌜ (basic.returns_pair.post x res).holds ⌝ ⦄


/-- [hax_tests::extra_args::generic::pre]:
    Source: 'src/lib.rs', lines 54:4-54:31 -/
@[reducible]
def extra_args.generic.pre (N : Std.U32) (x : Std.U32) : RustM Bool := do
  if 0#u32 < x
  then ok (x < N)
  else ok false

/-- [hax_tests::extra_args::generic::post]:
    Source: 'src/lib.rs', lines 55:4-55:35 -/
@[reducible]
def extra_args.generic.post
  (N : Std.U32) (x : Std.U32) (result : Std.U32) : RustM Bool := do
  ok (result < N)

def extra_args.generic.spec (N : Std.U32) (x : Std.U32) : Prop :=
  (extra_args.generic.pre N x).holds →
  ⦃ ⌜ True ⌝ ⦄
  extra_args.generic N x
  ⦃ ⇓ res => ⌜ (extra_args.generic.post N x res).holds ⌝ ⦄


/-- [hax_tests::extra_args::traits::pre]:
    Source: 'src/lib.rs', lines 71:4-71:45 -/
@[reducible]
def extra_args.traits.pre
  {T : Type} (ValInst : extra_args.Val T) (t : T) (x : Std.U32) :
  RustM Bool
  := do
  let i ← ValInst.value t
  if i < 1000#u32
  then ok (x < 1000#u32)
  else ok false

/-- [hax_tests::extra_args::traits::post]:
    Source: 'src/lib.rs', lines 72:4-72:38 -/
@[reducible]
def extra_args.traits.post
  {T : Type} (ValInst : extra_args.Val T) (t : T) (x : Std.U32)
  (result : Std.U32) :
  RustM Bool
  := do
  ok (result < 2000#u32)

def extra_args.traits.spec {T : Type} (ValInst : extra_args.Val T) (t : T)
  (x : Std.U32) : Prop :=
  (extra_args.traits.pre ValInst t x).holds →
  ⦃ ⌜ True ⌝ ⦄
  extra_args.traits ValInst t x
  ⦃ ⇓ res => ⌜ (extra_args.traits.post ValInst t x res).holds ⌝ ⦄


/-- [hax_tests::future::incr::pre]:
    Source: 'src/lib.rs', lines 82:4-82:26 -/
@[reducible]
def future.incr.pre (x : Std.U32) : RustM Bool := do
  ok (x < 1000#u32)

/-- [hax_tests::future::incr::post]:
    Source: 'src/lib.rs', lines 83:4-83:41 -/
@[reducible]
def future.incr.post (x : Std.U32) (x_future : Std.U32) : RustM Bool := do
  let i ← x + 1#u32
  ok (x_future = i)

def future.incr.spec (x : Std.U32) : Prop :=
  (future.incr.pre x).holds →
  ⦃ ⌜ True ⌝ ⦄
  future.incr x
  ⦃ ⇓ res => ⌜ (future.incr.post x res).holds ⌝ ⦄


/-- [hax_tests::future::incr_i::pre]:
    Source: 'src/lib.rs', lines 88:4-88:47 -/
@[reducible]
def future.incr_i.pre (x : Slice Std.U32) (i : Std.Usize) : RustM Bool := do
  let i1 ← core.slice.Slice.len x
  if i < i1
  then let i2 ← Slice.index_usize x i
       ok (i2 < core.num.U32.MAX)
  else ok false

/-- [hax_tests::future::incr_i::post]:
    Source: 'src/lib.rs', lines 89:4-91:31 -/
@[reducible]
def future.incr_i.post
  (x : Slice Std.U32) (i : Std.Usize) (x_future : Slice Std.U32) :
  RustM Bool
  := do
  let i1 ← Slice.index_usize x_future i
  let i2 ← Slice.index_usize x i
  let i3 ← i2 + 1#u32
  ok (i1 = i3)

def future.incr_i.spec (x : Slice Std.U32) (i : Std.Usize) : Prop :=
  (future.incr_i.pre x i).holds →
  ⦃ ⌜ True ⌝ ⦄
  future.incr_i x i
  ⦃ ⇓ res => ⌜ (future.incr_i.post x i res).holds ⌝ ⦄


/-- [hax_tests::future::swap_and_add::pre]:
    Source: 'src/lib.rs', lines 96:4-96:39 -/
@[reducible]
def future.swap_and_add.pre (x : Std.U32) (y : Std.U32) : RustM Bool := do
  if x < 1000#u32
  then ok (y < 1000#u32)
  else ok false

/-- [hax_tests::future::swap_and_add::post]:
    Source: 'src/lib.rs', lines 99:4-99:75 -/
@[reducible]
def future.swap_and_add.post
  (x : Std.U32) (y : Std.U32) (t : (Std.U32 × Std.U32 × Std.U32)) :
  RustM Bool
  := do
  let (r, x_future, y_future) := t
  if y_future = x
  then if x_future = y
       then let i ← x + y
            ok (r = i)
       else ok false
  else ok false

def future.swap_and_add.spec (x : Std.U32) (y : Std.U32) : Prop :=
  (future.swap_and_add.pre x y).holds →
  ⦃ ⌜ True ⌝ ⦄
  future.swap_and_add x y
  ⦃ ⇓ res => ⌜ (future.swap_and_add.post x y res).holds ⌝ ⦄


/-- [hax_tests::implicit_generics::nothing::post]:
    Source: 'src/lib.rs', lines 150:4-150:24 -/
@[reducible]
def implicit_generics.nothing.post
  {T : Type} (k : Std.Usize) (o : core.option.Option T) : RustM Bool := do
  ok true

def implicit_generics.nothing.spec (T : Type) (k : Std.Usize) : Prop :=
  ⦃ ⌜ True ⌝ ⦄
  implicit_generics.nothing T k
  ⦃ ⇓ res => ⌜ (implicit_generics.nothing.post k res).holds ⌝ ⦄


/-- [hax_tests::implicit_generics::of_fst::post]:
    Source: 'src/lib.rs', lines 156:4-156:24 -/
@[reducible]
def implicit_generics.of_fst.post
  {T : Type} {N : Std.Usize} (t : T) (p : implicit_generics.Pair T N) :
  RustM Bool
  := do
  ok true

def implicit_generics.of_fst.spec {T : Type} (N : Std.Usize) (t : T) : Prop :=
  ⦃ ⌜ True ⌝ ⦄
  implicit_generics.of_fst N t
  ⦃ ⇓ res => ⌜ (implicit_generics.of_fst.post t res).holds ⌝ ⦄


/-- [hax_tests::implicit_generics::empty::post]:
    Source: 'src/lib.rs', lines 162:4-162:24 -/
@[reducible]
def implicit_generics.empty.post
  {T : Type} {N : Std.Usize} (k : Std.Usize)
  (o : core.option.Option (implicit_generics.Pair T N)) :
  RustM Bool
  := do
  ok true

def implicit_generics.empty.spec (T : Type) (N : Std.Usize) (k : Std.Usize)
  : Prop :=
  ⦃ ⌜ True ⌝ ⦄
  implicit_generics.empty T N k
  ⦃ ⇓ res => ⌜ (implicit_generics.empty.post k res).holds ⌝ ⦄


/-- [hax_tests::unit_args::named::post]:
    Source: 'src/lib.rs', lines 194:4-194:36 -/
@[reducible]
def unit_args.named.post (_ : Unit) (result : Std.Usize) : RustM Bool := do
  ok (result = 0#usize)

def unit_args.named.spec (_ : Unit) : Prop :=
  ⦃ ⌜ True ⌝ ⦄
  unit_args.named ()
  ⦃ ⇓ res => ⌜ (unit_args.named.post () res).holds ⌝ ⦄


/-- [hax_tests::unit_args::before_other::pre]:
    Source: 'src/lib.rs', lines 200:4-200:24 -/
@[reducible]
def unit_args.before_other.pre (_ : Unit) (y : Std.U32) : RustM Bool := do
  ok (y < 100#u32)

/-- [hax_tests::unit_args::before_other::post]:
    Source: 'src/lib.rs', lines 201:4-201:36 -/
@[reducible]
def unit_args.before_other.post
  (_ : Unit) (y : Std.U32) (result : Std.U32) : RustM Bool := do
  ok (result = y)

def unit_args.before_other.spec (_ : Unit) (y : Std.U32) : Prop :=
  (unit_args.before_other.pre () y).holds →
  ⦃ ⌜ True ⌝ ⦄
  unit_args.before_other () y
  ⦃ ⇓ res => ⌜ (unit_args.before_other.post () y res).holds ⌝ ⦄


/-- [hax_tests::reserved_names::foo::pre]:
    Source: 'src/lib.rs', lines 256:4-256:24 -/
@[reducible]
def reserved_names.foo.pre (x : Std.U32) : RustM Bool := do
  ok (x < 100#u32)

/-- [hax_tests::reserved_names::foo::post]:
    Source: 'src/lib.rs', lines 257:4-257:40 -/
@[reducible]
def reserved_names.foo.post (x : Std.U32) (result : Std.U32) : RustM Bool := do
  let i ← x + 1#u32
  ok (result = i)

def reserved_names.foo.spec (x : Std.U32) : Prop :=
  (reserved_names.foo.pre x).holds →
  ⦃ ⌜ True ⌝ ⦄
  reserved_names.foo x
  ⦃ ⇓ res => ⌜ (reserved_names.foo.post x res).holds ⌝ ⦄


/-- [hax_tests::const_generic_ty::{hax_tests::const_generic_ty::MyStruct<N>}::build::pre]:
    Source: 'src/lib.rs', lines 125:8-125:28 -/
@[reducible]
def const_generic_ty.MyStruct.build.pre
  (N : Std.Usize) (k : Std.Usize) : RustM Bool := do
  ok (k < 100#usize)

/-- [hax_tests::const_generic_ty::{hax_tests::const_generic_ty::MyStruct<N>}::build::post]:
    Source: 'src/lib.rs', lines 126:8-126:28 -/
@[reducible]
def const_generic_ty.MyStruct.build.post
  {N : Std.Usize} (k : Std.Usize) (ms : const_generic_ty.MyStruct N) :
  RustM Bool
  := do
  ok true

def const_generic_ty.MyStruct.build.spec (N : Std.Usize) (k : Std.Usize)
  : Prop :=
  (const_generic_ty.MyStruct.build.pre N k).holds →
  ⦃ ⌜ True ⌝ ⦄
  const_generic_ty.MyStruct.build N k
  ⦃ ⇓ res => ⌜ (const_generic_ty.MyStruct.build.post k res).holds ⌝ ⦄


/-- [hax_tests::const_generic_ty::{hax_tests::const_generic_ty::MyStruct<N>}::get::post]:
    Source: 'src/lib.rs', lines 132:8-132:28 -/
@[reducible]
def const_generic_ty.MyStruct.get.post
  {N : Std.Usize} (self_ : const_generic_ty.MyStruct N) (i : Std.Usize) :
  RustM Bool
  := do
  ok true

def const_generic_ty.MyStruct.get.spec {N : Std.Usize}
  (self : const_generic_ty.MyStruct N) : Prop :=
  ⦃ ⌜ True ⌝ ⦄
  const_generic_ty.MyStruct.get self
  ⦃ ⇓ res => ⌜ (const_generic_ty.MyStruct.get.post self res).holds ⌝
  ⦄


/-- [hax_tests::unit_args::{impl hax_tests::unit_args::Size for ()}::len::post]:
    Source: 'src/lib.rs', lines 188:8-188:28 -/
@[reducible]
def Tuple.Insts.Hax_testsUnit_argsSize.len.post
  (_ : Unit) (i : Std.Usize) : RustM Bool := do
  ok true

def Tuple.Insts.Hax_testsUnit_argsSize.len.spec (_ : Unit) : Prop :=
  ⦃ ⌜ True ⌝ ⦄
  Tuple.Insts.Hax_testsUnit_argsSize.len ()
  ⦃ ⇓ res =>
  ⌜ (Tuple.Insts.Hax_testsUnit_argsSize.len.post () res).holds ⌝ ⦄


/-- [hax_tests::supertraits::B::provided::pre]:
    Source: 'src/lib.rs', lines 215:4-215:26 -/
@[reducible]
def supertraits.B.provided.pre
  {Self_ : Type} (AInst : supertraits.A Self_) (BInst : supertraits.B Self_)
  (self_ : Self_) :
  RustM Bool
  := do
  let i ← AInst.a self_
  ok (i < 100#usize)

/-- [hax_tests::supertraits::B::provided::post]:
    Source: 'src/lib.rs', lines 215:4-215:26 -/
@[reducible]
def supertraits.B.provided.post
  {Self_ : Type} (AInst : supertraits.A Self_) (BInst : supertraits.B Self_)
  (self_ : Self_) (res : Std.Usize) :
  RustM Bool
  := do
  let i ← AInst.a self_
  ok (res = i)

def
  supertraits.B.provided.default.spec {Self : Type} (BInst : supertraits.B
                                     Self) (self : Self) : Prop :=
  (supertraits.B.provided.pre BInst.AInst BInst self).holds →
  ⦃ ⌜ True ⌝ ⦄
  supertraits.B.provided.default BInst self
  ⦃ ⇓ res =>
  ⌜ (supertraits.B.provided.post BInst.AInst BInst self res).holds ⌝ ⦄


/-- [hax_tests::supertraits::C::provided_c::pre]:
    Source: 'src/lib.rs', lines 228:4-228:26 -/
@[reducible]
def supertraits.C.provided_c.pre
  {Self_ : Type} (BInst : supertraits.B Self_) (CInst : supertraits.C Self_)
  (self_ : Self_) :
  RustM Bool
  := do
  let i ← BInst.AInst.a self_
  ok (i < 100#usize)

/-- [hax_tests::supertraits::C::provided_c::post]:
    Source: 'src/lib.rs', lines 228:4-228:26 -/
@[reducible]
def supertraits.C.provided_c.post
  {Self_ : Type} (BInst : supertraits.B Self_) (CInst : supertraits.C Self_)
  (self_ : Self_) (res : Std.Usize) :
  RustM Bool
  := do
  let i ← BInst.AInst.a self_
  ok (res = i)

def
  supertraits.C.provided_c.default.spec {Self : Type} (CInst : supertraits.C
                                       Self) (self : Self) : Prop :=
  (supertraits.C.provided_c.pre CInst.BInst CInst self).holds →
  ⦃ ⌜ True ⌝ ⦄
  supertraits.C.provided_c.default CInst self
  ⦃ ⇓ res =>
  ⌜ (supertraits.C.provided_c.post CInst.BInst CInst self res).holds ⌝ ⦄

end hax_tests
