-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [hax_tests]: type definitions
import Aeneas
import CoreModels
import HaxTests.Extraction.TypesExternal
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace hax_tests

/-- Trait declaration: [hax_tests::specs::arguments::Size]
    Source: 'src/specs/arguments.rs', lines 5:0-7:1 -/
structure specs.arguments.Size (Self : Type) where
  len : Self → RustM Std.Usize

/-- [hax_tests::specs::arguments::Point]
    Source: 'src/specs/arguments.rs', lines 30:0-33:1
    Visibility: public -/
structure specs.arguments.Point where
  x : Std.U32
  y : Std.U32

/-- [hax_tests::specs::arguments::Shape]
    Source: 'src/specs/arguments.rs', lines 42:0-45:1
    Visibility: public -/
@[discriminant isize]
inductive specs.arguments.Shape where
| Dot : specs.arguments.Shape
| Line : Std.U32 → specs.arguments.Shape

/-- [hax_tests::specs::contracts::_#18::requires::closure]
    Source: 'src/specs/contracts.rs', lines 85:18-85:50 -/
@[reducible]
def specs.contracts.__18.requires.closure := Std.U32

/-- [hax_tests::specs::contracts::_#19::ensures::closure]
    Source: 'src/specs/contracts.rs', lines 86:26-86:46 -/
@[reducible]
def specs.contracts.__19.ensures.closure := Std.U32

/-- Trait declaration: [hax_tests::specs::generics::Val]
    Source: 'src/specs/generics.rs', lines 16:0-18:1 -/
structure specs.generics.Val (Self : Type) where
  value : Self → RustM Std.U32

/-- [hax_tests::specs::generics::Wrapper]
    Source: 'src/specs/generics.rs', lines 42:0-42:21 -/
@[reducible]
def specs.generics.Wrapper (T : Type) := T

/-- Trait declaration: [hax_tests::specs::generics::Producer]
    Source: 'src/specs/generics.rs', lines 55:0-58:1 -/
structure specs.generics.Producer (Self : Type) (Self_Out : Type) where
  produce : Self → RustM Self_Out

/-- [hax_tests::specs::generics::MyStruct]
    Source: 'src/specs/generics.rs', lines 74:0-76:1
    Visibility: public -/
structure specs.generics.MyStruct (N : Std.Usize) where
  cap : Std.Usize

/-- [hax_tests::specs::generics::Pair]
    Source: 'src/specs/generics.rs', lines 95:0-97:1
    Visibility: public -/
structure specs.generics.Pair (T : Type) (N : Std.Usize) where
  fst : T

/-- [hax_tests::specs::mutable_borrows::Counter]
    Source: 'src/specs/mutable_borrows.rs', lines 42:0-44:1
    Visibility: public -/
structure specs.mutable_borrows.Counter where
  count : Std.U32

end hax_tests
