-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [hax_tests]: type definitions
import Aeneas
import CoreModels
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace hax_tests

/-- Trait declaration: [hax_tests::standalone::arguments::Size]
    Source: 'src/standalone/arguments.rs', lines 5:0-7:1 -/
structure standalone.arguments.Size (Self : Type) where
  len : Self → RustM Std.Usize

/-- Trait declaration: [hax_tests::standalone::generics::Val]
    Source: 'src/standalone/generics.rs', lines 16:0-18:1 -/
structure standalone.generics.Val (Self : Type) where
  value : Self → RustM Std.U32

/-- [hax_tests::standalone::generics::MyStruct]
    Source: 'src/standalone/generics.rs', lines 42:0-44:1
    Visibility: public -/
structure standalone.generics.MyStruct (N : Std.Usize) where
  cap : Std.Usize

/-- [hax_tests::standalone::generics::Pair]
    Source: 'src/standalone/generics.rs', lines 63:0-65:1
    Visibility: public -/
structure standalone.generics.Pair (T : Type) (N : Std.Usize) where
  fst : T

/-- Trait declaration: [hax_tests::standalone::traits::A]
    Source: 'src/standalone/traits.rs', lines 3:0-5:1
    Visibility: public -/
structure standalone.traits.A (Self : Type) where
  a : Self → RustM Std.Usize

/-- Trait declaration: [hax_tests::standalone::traits::B]
    Source: 'src/standalone/traits.rs', lines 8:0-16:1
    Visibility: public -/
structure standalone.traits.B (Self : Type) where
  AInst : standalone.traits.A Self
  b : Self → RustM Std.Usize
  provided : Self → RustM Std.Usize

/-- Trait declaration: [hax_tests::standalone::traits::C]
    Source: 'src/standalone/traits.rs', lines 21:0-27:1
    Visibility: public -/
structure standalone.traits.C (Self : Type) where
  BInst : standalone.traits.B Self
  provided_c : Self → RustM Std.Usize

/-- Trait declaration: [hax_tests::standalone::traits::G]
    Source: 'src/standalone/traits.rs', lines 30:0-32:1
    Visibility: public -/
structure standalone.traits.G (Self : Type) (T : Type) where
  g : Self → RustM T

/-- Trait declaration: [hax_tests::standalone::traits::H]
    Source: 'src/standalone/traits.rs', lines 36:0-40:1
    Visibility: public -/
structure standalone.traits.H (Self : Type) (T : Type) where
  GInst : standalone.traits.G Self T
  provided_h : Self → RustM T

/-- Trait declaration: [hax_tests::standalone::traits::D]
    Source: 'src/standalone/traits.rs', lines 46:0-50:1
    Visibility: public -/
structure standalone.traits.D (Self : Type) where
  required : Self → Std.U32 → RustM Std.U32

end hax_tests
