-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [hax_tests]: type definitions
import Aeneas
import CoreModels
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace hax_tests

/-- Trait declaration: [hax_tests::extra_args::Val]
    Source: 'src/lib.rs', lines 61:4-63:5 -/
structure extra_args.Val (Self : Type) where
  value : Self → RustM Std.U32

/-- [hax_tests::const_generic_ty::MyStruct]
    Source: 'src/lib.rs', lines 117:4-119:5
    Visibility: public -/
structure const_generic_ty.MyStruct (N : Std.Usize) where
  cap : Std.Usize

/-- [hax_tests::implicit_generics::Pair]
    Source: 'src/lib.rs', lines 143:4-145:5
    Visibility: public -/
structure implicit_generics.Pair (T : Type) (N : Std.Usize) where
  fst : T

/-- Trait declaration: [hax_tests::unit_args::Size]
    Source: 'src/lib.rs', lines 181:4-183:5 -/
structure unit_args.Size (Self : Type) where
  len : Self → RustM Std.Usize

/-- Trait declaration: [hax_tests::supertraits::A]
    Source: 'src/lib.rs', lines 211:4-213:5
    Visibility: public -/
structure supertraits.A (Self : Type) where
  a : Self → RustM Std.Usize

/-- Trait declaration: [hax_tests::supertraits::B]
    Source: 'src/lib.rs', lines 216:4-224:5
    Visibility: public -/
structure supertraits.B (Self : Type) where
  AInst : supertraits.A Self
  b : Self → RustM Std.Usize
  provided : Self → RustM Std.Usize

/-- Trait declaration: [hax_tests::supertraits::C]
    Source: 'src/lib.rs', lines 229:4-235:5
    Visibility: public -/
structure supertraits.C (Self : Type) where
  BInst : supertraits.B Self
  provided_c : Self → RustM Std.Usize

/-- Trait declaration: [hax_tests::supertraits::G]
    Source: 'src/lib.rs', lines 238:4-240:5
    Visibility: public -/
structure supertraits.G (Self : Type) (T : Type) where
  g : Self → RustM T

/-- Trait declaration: [hax_tests::supertraits::H]
    Source: 'src/lib.rs', lines 244:4-248:5
    Visibility: public -/
structure supertraits.H (Self : Type) (T : Type) where
  GInst : supertraits.G Self T
  provided_h : Self → RustM T

end hax_tests
