// THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS-LEAN-CHECKER
// Crate: aggregates_basic

pub fn mk_tuple_model(x1: u32, x2: u32) -> (u32, u32) {
    (x1, x2)
}

pub fn mk_pair_model(x1: u32, x2: u32) -> Pair {
    Pair { x: x1, y: x2 }
}
