// AUTO-GENERATED by `meta-harness --regen-models`. DO NOT EDIT.
// Each fn below was emitted by `aeneas-check --rust-model` for the
// named fixture, filtered through `meta-harness` for scalar-shape sig
// and body, prefixed with the fixture name, and verified via `cargo
// check`. Fns whose bodies failed compilation were dropped.
//
// Re-generate with:
//   meta-harness --regen-models <out-path> --sweep <cert-dir>
//
// This file is `include!()`-d inside `pub mod model { ... }` in
// `src/lib.rs`, so inner attributes are not allowed here. Lints are
// silenced via the outer `pub mod model`'s attrs (in lib.rs).


// ---- arrays ----
pub fn arrays_take_array_model(x1: [u32; 2]) -> () {
    ()
}
