#!/usr/bin/env bash
# Runs the proof scenario `hax-tests` of the hax test crate `tests/hax` (see
# `tests/hax/hax.toml`) with `cargo hax extract`, using the aeneas and charon of
# this checkout, and builds the extracted Lean code.
#
# Usage:
#   test-hax.sh extract HAX_DIR
#       Extract `tests/hax` to Lean, overwriting the committed outputs.
#       `cargo hax` is taken from PATH; the crate uses the `hax-lib`
#       of HAX_DIR instead of the one from crates.io. Expects `bin/aeneas`
#       and `charon/bin/charon` to exist.
#   test-hax.sh verify HAX_DIR
#       Build the extracted Lean code (`tests/hax/proofs/hax-tests/lean`)
#       against the aeneas Lean library of this checkout and the hax Lean
#       library of HAX_DIR. Needs `lake` on PATH.
#
# HAX_DIR is a checkout of https://github.com/cryspen/hax. It is not modified.
set -euo pipefail

usage() {
    sed -n '/^# Usage:/,/^set /p' "$0" | sed '$d; s/^# \{0,1\}//' >&2
    exit 1
}

root="$(cd "$(dirname "$0")/.." && pwd)"
tests="$root/tests/hax"
scenario="hax-tests"
lean="$tests/proofs/$scenario/lean"

check_hax_dir() {
    [ -d "$1/hax-lib/proof-libs/lean" ] \
        || { echo "error: $1 is not a checkout of hax" >&2; exit 1; }
}

# Warn when the `cargo hax` on PATH is not the version of HAX_DIR: the
# extraction and the libraries would then come from different versions of hax.
check_cargo_hax_version() {
    local hax="$1" expected actual
    expected="$(sed -n '/^\[workspace.package\]/,/^\[/s/^version = "\(.*\)"/\1/p' "$hax/Cargo.toml")"
    actual="$(cargo hax --version | sed -n 's/^version=//p')"
    if [ "$expected" != "$actual" ]; then
        echo "warning: \`cargo hax\` is version $actual but $hax is version $expected" >&2
    fi
}

extract() {
    [ $# -eq 1 ] || usage
    local hax
    hax="$(realpath "$1")"
    check_hax_dir "$hax"
    check_cargo_hax_version "$hax"

    # hax expects `charon-driver` next to `charon`.
    local exe
    for exe in "$root/bin/aeneas" "$root/charon/bin/charon" "$root/charon/bin/charon-driver"; do
        [ -x "$exe" ] || { echo "error: $exe is not an executable" >&2; exit 1; }
    done

    # Use the `hax-lib` of HAX_DIR, which matches its `cargo hax`. Written as a
    # cargo config rather than in the crate's manifest, since the path is
    # machine-specific.
    mkdir -p "$tests/.cargo"
    cat > "$tests/.cargo/config.toml" <<EOF
# Generated by scripts/test-hax.sh.
[patch.crates-io]
hax-lib = { path = "$hax/hax-lib" }
EOF

    # Cargo ignores the patch, with a mere warning, when the version of HAX_DIR
    # does not satisfy the `hax-lib` requirement of `tests/hax/Cargo.toml`, and
    # falls back to crates.io. Resolve from scratch (the lockfile may predate
    # the patch) and check that the patch was used.
    rm -f "$tests/Cargo.lock"
    (cd "$tests" && cargo generate-lockfile --quiet)
    local pkgid
    pkgid="$(cd "$tests" && cargo pkgid hax-lib)"
    case "$pkgid" in
        "path+file://$hax/hax-lib#"*) ;;
        *)
            echo "error: \`hax-lib\` resolves to $pkgid instead of $hax/hax-lib:" \
                "update the \`hax-lib\` requirement of tests/hax/Cargo.toml to the version of $hax" >&2
            exit 1
            ;;
    esac

    (cd "$tests" && cargo hax extract "$scenario")
}

verify() {
    [ $# -eq 1 ] || usage
    local hax
    hax="$(realpath "$1")"
    check_hax_dir "$hax"
    ln -sfn "$hax/hax-lib/proof-libs/lean" "$lean/.hax-lean"
    cp "$root/backends/lean/lean-toolchain" "$lean/lean-toolchain"
    (cd "$lean" && lake update && lake exe cache get && lake build)
}

[ $# -ge 1 ] || usage
command="$1"
shift
case "$command" in
    extract) extract "$@" ;;
    verify) verify "$@" ;;
    *) usage ;;
esac
