-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [external_names_split]: function definitions
import Aeneas
import ExternalNamesSplit.Types
import ExternalNamesModel
open Aeneas Aeneas.Std RustM ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace external_names_split

/-- [external_names_split::incr_twice]:
    Source: 'tests/src/external-names-split.rs', lines 18:0-20:1 -/
def incr_twice
  (c : ExternalNamesModel.Counter) : RustM ExternalNamesModel.Counter := do
  let c1 ← ExternalNamesModel.incr c
  ExternalNamesModel.incr c1

end external_names_split
