-- GENERATED BY semdiff gen_driver.py -- do not edit by hand
-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [selftest]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace selftest

/-- [selftest::test_ok]: loop body 0:
    Source: '/private/var/folders/2d/hymfjh9j0mg_v4wx9nqk7w800000gn/T/semdiff-e2e-96018/selftest.rs', lines 6:4-6:51
    Visibility: public -/
@[rust_loop_body]
def test_ok_loop.body
  (x : Std.U32) (i : Std.U32) :
  Result (ControlFlow (Std.U32 × Std.U32) Std.U32)
  := do
  if i < 5#u32
  then
    let x1 ← lift (core.num.U32.wrapping_add x 1#u32)
    let i1 ← i + 1#u32
    ok (cont (x1, i1))
  else ok (done x)

/-- [selftest::test_ok]: loop 0:
    Source: '/private/var/folders/2d/hymfjh9j0mg_v4wx9nqk7w800000gn/T/semdiff-e2e-96018/selftest.rs', lines 6:4-6:51
    Visibility: public -/
@[rust_loop]
def test_ok_loop (x : Std.U32) (i : Std.U32) : Result Std.U32 := do
  loop
    (fun (x1, i1) => test_ok_loop.body x1 i1)
    (x, i)

/-- [selftest::test_ok]:
    Source: '/private/var/folders/2d/hymfjh9j0mg_v4wx9nqk7w800000gn/T/semdiff-e2e-96018/selftest.rs', lines 2:0-8:1
    Visibility: public -/
def test_ok : Result Unit := do
  let base ← test_ok_loop 3#u32 0#u32
  massert (base = 8#u32)

/-- [selftest::test_fail]:
    Source: '/private/var/folders/2d/hymfjh9j0mg_v4wx9nqk7w800000gn/T/semdiff-e2e-96018/selftest.rs', lines 9:0-12:1
    Visibility: public -/
def test_fail : Result Unit := do
  let n ← lift (core.num.U32.wrapping_mul 2#u32 3#u32)
  massert (n = 999#u32)

/-- [selftest::test_overflow]:
    Source: '/private/var/folders/2d/hymfjh9j0mg_v4wx9nqk7w800000gn/T/semdiff-e2e-96018/selftest.rs', lines 13:0-17:1
    Visibility: public -/
def test_overflow : Result Unit := do
  let _ ← core.num.U32.MAX + 1#u32
  ok ()

end selftest

/- ===== semdiff oracle appendix (generated) ===== -/
private def semdiffClassify {α : Type} (r : Result α) : String :=
  match r with
  | .ok _ => "OK"
  | .fail .assertionFailure    => "FAIL:assertionFailure"
  | .fail .integerOverflow     => "FAIL:integerOverflow"
  | .fail .divisionByZero      => "FAIL:divisionByZero"
  | .fail .arrayOutOfBounds    => "FAIL:arrayOutOfBounds"
  | .fail .maximumSizeExceeded => "FAIL:maximumSizeExceeded"
  | .fail .panic               => "FAIL:panic"
  | .fail .undef               => "FAIL:undef"
  | .div => "DIV"

open selftest
#eval IO.println s!"SEMDIFF|test_ok|{semdiffClassify test_ok}"
#eval IO.println s!"SEMDIFF|test_fail|{semdiffClassify test_fail}"
#eval IO.println s!"SEMDIFF|test_overflow|{semdiffClassify test_overflow}"
