import AeneasCheck.Pure.Pretty
import AeneasCheck.Translate.Driver

/-!
Lean source-code backend: render `Pure.TranslatedCrate` as Lean
source that compiles against `backends/lean/Aeneas/Std`.
-/

namespace AeneasCheck.Backends

open AeneasCheck Pure Translate

def emitHeader (crateName : String) : String :=
  s!"-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS-LEAN-CHECKER" ++ "\n" ++
  s!"-- Crate: {crateName}" ++ "\n" ++
  "import Aeneas.Std" ++ "\n" ++
  "open Aeneas (Std)" ++ "\n\n"

def emitDecl (d : Decl) : String := d.toLean ++ "\n"

def emitTranslatedCrate (crateName : String) (tc : TranslatedCrate) : String :=
  let decls := String.intercalate "\n" (tc.decls.toList.map emitDecl)
  emitHeader crateName ++ decls

end AeneasCheck.Backends
