import AeneasCheck.Pure.Pretty
import AeneasCheck.Translate.Driver

/-!
Lean source-code backend: render `Pure.TranslatedCrate` as Lean
source that compiles against `backends/lean/Aeneas/Std`.

M9.0a polish: emit the same shape as `aeneas -backend lean` —
`import Aeneas`, the full `open` line, the standard linter / heartbeat
options, a top-level `namespace <crate>` block, and per-function
`/-- ... Source: ..., lines N:M-P:Q -/` docstrings. The body is
wrapped in `do …` to match the standard backend's monadic surface.

Byte-identity with the standard backend is the M9 convergence goal;
the body content (binops, calls) still uses the M7 placeholder until
M9.1+ adds the relevant cert events.
-/

namespace AeneasCheck.Backends

open AeneasCheck Pure Translate

/-- The "crate" segment of a qualified Rust name `crate::a::b` —
    everything up to the first `::`. Used to group decls into one
    `namespace …` block per crate. -/
def crateOf (qualified : String) : String :=
  (qualified.splitOn "::").headD qualified

/-- The header emitted at the top of every generated file. Matches the
    standard Aeneas backend's preamble so a downstream verifier can
    swap one output for the other. -/
def emitHeader (crateName : String) : String :=
  "-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS-LEAN-CHECKER\n" ++
  s!"-- [{crateName}]\n" ++
  "import Aeneas\n" ++
  "open Aeneas Aeneas.Std Result ControlFlow Error\n" ++
  "set_option linter.dupNamespace false\n" ++
  "set_option linter.hashCommand false\n" ++
  "set_option linter.unusedVariables false\n\n" ++
  "/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/\n" ++
  "set_option maxHeartbeats 1000000\n\n" ++
  "/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/\n" ++
  "set_option maxRecDepth 2048\n\n"

/-- Render one `def …` in monadic style, preceded by its docstring. -/
def emitDecl (d : Decl) : String := d.toLean ++ "\n"

/-- M9.5b: render one `structure Foo where …` block. -/
def emitStruct (sd : StructDecl) : String := sd.toLean ++ "\n"

/-- M9.5d: render one `inductive Foo where …` block. -/
def emitEnum (ed : EnumDecl) : String := ed.toLean ++ "\n"

/-- M9.5l: render one `structure <Trait> (Self : Type) where …` block. -/
def emitTraitDecl (td : TraitDecl) : String := td.toLean ++ "\n"

/-- M9.5l: render one `@[reducible] def <Impl> : <Trait> <Self> := { … }` block. -/
def emitTraitImpl (ti : TraitImpl) : String := ti.toLean ++ "\n"

/-- Group function decls into namespace blocks keyed by their crate
    prefix. Order within each group is preserved (cert iteration
    order). -/
private def groupByCrate (decls : Array Decl) : Array (String × Array Decl) :=
  Id.run do
    let mut order : Array String := #[]
    let mut buckets : Std.HashMap String (Array Decl) := {}
    for d in decls do
      let c := crateOf d.qualifiedName
      if !buckets.contains c then
        order := order.push c
        buckets := buckets.insert c #[]
      buckets := buckets.insert c ((buckets.getD c #[]).push d)
    return order.map fun c => (c, buckets.getD c #[])

/-- M9.5b: same grouping for struct decls. -/
private def groupStructsByCrate (sds : Array StructDecl) :
    Std.HashMap String (Array StructDecl) :=
  Id.run do
    let mut buckets : Std.HashMap String (Array StructDecl) := {}
    for sd in sds do
      let c := crateOf sd.qualifiedName
      buckets := buckets.insert c ((buckets.getD c #[]).push sd)
    return buckets

/-- M9.5d: same grouping for enum decls. -/
private def groupEnumsByCrate (eds : Array EnumDecl) :
    Std.HashMap String (Array EnumDecl) :=
  Id.run do
    let mut buckets : Std.HashMap String (Array EnumDecl) := {}
    for ed in eds do
      let c := crateOf ed.qualifiedName
      buckets := buckets.insert c ((buckets.getD c #[]).push ed)
    return buckets

/-- M9.5l: same grouping for trait decls. -/
private def groupTraitDeclsByCrate (tds : Array TraitDecl) :
    Std.HashMap String (Array TraitDecl) :=
  Id.run do
    let mut buckets : Std.HashMap String (Array TraitDecl) := {}
    for td in tds do
      let c := crateOf td.qualifiedName
      buckets := buckets.insert c ((buckets.getD c #[]).push td)
    return buckets

/-- M9.5l: same grouping for trait impls. -/
private def groupTraitImplsByCrate (tis : Array TraitImpl) :
    Std.HashMap String (Array TraitImpl) :=
  Id.run do
    let mut buckets : Std.HashMap String (Array TraitImpl) := {}
    for ti in tis do
      let c := crateOf ti.qualifiedName
      buckets := buckets.insert c ((buckets.getD c #[]).push ti)
    return buckets

/-- M9.5l / M9.5o: a function decl is an "impl method body" when its
    `name` appears as the `body` of some trait impl's method entry.
    Two shape conventions arise: `<Self>.Insts.<Crate><Trait>.<m>`
    (concrete-Self impls — M9.5l) and `<Trait>.Blanket.<m>` (blanket
    impls — M9.5o). The membership check is robust to both forms.

    The check also looks at the qualifiedName for cases where the
    name override hasn't been applied (defensive — the translator
    always applies it before reaching this point). -/
private def isImplMethodBody (impls : Array TraitImpl) (d : Decl) : Bool :=
  impls.any fun ti =>
    ti.methods.any fun m => m.body == d.name

/-- Emit one `namespace …` block. Ordering, mirroring the standard
    Aeneas backend's output for a `traits_basic`-shaped crate:
    1. trait decls
    2. struct + enum decls
    3. impl method body `def`s
    4. trait impl instance `@[reducible] def`s
    5. remaining (caller) `def`s

    For a crate with no traits / no impls the order collapses to
    the M9.5b shape (structs/enums first, then all functions). -/
def emitNamespace (c : String) (traits : Array TraitDecl)
    (structs : Array StructDecl) (enums : Array EnumDecl)
    (impls : Array TraitImpl) (decls : Array Decl) : String :=
  -- M9.5o: each `emit*` already ends with `\n`; joining with another
  -- `\n` would introduce a redundant blank line between siblings.
  -- Use `String.join` so a chain of N traits is `td1\n + td2\n` not
  -- `td1\n\ntd2\n`.
  let traitBody := String.join (traits.toList.map emitTraitDecl)
  let structBody := String.intercalate "\n" (structs.toList.map emitStruct)
  let enumBody := String.intercalate "\n" (enums.toList.map emitEnum)
  -- M9.5o: default-method body decls are emitted between the trait
  -- decl and the impl method bodies. Detect them by the `.default`
  -- name suffix produced by the Driver's defaultRenameByName pass.
  let isDefaultMethod := fun (d : Decl) => d.name.endsWith ".default"
  -- Split function decls into default-method / impl-method / caller.
  let defaults := decls.filter isDefaultMethod
  let implMethods := decls.filter (fun d =>
    !isDefaultMethod d && isImplMethodBody impls d)
  let callerDecls := decls.filter (fun d =>
    !isDefaultMethod d && !isImplMethodBody impls d)
  let defaultBody :=
    String.intercalate "\n" (defaults.toList.map emitDecl)
  let implFnBody :=
    String.intercalate "\n" (implMethods.toList.map emitDecl)
  let implInstBody :=
    String.intercalate "\n" (impls.toList.map emitTraitImpl)
  let callerFnBody :=
    String.intercalate "\n" (callerDecls.toList.map emitDecl)
  let sepT := if traits.isEmpty then "" else "\n"
  let sepS := if structs.isEmpty then "" else "\n"
  let sepE := if enums.isEmpty then "" else "\n"
  let sepD := if defaults.isEmpty then "" else "\n"
  let sepIM := if implMethods.isEmpty then "" else "\n"
  let sepII := if impls.isEmpty then "" else "\n"
  -- M9.5o: when there are no caller decls, the preceding section's
  -- trailing newline already provides the blank line before `end`;
  -- adding another `\n` would yield two visible blank lines.
  let endSep := if callerDecls.isEmpty then "" else "\n"
  s!"namespace {c}\n\n"
    ++ traitBody ++ sepT
    ++ structBody ++ sepS
    ++ enumBody ++ sepE
    ++ defaultBody ++ sepD
    ++ implFnBody ++ sepIM
    ++ implInstBody ++ sepII
    ++ callerFnBody
    ++ s!"{endSep}end {c}\n"

/-- Top-level entry: header + one namespace block per crate. Type
    decls (structs + enums) come before functions in each namespace.

    M9.5l: trait decls come BEFORE structs/enums; trait impls go
    between impl method body `def`s and caller `def`s — see
    `emitNamespace` for the full ordering. -/
def emitTranslatedCrate (crateName : String) (tc : TranslatedCrate) : String :=
  let groups := groupByCrate tc.decls
  let structBuckets := groupStructsByCrate tc.structs
  let enumBuckets := groupEnumsByCrate tc.enums
  let traitDeclBuckets := groupTraitDeclsByCrate tc.traitDecls
  let traitImplBuckets := groupTraitImplsByCrate tc.traitImpls
  let header := emitHeader crateName
  -- M9.5b: a crate may have type decls but no function decls (rare).
  -- For now the grouping iterates only crates that have function
  -- decls; type decls in unreferenced crates are dropped. The
  -- fixtures under test all have at least one function per crate.
  let namespaces :=
    String.intercalate "\n" (groups.toList.map fun (c, ds) =>
      emitNamespace c
        (traitDeclBuckets.getD c #[])
        (structBuckets.getD c #[])
        (enumBuckets.getD c #[])
        (traitImplBuckets.getD c #[])
        ds)
  header ++ namespaces

end AeneasCheck.Backends
