import AeneasCheck.Pure.Pretty
import AeneasCheck.Translate.Driver

/-!
Rust source-code backend.

Each Pure decl `def f (x1 .. xn : T) : Result T := body` becomes a
Rust fn `pub fn f_model(x1 .. xn : T) -> T { … }` whose body is a
direct transliteration of the Pure expression.

Functions that originally took `&mut T` references in Rust are
emitted as functions that *take and return* `T` — this is the
differential-test convention: the model returns the updated value so
proptest can compare it to running the original function on a fresh
local.
-/

open AeneasCheck Raw Pure Translate

namespace AeneasCheck.Pure

partial def PTy.toRust : PTy → String
  | .unit => "()"
  | .lit (.int k) => IntKind.toRust k
  | .lit .bool => "bool"
  | .lit .char => "char"
  | .lit (.float _) => "f64"
  | .adt name args =>
    if args.isEmpty then name
    else s!"{name}<{String.intercalate ", " (args.toList.map PTy.toRust)}>"
  | .tuple args =>
    "(" ++ String.intercalate ", " (args.toList.map PTy.toRust) ++ ")"
  | .result inner => inner.toRust  -- M8: drop the Result wrapper

def litToRust : Lit → String
  | .scalar k v => s!"{v}{IntKind.toRust k}"
  | .bool b => toString b
  | .char c => s!"'\\u\{{c}}'"
  | .str s => s!"\"{s}\""
  | .byteStr _ => "b\"<bytestr>\""

partial def PExpr.toRust : PExpr → String
  | .var name => name
  | .lit l => litToRust l
  | .app head args =>
    if args.isEmpty then head
    else s!"{head}(" ++ String.intercalate ", " (args.toList.map PExpr.toRust) ++ ")"
  | .letIn name _ e1 e2 =>
    s!"let {name} = {e1.toRust};\n    {e2.toRust}"
  -- M8 drops the .ok wrapper: the Rust model returns the value directly.
  | .ok inner => inner.toRust

end AeneasCheck.Pure

namespace AeneasCheck.Backends

open AeneasCheck Pure

def sanitizeRustName (n : String) : String :=
  -- Lean's `::` and `.` are not valid in Rust function names. Take the
  -- last segment and append `_model` so we don't collide with the
  -- original Rust function.
  let segs := (n.replace "::" ".").splitOn "."
  let basename := segs.getLast?.getD n
  basename ++ "_model"

def emitDeclRust (d : Decl) : String :=
  let params := String.intercalate ", "
    (d.params.toList.map fun p => s!"{p.name}: {p.ty.toRust}")
  let retTy := d.retTy.toRust
  let body := d.body.toRust
  let fnName := sanitizeRustName d.name
  "pub fn " ++ fnName ++ "(" ++ params ++ ") -> " ++ retTy ++ " {\n    " ++
    body ++ "\n}\n"

def emitTranslatedCrateRust (crateName : String) (tc : TranslatedCrate) : String :=
  -- Decls are emitted without an inner `#![allow(...)]` so the file
  -- can be `include!`'d from a lib root that already sets the
  -- relevant lints crate-wide.
  let header :=
    s!"// THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS-LEAN-CHECKER\n" ++
    s!"// Crate: {crateName}\n\n"
  header ++ String.intercalate "\n" (tc.decls.toList.map emitDeclRust)

end AeneasCheck.Backends
