-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [hax_specs]
import Aeneas
import Hax
open Aeneas Aeneas.Std RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace hax_specs

/-- [core::ops::arith::{impl core::ops::arith::Add<&'_0 u32, u32> for &'_1 u32}::add]:
    Source: '/rustc/library/core/src/internal_macros.rs', lines 49:12-49:68
    Name pattern: [core::ops::arith::{core::ops::arith::Add<&'1 u32, &'0 u32, u32>}::add]
    Visibility: public -/
@[rust_fun
  "core::ops::arith::{core::ops::arith::Add<&'1 u32, &'0 u32, u32>}::add"]
axiom Shared1U32.Insts.CoreOpsArithAddShared0U32U32.add
  : Std.U32 → Std.U32 → RustM Std.U32

/-- [hax_specs::basic::only_requires]:
    Source: 'src/lib.rs', lines 6:4-8:5 -/
def basic.only_requires (x : Std.U32) : RustM Std.U32 := do
  x + 1#u32

/-- [hax_specs::basic::only_ensures]:
    Source: 'src/lib.rs', lines 11:4-13:5 -/
def basic.only_ensures (x : Std.U32) : RustM Std.U32 := do
  ok x

/-- [hax_specs::basic::both]:
    Source: 'src/lib.rs', lines 17:4-19:5 -/
def basic.both (x : Std.U32) : RustM Std.U32 := do
  x + 1#u32

/-- [hax_specs::basic::no_args]:
    Source: 'src/lib.rs', lines 23:4-26:5 -/
def basic.no_args : RustM Unit := do
  ok ()

/-- [hax_specs::basic::returns_unit]:
    Source: 'src/lib.rs', lines 31:4-31:30 -/
def basic.returns_unit (x : Std.U32) : RustM Unit := do
  ok ()

/-- [hax_specs::basic::block_in_requires]:
    Source: 'src/lib.rs', lines 35:4-37:5 -/
def basic.block_in_requires (x : Std.U32) : RustM Std.U32 := do
  ok x

/-- [hax_specs::basic::returns_pair]:
    Source: 'src/lib.rs', lines 41:4-43:5 -/
def basic.returns_pair (x : Std.U32) : RustM (Std.U32 × Std.U32) := do
  ok (x, x)

/-- [hax_specs::extra_args::generic]:
    Source: 'src/lib.rs', lines 53:4-55:5 -/
def extra_args.generic (N : Std.U32) (x : Std.U32) : RustM Std.U32 := do
  N - x

/-- Trait declaration: [hax_specs::extra_args::Val]
    Source: 'src/lib.rs', lines 58:4-60:5 -/
structure extra_args.Val (Self : Type) where
  value : Self → RustM Std.U32

/-- [hax_specs::extra_args::{impl hax_specs::extra_args::Val for u32}::value]:
    Source: 'src/lib.rs', lines 63:8-65:9 -/
def U32.Insts.Hax_specsExtra_argsVal.value
  (self : Std.U32) : RustM Std.U32 := do
  ok self

/-- Trait implementation: [hax_specs::extra_args::{impl hax_specs::extra_args::Val for u32}]
    Source: 'src/lib.rs', lines 62:4-66:5 -/
@[reducible]
def U32.Insts.Hax_specsExtra_argsVal : extra_args.Val Std.U32 := {
  value := U32.Insts.Hax_specsExtra_argsVal.value
}

/-- [hax_specs::extra_args::traits]:
    Source: 'src/lib.rs', lines 70:4-72:5 -/
def extra_args.traits
  {T : Type} (ValInst : extra_args.Val T) (t : T) (x : Std.U32) :
  RustM Std.U32
  := do
  let i ← ValInst.value t
  i + x

/-- [hax_specs::future::incr]:
    Source: 'src/lib.rs', lines 81:4-83:5 -/
def future.incr (x : Std.U32) : RustM Std.U32 := do
  x + 1#u32

/-- [hax_specs::future::incr_i]:
    Source: 'src/lib.rs', lines 89:4-91:5 -/
def future.incr_i
  (x : Slice Std.U32) (i : Std.Usize) : RustM (Slice Std.U32) := do
  let i1 ← Slice.index_usize x i
  let i2 ← i1 + 1#u32
  Slice.update x i i2

/-- [hax_specs::future::swap_and_add]:
    Source: 'src/lib.rs', lines 95:4-101:5 -/
def future.swap_and_add
  (x : Std.U32) (y : Std.U32) : RustM (Std.U32 × Std.U32 × Std.U32) := do
  let i ← x + y
  ok (i, y, x)

/-- [hax_specs::const_generic_ty::MyStruct]
    Source: 'src/lib.rs', lines 113:4-115:5
    Visibility: public -/
structure const_generic_ty.MyStruct (N : Std.Usize) where
  cap : Std.Usize

/-- [hax_specs::const_generic_ty::{hax_specs::const_generic_ty::MyStruct<N>}::build]:
    Source: 'src/lib.rs', lines 123:8-125:9
    Visibility: public -/
def const_generic_ty.MyStruct.build
  (N : Std.Usize) (k : Std.Usize) : RustM (const_generic_ty.MyStruct N) := do
  ok { cap := k }

/-- [hax_specs::const_generic_ty::{hax_specs::const_generic_ty::MyStruct<N>}::get]:
    Source: 'src/lib.rs', lines 129:8-131:9
    Visibility: public -/
def const_generic_ty.MyStruct.get
  {N : Std.Usize} (self : const_generic_ty.MyStruct N) : RustM Std.Usize := do
  ok self.cap

/-- [hax_specs::implicit_generics::Pair]
    Source: 'src/lib.rs', lines 139:4-141:5
    Visibility: public -/
structure implicit_generics.Pair (T : Type) (N : Std.Usize) where
  fst : T

/-- [hax_specs::implicit_generics::nothing]:
    Source: 'src/lib.rs', lines 147:4-149:5 -/
def implicit_generics.nothing
  (T : Type) (k : Std.Usize) : RustM (Option T) := do
  ok none

/-- [hax_specs::implicit_generics::of_fst]:
    Source: 'src/lib.rs', lines 153:4-155:5 -/
def implicit_generics.of_fst
  {T : Type} (N : Std.Usize) (t : T) : RustM (implicit_generics.Pair T N) := do
  ok { fst := t }

/-- [hax_specs::implicit_generics::empty]:
    Source: 'src/lib.rs', lines 159:4-161:5 -/
def implicit_generics.empty
  (T : Type) (N : Std.Usize) (k : Std.Usize) :
  RustM (Option (implicit_generics.Pair T N))
  := do
  ok none

/-- [hax_specs::implicit_generics::from_default]:
    Source: 'src/lib.rs', lines 167:4-169:5 -/
def implicit_generics.from_default
  {T : Type} (N : Std.Usize) (coredefaultDefaultInst : core.default.Default T)
  (k : Std.Usize) :
  RustM (implicit_generics.Pair T N)
  := do
  let t ← coredefaultDefaultInst.default
  ok { fst := t }

/-- Trait declaration: [hax_specs::unit_args::Size]
    Source: 'src/lib.rs', lines 178:4-180:5 -/
structure unit_args.Size (Self : Type) where
  len : Self → RustM Std.Usize

/-- [hax_specs::unit_args::{impl hax_specs::unit_args::Size for ()}::len]:
    Source: 'src/lib.rs', lines 186:8-188:9 -/
def Tuple.Insts.Hax_specsUnit_argsSize.len (_ : Unit) : RustM Std.Usize := do
  ok 0#usize

/-- Trait implementation: [hax_specs::unit_args::{impl hax_specs::unit_args::Size for ()}]
    Source: 'src/lib.rs', lines 184:4-189:5 -/
@[reducible]
def Tuple.Insts.Hax_specsUnit_argsSize : unit_args.Size Unit := {
  len := Tuple.Insts.Hax_specsUnit_argsSize.len
}

/-- [hax_specs::unit_args::named]:
    Source: 'src/lib.rs', lines 192:4-194:5 -/
def unit_args.named (_ : Unit) : RustM Std.Usize := do
  ok 0#usize

/-- [hax_specs::unit_args::before_other]:
    Source: 'src/lib.rs', lines 199:4-201:5 -/
def unit_args.before_other (_ : Unit) (y : Std.U32) : RustM Std.U32 := do
  ok y

/-- Trait declaration: [hax_specs::supertraits::A]
    Source: 'src/lib.rs', lines 210:4-212:5
    Visibility: public -/
structure supertraits.A (Self : Type) where
  a : Self → RustM Std.Usize

/-- Trait declaration: [hax_specs::supertraits::B]
    Source: 'src/lib.rs', lines 215:4-223:5
    Visibility: public -/
structure supertraits.B (Self : Type) where
  AInst : supertraits.A Self
  b : Self → RustM Std.Usize
  provided : Self → RustM Std.Usize

/-- [hax_specs::supertraits::B::provided]:
    Source: 'src/lib.rs', lines 220:8-222:9
    Visibility: public -/
@[trait_default]
def supertraits.B.provided.default
  {Self : Type} (BInst : supertraits.B Self) (self : Self) :
  RustM Std.Usize
  := do
  BInst.AInst.a self

/-- Trait declaration: [hax_specs::supertraits::C]
    Source: 'src/lib.rs', lines 227:4-232:5
    Visibility: public -/
structure supertraits.C (Self : Type) where
  BInst : supertraits.B Self
  provided_c : Self → RustM Std.Usize

/-- [hax_specs::supertraits::C::provided_c]:
    Source: 'src/lib.rs', lines 229:8-231:9
    Visibility: public -/
@[trait_default]
def supertraits.C.provided_c.default
  {Self : Type} (CInst : supertraits.C Self) (self : Self) :
  RustM Std.Usize
  := do
  CInst.BInst.AInst.a self

/-- Trait declaration: [hax_specs::supertraits::G]
    Source: 'src/lib.rs', lines 235:4-237:5
    Visibility: public -/
structure supertraits.G (Self : Type) (T : Type) where
  g : Self → RustM T

/-- Trait declaration: [hax_specs::supertraits::H]
    Source: 'src/lib.rs', lines 240:4-245:5
    Visibility: public -/
structure supertraits.H (Self : Type) (T : Type) where
  GInst : supertraits.G Self T
  provided_h : Self → RustM T

/-- [hax_specs::supertraits::H::provided_h]:
    Source: 'src/lib.rs', lines 242:8-244:9
    Visibility: public -/
@[trait_default]
def supertraits.H.provided_h.default
  {Self : Type} {T : Type} (HInst : supertraits.H Self T) (self : Self) :
  RustM T
  := do
  HInst.GInst.g self


/-- [hax_specs::basic::only_requires::pre]:
    Source: 'src/lib.rs', lines 5:4-5:24 -/
@[reducible]
def basic.only_requires.pre (x : Std.U32) : RustM Bool := do
  ok (x < 100#u32)

def basic.only_requires.spec (x : Std.U32) : Prop :=
  (basic.only_requires.pre x).holds →
  ⦃ ⌜ True ⌝ ⦄
  basic.only_requires x
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [hax_specs::basic::only_ensures::post]:
    Source: 'src/lib.rs', lines 10:4-10:36 -/
@[reducible]
def basic.only_ensures.post (x : Std.U32) (result : Std.U32) : RustM Bool := do
  ok (result = x)

def basic.only_ensures.spec (x : Std.U32) : Prop :=
  ⦃ ⌜ True ⌝ ⦄
  basic.only_ensures x
  ⦃ ⇓ res => ⌜ (basic.only_ensures.post x res).holds ⌝ ⦄


/-- [hax_specs::basic::both::pre]:
    Source: 'src/lib.rs', lines 15:4-15:23 -/
@[reducible]
def basic.both.pre (x : Std.U32) : RustM Bool := do
  ok (x < 10#u32)

/-- [hax_specs::basic::both::post]:
    Source: 'src/lib.rs', lines 16:4-16:35 -/
@[reducible]
def basic.both.post (x : Std.U32) (result : Std.U32) : RustM Bool := do
  ok (result > x)

def basic.both.spec (x : Std.U32) : Prop :=
  (basic.both.pre x).holds →
  ⦃ ⌜ True ⌝ ⦄
  basic.both x
  ⦃ ⇓ res => ⌜ (basic.both.post x res).holds ⌝ ⦄


/-- [hax_specs::basic::returns_unit::pre]:
    Source: 'src/lib.rs', lines 29:4-29:23 -/
@[reducible]
def basic.returns_unit.pre (x : Std.U32) : RustM Bool := do
  ok (x < 10#u32)

/-- [hax_specs::basic::returns_unit::post]:
    Source: 'src/lib.rs', lines 30:4-30:24 -/
@[reducible]
def basic.returns_unit.post (x : Std.U32) (_ : Unit) : RustM Bool := do
  ok true

def basic.returns_unit.spec (x : Std.U32) : Prop :=
  (basic.returns_unit.pre x).holds →
  ⦃ ⌜ True ⌝ ⦄
  basic.returns_unit x
  ⦃ ⇓ res => ⌜ (basic.returns_unit.post x res).holds ⌝ ⦄


/-- [hax_specs::basic::block_in_requires::pre]:
    Source: 'src/lib.rs', lines 34:4-34:46 -/
@[reducible]
def basic.block_in_requires.pre (x : Std.U32) : RustM Bool := do
  ok (x > 10#u32)

def basic.block_in_requires.spec (x : Std.U32) : Prop :=
  (basic.block_in_requires.pre x).holds →
  ⦃ ⌜ True ⌝ ⦄
  basic.block_in_requires x
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [hax_specs::basic::returns_pair::post]:
    Source: 'src/lib.rs', lines 40:4-40:41 -/
@[reducible]
def basic.returns_pair.post
  (x : Std.U32) (p : (Std.U32 × Std.U32)) : RustM Bool := do
  let (a, b) := p
  if a = x
  then ok (b = x)
  else ok false

def basic.returns_pair.spec (x : Std.U32) : Prop :=
  ⦃ ⌜ True ⌝ ⦄
  basic.returns_pair x
  ⦃ ⇓ res => ⌜ (basic.returns_pair.post x res).holds ⌝ ⦄


/-- [hax_specs::extra_args::generic::pre]:
    Source: 'src/lib.rs', lines 51:4-51:31 -/
@[reducible]
def extra_args.generic.pre (N : Std.U32) (x : Std.U32) : RustM Bool := do
  if 0#u32 < x
  then ok (x < N)
  else ok false

/-- [hax_specs::extra_args::generic::post]:
    Source: 'src/lib.rs', lines 52:4-52:35 -/
@[reducible]
def extra_args.generic.post
  (N : Std.U32) (x : Std.U32) (result : Std.U32) : RustM Bool := do
  ok (result < N)

def extra_args.generic.spec (N : Std.U32) (x : Std.U32) : Prop :=
  (extra_args.generic.pre N x).holds →
  ⦃ ⌜ True ⌝ ⦄
  extra_args.generic N x
  ⦃ ⇓ res => ⌜ (extra_args.generic.post N x res).holds ⌝ ⦄


/-- [hax_specs::extra_args::traits::pre]:
    Source: 'src/lib.rs', lines 68:4-68:45 -/
@[reducible]
def extra_args.traits.pre
  {T : Type} (ValInst : extra_args.Val T) (t : T) (x : Std.U32) :
  RustM Bool
  := do
  let i ← ValInst.value t
  if i < 1000#u32
  then ok (x < 1000#u32)
  else ok false

/-- [hax_specs::extra_args::traits::post]:
    Source: 'src/lib.rs', lines 69:4-69:38 -/
@[reducible]
def extra_args.traits.post
  {T : Type} (ValInst : extra_args.Val T) (t : T) (x : Std.U32)
  (result : Std.U32) :
  RustM Bool
  := do
  ok (result < 2000#u32)

def extra_args.traits.spec {T : Type} (ValInst : extra_args.Val T) (t : T)
  (x : Std.U32) : Prop :=
  (extra_args.traits.pre ValInst t x).holds →
  ⦃ ⌜ True ⌝ ⦄
  extra_args.traits ValInst t x
  ⦃ ⇓ res => ⌜ (extra_args.traits.post ValInst t x res).holds ⌝ ⦄


/-- [hax_specs::future::incr::pre]:
    Source: 'src/lib.rs', lines 79:4-79:26 -/
@[reducible]
def future.incr.pre (x : Std.U32) : RustM Bool := do
  ok (x < 1000#u32)

/-- [hax_specs::future::incr::post]:
    Source: 'src/lib.rs', lines 80:4-80:41 -/
@[reducible]
def future.incr.post (x : Std.U32) (x_future : Std.U32) : RustM Bool := do
  let i ← x + 1#u32
  ok (x_future = i)

def future.incr.spec (x : Std.U32) : Prop :=
  (future.incr.pre x).holds →
  ⦃ ⌜ True ⌝ ⦄
  future.incr x
  ⦃ ⇓ res => ⌜ (future.incr.post x res).holds ⌝ ⦄


/-- [hax_specs::future::incr_i::pre]:
    Source: 'src/lib.rs', lines 85:4-85:28 -/
@[reducible]
def future.incr_i.pre (x : Slice Std.U32) (i : Std.Usize) : RustM Bool := do
  let i1 := Slice.len x
  ok (i < i1)

/-- [hax_specs::future::incr_i::post]:
    Source: 'src/lib.rs', lines 86:4-88:31 -/
@[reducible]
def future.incr_i.post
  (x : Slice Std.U32) (i : Std.Usize) (x_future : Slice Std.U32) :
  RustM Bool
  := do
  let i1 ← Slice.index_usize x_future i
  let i2 ← Slice.index_usize x i
  let i3 ← i2 + 1#u32
  ok (i1 = i3)

def future.incr_i.spec (x : Slice Std.U32) (i : Std.Usize) : Prop :=
  (future.incr_i.pre x i).holds →
  ⦃ ⌜ True ⌝ ⦄
  future.incr_i x i
  ⦃ ⇓ res => ⌜ (future.incr_i.post x i res).holds ⌝ ⦄


/-- [hax_specs::future::swap_and_add::pre]:
    Source: 'src/lib.rs', lines 93:4-93:39 -/
@[reducible]
def future.swap_and_add.pre (x : Std.U32) (y : Std.U32) : RustM Bool := do
  if x < 1000#u32
  then ok (y < 1000#u32)
  else ok false

/-- [hax_specs::future::swap_and_add::post]:
    Source: 'src/lib.rs', lines 94:4-94:73 -/
@[reducible]
def future.swap_and_add.post
  (x : Std.U32) (y : Std.U32) (t : (Std.U32 × Std.U32 × Std.U32)) :
  RustM Bool
  := do
  let (x_future, y_future, r) := t
  if y_future = x
  then
    if x_future = y
    then
      let i ← Shared1U32.Insts.CoreOpsArithAddShared0U32U32.add x y
      ok (r = i)
    else ok false
  else ok false

def future.swap_and_add.spec (x : Std.U32) (y : Std.U32) : Prop :=
  (future.swap_and_add.pre x y).holds →
  ⦃ ⌜ True ⌝ ⦄
  future.swap_and_add x y
  ⦃ ⇓ res => ⌜ (future.swap_and_add.post x y res).holds ⌝ ⦄


/-- [hax_specs::implicit_generics::nothing::post]:
    Source: 'src/lib.rs', lines 146:4-146:24 -/
@[reducible]
def implicit_generics.nothing.post
  {T : Type} (k : Std.Usize) (o : Option T) : RustM Bool := do
  ok true

def implicit_generics.nothing.spec (T : Type) (k : Std.Usize) : Prop :=
  ⦃ ⌜ True ⌝ ⦄
  implicit_generics.nothing T k
  ⦃ ⇓ res => ⌜ (implicit_generics.nothing.post k res).holds ⌝ ⦄


/-- [hax_specs::implicit_generics::of_fst::post]:
    Source: 'src/lib.rs', lines 152:4-152:24 -/
@[reducible]
def implicit_generics.of_fst.post
  {T : Type} {N : Std.Usize} (t : T) (p : implicit_generics.Pair T N) :
  RustM Bool
  := do
  ok true

def implicit_generics.of_fst.spec {T : Type} (N : Std.Usize) (t : T) : Prop :=
  ⦃ ⌜ True ⌝ ⦄
  implicit_generics.of_fst N t
  ⦃ ⇓ res => ⌜ (implicit_generics.of_fst.post t res).holds ⌝ ⦄


/-- [hax_specs::implicit_generics::empty::post]:
    Source: 'src/lib.rs', lines 158:4-158:24 -/
@[reducible]
def implicit_generics.empty.post
  {T : Type} {N : Std.Usize} (k : Std.Usize)
  (o : Option (implicit_generics.Pair T N)) :
  RustM Bool
  := do
  ok true

def implicit_generics.empty.spec (T : Type) (N : Std.Usize) (k : Std.Usize)
  : Prop :=
  ⦃ ⌜ True ⌝ ⦄
  implicit_generics.empty T N k
  ⦃ ⇓ res => ⌜ (implicit_generics.empty.post k res).holds ⌝ ⦄


/-- [hax_specs::implicit_generics::from_default::pre]:
    Source: 'src/lib.rs', lines 165:4-165:24 -/
@[reducible]
def implicit_generics.from_default.pre
  {T : Type} (N : Std.Usize) (coredefaultDefaultInst : core.default.Default T)
  (k : Std.Usize) :
  RustM Bool
  := do
  ok (k < 100#usize)

/-- [hax_specs::implicit_generics::from_default::post]:
    Source: 'src/lib.rs', lines 166:4-166:24 -/
@[reducible]
def implicit_generics.from_default.post
  {T : Type} {N : Std.Usize} (coredefaultDefaultInst : core.default.Default T)
  (k : Std.Usize) (p : implicit_generics.Pair T N) :
  RustM Bool
  := do
  ok true

def
  implicit_generics.from_default.spec {T : Type} (N : Std.Usize)
                                     (coredefaultDefaultInst :
                                     core.default.Default T) (k : Std.Usize)
  : Prop :=
  (implicit_generics.from_default.pre N coredefaultDefaultInst k).holds →
  ⦃ ⌜ True ⌝ ⦄
  implicit_generics.from_default N coredefaultDefaultInst k
  ⦃ ⇓ res =>
  ⌜ (implicit_generics.from_default.post coredefaultDefaultInst k res).holds
  ⌝ ⦄


/-- [hax_specs::unit_args::named::post]:
    Source: 'src/lib.rs', lines 191:4-191:36 -/
@[reducible]
def unit_args.named.post (_ : Unit) (result : Std.Usize) : RustM Bool := do
  ok (result = 0#usize)

def unit_args.named.spec (_ : Unit) : Prop :=
  ⦃ ⌜ True ⌝ ⦄
  unit_args.named ()
  ⦃ ⇓ res => ⌜ (unit_args.named.post () res).holds ⌝ ⦄


/-- [hax_specs::unit_args::before_other::pre]:
    Source: 'src/lib.rs', lines 197:4-197:24 -/
@[reducible]
def unit_args.before_other.pre (_ : Unit) (y : Std.U32) : RustM Bool := do
  ok (y < 100#u32)

/-- [hax_specs::unit_args::before_other::post]:
    Source: 'src/lib.rs', lines 198:4-198:36 -/
@[reducible]
def unit_args.before_other.post
  (_ : Unit) (y : Std.U32) (result : Std.U32) : RustM Bool := do
  ok (result = y)

def unit_args.before_other.spec (_ : Unit) (y : Std.U32) : Prop :=
  (unit_args.before_other.pre () y).holds →
  ⦃ ⌜ True ⌝ ⦄
  unit_args.before_other () y
  ⦃ ⇓ res => ⌜ (unit_args.before_other.post () y res).holds ⌝ ⦄


/-- [hax_specs::const_generic_ty::{hax_specs::const_generic_ty::MyStruct<N>}::build::pre]:
    Source: 'src/lib.rs', lines 121:8-121:28 -/
@[reducible]
def const_generic_ty.MyStruct.build.pre
  (N : Std.Usize) (k : Std.Usize) : RustM Bool := do
  ok (k < 100#usize)

/-- [hax_specs::const_generic_ty::{hax_specs::const_generic_ty::MyStruct<N>}::build::post]:
    Source: 'src/lib.rs', lines 122:8-122:28 -/
@[reducible]
def const_generic_ty.MyStruct.build.post
  {N : Std.Usize} (k : Std.Usize) (ms : const_generic_ty.MyStruct N) :
  RustM Bool
  := do
  ok true

def const_generic_ty.MyStruct.build.spec (N : Std.Usize) (k : Std.Usize)
  : Prop :=
  (const_generic_ty.MyStruct.build.pre N k).holds →
  ⦃ ⌜ True ⌝ ⦄
  const_generic_ty.MyStruct.build N k
  ⦃ ⇓ res => ⌜ (const_generic_ty.MyStruct.build.post k res).holds ⌝ ⦄


/-- [hax_specs::const_generic_ty::{hax_specs::const_generic_ty::MyStruct<N>}::get::post]:
    Source: 'src/lib.rs', lines 128:8-128:28 -/
@[reducible]
def const_generic_ty.MyStruct.get.post
  {N : Std.Usize} (self_ : const_generic_ty.MyStruct N) (i : Std.Usize) :
  RustM Bool
  := do
  ok true

def const_generic_ty.MyStruct.get.spec {N : Std.Usize}
  (self : const_generic_ty.MyStruct N) : Prop :=
  ⦃ ⌜ True ⌝ ⦄
  const_generic_ty.MyStruct.get self
  ⦃ ⇓ res => ⌜ (const_generic_ty.MyStruct.get.post self res).holds ⌝
  ⦄


/-- [hax_specs::unit_args::{impl hax_specs::unit_args::Size for ()}::len::post]:
    Source: 'src/lib.rs', lines 185:8-185:28 -/
@[reducible]
def unit_args.SizeTuple.len.post (_ : Unit) (i : Std.Usize) : RustM Bool := do
  ok true

def Tuple.Insts.Hax_specsUnit_argsSize.len.spec (_ : Unit) : Prop :=
  ⦃ ⌜ True ⌝ ⦄
  Tuple.Insts.Hax_specsUnit_argsSize.len ()
  ⦃ ⇓ res => ⌜ (unit_args.SizeTuple.len.post () res).holds ⌝ ⦄


/-- [hax_specs::supertraits::B::provided::pre]:
    Source: 'src/lib.rs', lines 214:4-214:26 -/
@[reducible]
def supertraits.B.provided.pre
  {Self_ : Type} (AInst : supertraits.A Self_) (BInst : supertraits.B Self_)
  (self_ : Self_) :
  RustM Bool
  := do
  let i ← AInst.a self_
  ok (i < 100#usize)

/-- [hax_specs::supertraits::B::provided::post]:
    Source: 'src/lib.rs', lines 214:4-214:26 -/
@[reducible]
def supertraits.B.provided.post
  {Self_ : Type} (AInst : supertraits.A Self_) (BInst : supertraits.B Self_)
  (self_ : Self_) (res : Std.Usize) :
  RustM Bool
  := do
  let i ← AInst.a self_
  ok (res = i)

def
  supertraits.B.provided.default.spec {Self : Type} (BInst : supertraits.B
                                     Self) (self : Self) : Prop :=
  (supertraits.B.provided.pre BInst.AInst BInst self).holds →
  ⦃ ⌜ True ⌝ ⦄
  supertraits.B.provided.default BInst self
  ⦃ ⇓ res =>
  ⌜ (supertraits.B.provided.post BInst.AInst BInst self res).holds ⌝ ⦄


/-- [hax_specs::supertraits::C::provided_c::post]:
    Source: 'src/lib.rs', lines 226:4-226:26 -/
@[reducible]
def supertraits.C.provided_c.post
  {Self_ : Type} (BInst : supertraits.B Self_) (CInst : supertraits.C Self_)
  (self_ : Self_) (res : Std.Usize) :
  RustM Bool
  := do
  let i ← BInst.AInst.a self_
  ok (res = i)

def
  supertraits.C.provided_c.default.spec {Self : Type} (CInst : supertraits.C
                                       Self) (self : Self) : Prop :=
  ⦃ ⌜ True ⌝ ⦄
  supertraits.C.provided_c.default CInst self
  ⦃ ⇓ res =>
  ⌜ (supertraits.C.provided_c.post CInst.BInst CInst self res).holds ⌝ ⦄


/-- [hax_specs::supertraits::H::provided_h::post]:
    Source: 'src/lib.rs', lines 239:4-239:26 -/
@[reducible]
def supertraits.H.provided_h.post
  {Self_ : Type} {T : Type} (GInst : supertraits.G Self_ T) (HInst :
  supertraits.H Self_ T) (self_ : Self_) (t : T) :
  RustM Bool
  := do
  ok true

def
  supertraits.H.provided_h.default.spec {Self : Type} {T : Type} (HInst :
                                       supertraits.H Self T) (self : Self)
  : Prop :=
  ⦃ ⌜ True ⌝ ⦄
  supertraits.H.provided_h.default HInst self
  ⦃ ⇓ res =>
  ⌜ (supertraits.H.provided_h.post HInst.GInst HInst self res).holds ⌝ ⦄

theorem basic.only_requires.spec.proof (x : Std.U32) :
  basic.only_requires.spec x
  := by sorry

theorem basic.only_ensures.spec.proof (x : Std.U32) : basic.only_ensures.spec x
  := by sorry

theorem basic.both.spec.proof (x : Std.U32) : basic.both.spec x := by sorry

theorem basic.returns_unit.spec.proof (x : Std.U32) : basic.returns_unit.spec x
  := by sorry

theorem basic.block_in_requires.spec.proof (x : Std.U32) :
  basic.block_in_requires.spec x
  := by sorry

theorem basic.returns_pair.spec.proof (x : Std.U32) : basic.returns_pair.spec x
  := by sorry

theorem extra_args.generic.spec.proof (N : Std.U32) (x : Std.U32) :
  extra_args.generic.spec N x
  := by sorry

theorem extra_args.traits.spec.proof {T : Type} (ValInst : extra_args.Val T)
  (t : T) (x : Std.U32) : extra_args.traits.spec ValInst t x
  := by sorry

theorem future.incr.spec.proof (x : Std.U32) : future.incr.spec x := by sorry

theorem future.incr_i.spec.proof (x : Slice Std.U32) (i : Std.Usize) :
  future.incr_i.spec x i
  := by sorry

theorem future.swap_and_add.spec.proof (x : Std.U32) (y : Std.U32) :
  future.swap_and_add.spec x y
  := by sorry

theorem implicit_generics.nothing.spec.proof (T : Type) (k : Std.Usize) :
  implicit_generics.nothing.spec T k
  := by sorry

theorem implicit_generics.of_fst.spec.proof {T : Type} (N : Std.Usize) 
  (t : T) : implicit_generics.of_fst.spec N t
  := by sorry

theorem implicit_generics.empty.spec.proof (T : Type) (N : Std.Usize)
  (k : Std.Usize) : implicit_generics.empty.spec T N k
  := by sorry

theorem
  implicit_generics.from_default.spec.proof {T : Type} (N : Std.Usize)
                                           (coredefaultDefaultInst :
                                           core.default.Default T)
  (k : Std.Usize) :
  implicit_generics.from_default.spec N coredefaultDefaultInst k
  := by sorry

theorem unit_args.named.spec.proof (_ : Unit) : unit_args.named.spec ()
  := by sorry

theorem unit_args.before_other.spec.proof (_ : Unit) (y : Std.U32) :
  unit_args.before_other.spec () y
  := by sorry

theorem const_generic_ty.MyStruct.build.spec.proof (N : Std.Usize)
  (k : Std.Usize) : const_generic_ty.MyStruct.build.spec N k
  := by sorry

theorem const_generic_ty.MyStruct.get.spec.proof {N : Std.Usize}
  (self : const_generic_ty.MyStruct N) :
  const_generic_ty.MyStruct.get.spec self
  := by sorry

theorem Tuple.Insts.Hax_specsUnit_argsSize.len.spec.proof (_ : Unit) :
  Tuple.Insts.Hax_specsUnit_argsSize.len.spec ()
  := by sorry

theorem
  supertraits.B.provided.default.spec.proof {Self : Type} (BInst :
                                           supertraits.B Self) (self : Self) :
  supertraits.B.provided.default.spec BInst self
  := by sorry

theorem
  supertraits.C.provided_c.default.spec.proof {Self : Type} (CInst :
                                             supertraits.C Self) (self : Self)
  : supertraits.C.provided_c.default.spec CInst self
  := by sorry

theorem
  supertraits.H.provided_h.default.spec.proof {Self : Type} {T : Type} (HInst :
                                             supertraits.H Self T)
  (self : Self) : supertraits.H.provided_h.default.spec HInst self
  := by sorry

end hax_specs
